### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by MacDhughaill** [mtkennerly/ludusavi#10]
It's just using a generic program icon right now. An icon specific to Ludusavi would be a nice touch.

**Comment by mtkennerly** [comment]
Agreed, this would be a nice addition. Iced (the GUI library I'm using) recently added window icon support (https://github.com/hecrj/iced/issues/433), but I'll need to wait for them to include it in a new release.

**Comment by mtkennerly** [comment]
I was able to do this sooner than anticipated by using [Realia](https://crates.io/crates/realia) for conditional compilation. I'm not much of a graphic designer, but I think it turned out okay \:D This will be included in the next release.

In the window:

> ![image](https://user-images.githubusercontent.com/4934192/88240275-a1144200-cc54-11ea-8cf5-a85e7cfd77bd.png)

In the task bar:

> ![image](https://user-images.githubusercontent.com/4934192/88240281-a40f3280-cc54-11ea-8350-5918d5e07d39.png)
