### ISSUE TITLE
Cyberpunk 2077

### ISSUE THREAD

**Issue by Marc05** [mtkennerly/ludusavi#101]
Game saves for Cyberpunk 2077 don't show up after a scan. Adding it as a custom game does not work either.

The correct entries appear in the manifest:
https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml

`<home>/Saved Games/CD Projekt Red/Cyberpunk 2077:`

The screenshots folder from steam does show up in the scan.

**Comment by Marc05** [comment]
Restarting the app after adding a custom entry worked. I then removed the custom entry and restarted the app again and it continued to detect it. I'm not sure what happened there.

**Comment by mtkennerly** [comment]
Did you play the game for the first time while Ludusavi was already open? When you open Ludusavi and do a backup/preview, it performs a full scan, but then if you do another backup/preview, it only re-scans the games it found before, unless certain settings change or you restart Ludusavi. It *should* always re-scan custom games, though.

**Comment by Marc05** [comment]
I did not. I opened the app, clicked preview on backup mode, saw that only the screenshots were being detected, clicked on the edit icon and removed all but the relevant path, restarted, and it worked. I then removed the custom entry, restarted, and it continued to work.

**Comment by mtkennerly** [comment]
Hmm, I don't have any idea what would cause that then, unfortunately :/

**Comment by Marc05** [comment]
I'll close this out since it doesn't make any sense and it's currently working.

**Comment by Marc05** [comment]
Re-opening. Looks like it's happening with Half-Life Alyx as well.
![backup](https://user-images.githubusercontent.com/1699133/175719751-b831a024-656d-4e2d-abc6-78e44eea81e3.png)
![custom](https://user-images.githubusercontent.com/1699133/175719754-b743d2cb-d09a-480c-b250-80e133ac2923.png)
![saves](https://user-images.githubusercontent.com/1699133/175719755-f5e5c224-0a47-49c6-81a0-f92bf88178e2.png)

Except it's not detecting it at all currently, ever after restarting multiple times.
