### ISSUE TITLE
UI doesn't work on KDE with Wayland

### ISSUE THREAD

**Issue by ThaChillera** [mtkennerly/ludusavi#104]
version: 0.10.0
environment: arch linux, KDE 5.25.3

When starting ludusavi, it fails with the following error message:
> [wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.

I'm 95% sure this has worked in the past, so it might be a regression of KDE.

I found [this issue](https://github.com/rust-windowing/winit/issues/1942) which might be related, but I'm not familiar with rust or its package management systems, so I'm not sure if you use this dependency.

**Comment by mtkennerly** [comment]
Per https://github.com/mtkennerly/ludusavi/issues/91, Ludusavi (both 0.10.0 and a newer preview) work on Steam Deck's game mode, which uses Wayland. That makes it seem like this is something specific to KDE.

**Comment by ThaChillera** [comment]
@mtkennerly Sorry for the late reply, but yes, the linked ludusavi build works perfectly :)

**Comment by nesteiner** [comment]
sorry to bother you, I found something wrong with my situation, when configure with `--with-webrender`, and when running emacs, it has the error:
![image](https://user-images.githubusercontent.com/46296608/185742972-aa7df77b-e2a2-4c47-b065-14a97a05d391.png)

I am using the KDE wayland, and I have not try other platform

**Comment by mtkennerly** [comment]
@nesteiner I'm not quite sure how that issue relates to Ludusavi. Does Emacs specifically crash while Ludusavi is also running? If Ludusavi isn't involved, then you may want to check the Emacs bug reporting procedure: https://www.gnu.org/software/emacs/manual/html_node/emacs/Bugs.html

**Comment by nesteiner** [comment]
@mtkennerly it does not releate to Ludusavi, after `sudo make install`, typing `emacs`, the error occur.  
eh, maybe I should remove `--with-webrender`
