### ISSUE TITLE
Add missing spacing to some UI elements

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#105]
Currently, the row of buttons along the top of the window are right up against the title bar on Windows which looks quite cramped. This is unlike the rest of the UI which does not touch the very bounds of the window. Some spacing between the top buttons and the title bar would help to improve Ludusavi's appearance.

As seen in the following screenshot, there are a few others issues:

- There is a lack of margin on left and right sides of the top buttons row which should also be added.
- The Other button on the top row shrinks up to the bounds of the text within it, rather than maintaining a minimum size that includes some padding. 
- Notice that the right-most button on the second row of buttons, the blue Search button, shrinks into a thin vertical pill shape when it should obviously remain large enough to still display the search icon itself.
- Likewise, the Duplicates indicator (now a black and white pill shape) next to the MiB value has no reasonable minimum size. Same for the "Selecting # games" indicator to the right of it.

If the Ludusavi window itself included some default padding, then the individual elements would need less tuning and could be allowed to extend to their bounds without the UI resulting in a cramped look.

![ludusavi](https://user-images.githubusercontent.com/25013746/180175015-8dc0ca12-0448-4e11-9532-c5e336d76d67.png)

Thanks.

Ludusavi 0.10.0
Windows 11

**Comment by mtkennerly** [comment]
Thanks for bringing this up! I'll look into this.

**Comment by mtkennerly** [comment]
I've adjusted the margin, but the pill shape issue will have to wait on https://github.com/iced-rs/iced/issues/1397.

**Comment by mtkennerly** [comment]
As a temporary solution, I've increased the minimum window size from 640x480 to 800x600. This avoids the pill shape issue (for now) and ensures the backup path field is usable with the new full/differential controls:

> <img width="603" alt="image" src="https://user-images.githubusercontent.com/4934192/184046774-119b0ce7-a6d5-4759-858c-ce194ed63677.png">
