### ISSUE TITLE
Wiki / Manual - What is Merge

### ISSUE THREAD

**Issue by JJohn86** [mtkennerly/ludusavi#108]
Sorry.. I'm not sure if this is the standard place to ask a question, but couldn't find anywhere else. 

What does the "merge" option do?

**Comment by mtkennerly** [comment]
Hi! No worries; this is the right place to ask.

If you already have a backup and you make another one, then:

* With merge disabled, the old backup folder will be deleted, and the new backup will happen from scratch.
* With merge enabled, whichever games you're backing up will be added/updated in the old backup folder. For example, if you only select to back up 10 games, then just those 10 will be updated in the backup folder, and any others will stay how they were. For the games that do get updated, Ludusavi will only copy over new/changed files, and then it will remove any old backup files for that game if it couldn't find them on your system.
