### ISSUE TITLE
Cancelling is slow

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#114]
Cancelling a scan will show "Cancelling..." until the entire scan has been done in the background (at least, according to the progress bar).

Ludusavi 0.11.0
Windows 11

**Comment by mtkennerly** [comment]
The reason for this is that, at the start of the backup, Ludusavi creates a list of asynchronous tasks, one per game, and then waits for all tasks to finish. When a task starts, it checks whether the user has pressed cancel, and if so, it just doesn't do anything. But every task still has to start up and check if it's been cancelled.

I'll see if I can improve this by just creating a few tasks at the start and only scheduling more in a rolling fashion.

**Comment by mtkennerly** [comment]
Fixed:

> ![zuNC1T9Mmi](https://user-images.githubusercontent.com/4934192/186025572-044c35d4-9650-4e1f-88d8-62ccf2338026.gif)
