### ISSUE TITLE
Desktop icon not showing

### ISSUE THREAD

**Issue by 24788329** [mtkennerly/ludusavi#116]
After adding [ludusavi.desktop](https://github.com/mtkennerly/ludusavi/blob/master/assets/ludusavi.desktop) to `/usr/share/applications`, Ludusavi shows up in desktop apps but without the correct icon.

Removing ludusavi.desktop also removes Ludusavi from the desktop apps list. Launching ludusavi from the command line then correctly brings up the right desktop app icon. However, I want the Ludusavi desktop app icon to be both persistent and correct. 

How do I fix ludusavi.desktop to show the right icon? Using Pop!_OS 20.04 with Ludusavi installed by downloading the executable.

**Comment by mtkennerly** [comment]
Hi! I'm able to get it working on a fresh Ubuntu system like this:

* Put `ludusavi` executable in `/usr/local/bin` (or anywhere on the PATH)
* Copy ludusavi.desktop to `/usr/share/applications/ludusavi.desktop`
* Copy icon.svg to `/usr/share/icons/ludusavi.svg`

I'm not sure how Pop!_OS might differ. You could also try adding `TryExec=ludusavi` to the desktop file  or specifying the icon's file extension explicitly, if that's something the distro needs.

> <img width="515" alt="image" src="https://user-images.githubusercontent.com/4934192/186789244-77074636-bdd0-44f3-9e76-76a8816d76cc.png">

> <img width="515" alt="image" src="https://user-images.githubusercontent.com/4934192/186789267-3bdfaaad-8163-4ae2-aeba-d61234828b5e.png">

**Comment by 24788329** [comment]
Hey thanks for the help. It was the icon.svg file that I did incorrectly. Appreciate the work you've put into this project.

**Comment by 24788329** [comment]
Hey thanks for the help. It was the icon.svg file that I did incorrectly. Appreciate the work you've put into this project.
