### ISSUE TITLE
Improvements to Duplicates

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#117]
Some thoughts and ideas on duplicates and how their handled:

- The Duplicates pill label next to a game's title could be clickable and reveal a list of games that are flagging the clicked game as having duplicates. This would help with unchecking other games / games' files to reduce backing up duplicate data. How detailed should this list be, I'm not sure. For example, should it also include the specific duplicated files in question, or only provide a list of games? Perhaps the games shown in this list could also be clickable and scroll the UI to that game and open its list of files if not already opened.

- If all games (or their specific duplicated files) are unchecked which contribute to a given game of interest as being flagged as having duplicates, should the duplicates pill be hidden on the remaining checked game? If two or more games are checked and share duplicates, it makes sense to keep the pill label shown on both. I think these duplicate labels should reflect the state of if duplicate data would be backed up instead of if games with duplicate rules exist regardless of their checked state.

- There seems to be issues with games displaying the duplicates pill label even though its list of files shows "Duplicated" next to some items. Also, _which_ games show the duplicates pill next to their title changes depending on the order in which the games were scanned.

ludusavi-v0.11.0-post.16+b91a9d8-win64

**Comment by mtkennerly** [comment]
1. Good idea. This could just apply a filter to the main list (like the search function does), rather than having a separate list.
2. That makes sense. I think I'd rather just fade the badge than hide  it entirely, though.
3. Could you give me a specific example of how to reproduce these issues?

**Comment by redactedscribe** [comment]
https://user-images.githubusercontent.com/25013746/187464758-e81fcdc8-fc2f-48a4-8fdc-87c2dbd928ad.mp4

I'm not sure what's going on but, first time around I go from top to bottom for the three Trackmania titles that contain duplicates and only the first two show the Duplicates label. Next launch I go from the third to the first game and now the last two show the Duplicates label.

ludusavi-v0.11.0-post.21+4280cd6-win64

**Comment by mtkennerly** [comment]
Thanks, that should be fixed now.

**Comment by mtkennerly** [comment]
Preview:

> https://user-images.githubusercontent.com/4934192/229978290-fbcbe797-0cc3-4e09-ba21-976e2e55d131.mp4
