### ISSUE TITLE
Chinese didt show correctly

### ISSUE THREAD

**Issue by JohnnyWoong** [mtkennerly/ludusavi#118]
If custom game name or filepath contain chinese, it will show as 'empty block'
![image](https://user-images.githubusercontent.com/5661094/187082665-8abfce4e-ca25-4846-9bc0-74167e4d6595.png)

**Comment by mtkennerly** [comment]
Unfortunately, this is a known limitation of the [graphics library](https://github.com/iced-rs/iced) that Ludusavi uses. Please keep an eye on #9 for progress on this.

The files should still be backed up correctly, even though they're not displayed in Ludusavi itself.
