### ISSUE TITLE
Search filters

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#120]
An idea to be able to further filter your games list, useful for those with hundreds of entries:

- The current Search button could reveal a `Unique|Duplicates` drop-down box (DDB) to filter only games marked as having duplicates or not. The DDB would then have a checkbox beside it to toggle the DDB's active state (disable its UI and its filtering).
- Similarly, a `Complete|Partial` DDB for games with only some their items checked (i.e. when you see "5 of 26" next to a game title), or those that have all of their items checked.
- Similarly, a `Selected|Unselected` DDB for games which are currently unselected and won't be backed up, or those that will be.

My thinking is that these options would be additional filters on top of any supplied search term and able to be combined for specific types of results, for example: "Call of Duty" + `[x] Duplicates` + `[x] Partial` + `[x] Selected`. This example is an extreme case which actually would be more likely to be used _without_ the search term, i.e.: find any games which have duplicates, which have only some of their items selected, and which the games themselves are selected to be backed up.

With such a design, an `All` button would be nice to have to bypass all the DDB filters (to avoid the need to uncheck the checkboxes of each filter) to only see what the search term by itself returns, i.e. turn the feature off altogether.

How regularly would one need these filters, I'm not sure, but I could see them being useful to help find those two games out of your 200 that are unchecked for example. Over-engineered or practical? Thanks!

**Comment by mtkennerly** [comment]
Here's a preview from the upcoming release:

> https://user-images.githubusercontent.com/4934192/229463214-9a93086d-112b-4eb2-bae0-0a7c5869a4e8.mp4

**Comment by redactedscribe** [comment]
Looks great! Thanks @mtkennerly.
