### ISSUE TITLE
It does not work on KDE Neon

### ISSUE THREAD

**Issue by dtantono** [mtkennerly/ludusavi#125]
Hi
I tried to install it with cargo install ludusavi. But it does not worked.

![image](https://user-images.githubusercontent.com/29157187/188338045-939e65bd-4e8b-4d44-845b-e89426f8866b.png)

**Comment by mtkennerly** [comment]
Hi! As the error message says, you're using Rust 1.57.0, but you need Rust 1.59 or higher. Ludusavi generally requires a pretty new version of Rust.
