### ISSUE TITLE
On launch, Ludusavi console window opens with main window

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#131]
### Ludusavi version

v0.13.0

### Operating system

Windows

### Installation method

Scoop

### Description

Each time Ludusavi is launched, a console window now opens along with it. This did not happen in previous versions.

**Comment by mtkennerly** [comment]
Thanks, I didn't catch this since I normally run via Cargo.

This makes no sense to me (yet), but this is somehow being caused by the logging code. When I remove the logging setup, the console stops appearing. I'll try to figure out why.

**Comment by mtkennerly** [comment]
I found a workaround. I still don't understand how the logging interfered, but I fixed it by initializing the logging a little bit later. I'll release the fix ASAP.

**Comment by redactedscribe** [comment]
Thanks for the quick fix! Hopefully you can understand the root cause of the issue later.

**Comment by redactedscribe** [comment]
@mtkennerly Judging by my previous comment, I experienced this as being fixed at some point, but Ludusavi has still been launching a console window along side the main window for probably many versions now.

The problem is that I have my Windows Terminal configured to not automatically close console windows which exit, thus Ludusavi's console window remains on my screen despite it only showing momentarily (`[process exited with code 0 (0x00000000)]`). I admit that I could configure my Windows Terminal to not do so and avoid this issue, but I find the feature convenient in other cases.

Is it not possible to launch Ludusavi without also having a momentary console window being creating? Maybe the console window can be created in a hidden state?

**Comment by redactedscribe** [comment]
@mtkennerly Turns out there was a few options available for this Windows Terminal feature. Setting it to the second last as seen below essentially overcomes this issue. Only non-zero exits now remain on-screen:

![windows_terminal_2023-06-26_16-41-19](https://github.com/mtkennerly/ludusavi/assets/25013746/59622086-be62-4c28-b8a5-cc1f2045c360)

**Comment by mtkennerly** [comment]
> I guess it still would be ideal if no console window was even created momentarily on Ludusavi's launch...

I agree. I tried to do that originally, and I think I ran into some problem with it, but it's been long enough that I don't remember exactly what. I'll try it again and double check. Having a single exe that switches between CLI/GUI is honestly just way trickier than it should be 🙃

**Comment by mtkennerly** [comment]
I just tried setting `#![windows_subsystem = "windows"]` (which makes the program launch without a console) and then conditionally reattaching to the parent console (`AttachConsole(ATTACH_PARENT_PROCESS)` via winapi). It works, but looks messed up in Command Prompt and PowerShell:

* Logs are printed on a new console prompt (the "attached 2" line is printed right after re-attaching)
* After the command is done, there's no new prompt, and typing bleeds into the output

If anyone can figure out a way to make this work, I'd be happy to integrate it, but I'm not sure what else to try.

> https://github.com/mtkennerly/ludusavi/assets/4934192/3893a13e-514b-4bb6-8640-f4ec2077e4f4
