### ISSUE TITLE
ludusavi backup requires to specify --merge although it is set in config.yaml

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#133]
### Ludusavi version

v0.13.1

### Operating system

Linux

### Installation method

Other

### Description

* Configured backups to merge in config.yaml
* run backup on CLI, getting error message

```shell
$ ludusavi --version
ludusavi 0.13.1
$ ludusavi  backup Factorio
The backup target already exists ( /home/MYUSER/Games/00-savegames/0-ludusavi-backup ). Either choose a different --path or delete it with --force.
$ ludusavi  backup --merge Factorio
Factorio [187.88 MiB]:
  - /home/MYUSER/Games/Factorio/game/config/config.ini
  - /home/MYUSER/Games/Factorio/game/saves/_autosave1.zip
  - /home/MYUSER/Games/Factorio/game/saves/_autosave2.zip
[...]

Overall:
  Games: 1
  Size: 187.88 MiB
  Location: /home/MYUSER/Games/00-savegames/0-ludusavi-backup

```

Ludusavi configuration:

![image](https://user-images.githubusercontent.com/7710530/193204804-3eab3f17-c715-4bfd-9619-7a31b4f36fe2.png)

**Comment by mtkennerly** [comment]
Yeah, this isn't a good experience. I think it should prompt for confirmation, like it does in the GUI, unless you use `--force` to bypass that. The phrasing of the error is a carryover from before the merge option was available.
