### ISSUE TITLE
[Feature Request] Compression level

### ISSUE THREAD

**Issue by t3dium** [mtkennerly/ludusavi#135]
### What's your idea?

Auto compressing ludusavi saves would be useful to save storage, ideally via LZMA or ARC as they're the most efficient.

**Comment by mtkennerly** [comment]
Hi! Compression is available for zip backups (backup mode -> gear icon). The default is Deflate, but you can also choose the more efficient Bzip2 or Zstd options.

I think Zstd is on par with LZMA. However, Ludusavi doesn't currently have options to tweak the compression level, so you can't get the full value out of it. I'll add an option for that.

**Comment by t3dium** [comment]
perfect thanks
