### ISSUE TITLE
Sometimes two previews are needed to display a game in the games list

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#138]
### Ludusavi version

v0.13.1

### Operating system

Windows

### Installation method

Scoop

### Description

In the Ludusavi issue that I created last, you mentioned that you had forced the GitHub actions bot to run an update for me. So I launched Ludusavi, and hit Preview. Once the list loaded, the new game was not present in the list. Upon hitting Preview a second time, the new game was now visible.

I think I've noticed this happen before where two previews are needed before the list is up-to-date, and not only regarding new PCGW data, but even local data such as when a save file has been created when none existed before that for a game. I could be wrong about that, but certainly what I described in the paragraph above just happened.

**Comment by mtkennerly** [comment]
How quickly did you start the preview after opening the program? The manifest update happens asynchronously in the background. If you started the scan very quickly, it may not have finished updating yet.

**Comment by redactedscribe** [comment]
Immediately, so that's probably why. Although, I thought I had experienced something this when a game currently had no data, I launched the game for the first time, re-previewed, and nothing showed until a second time -- but I could be mistaken. This issue can probably be closed then.

**Comment by redactedscribe** [comment]
Just a thought: Perhaps Ludusavi could notify that the manifest has just been updated? I guess this would make sense if the feature you suggested of being able to force a new manifest download prior to the 24-hour auto-update cycle was implemented. We would want to know that the update succeeded, and perhaps this should also be communicated after Ludusavi launches (assuming an update happened).

Should it really be called the manifest to the user? Maybe something more like the "games database"? Just thinking people on average wouldn't know what a manifest is.

**Comment by mtkennerly** [comment]
> Although, I thought I had experienced something this when a game currently had no data, I launched the game for the first time, re-previewed, and nothing showed until a second time -- but I could be mistaken.

Hmm, I'm not able to reproduce this. I did a full preview, created `C:/ALIENS.CFG`, did another preview, and got a new entry for "Aliens: A Comic Book Adventure". If you're able to find a game/setup where this happens, please let me know.

> Just a thought: Perhaps Ludusavi could notify that the manifest has just been updated?

Yeah, I can try to add some feedback for this.

> Should it really be called the manifest to the user? Maybe something more like the "games database"? Just thinking people on average wouldn't know what a manifest is.

They probably wouldn't normally, but I think (hope) it's okay since the README talks about the manifest and what it's for.

**Comment by redactedscribe** [comment]
> If you're able to find a game/setup where this happens, please let me know.

I'll keep a lookout for this. I can reopen the issue if it occurs again so feel free to close it for now.
