### ISSUE TITLE
Re-preview a game from the Custom Games tab

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#139]
### What's your idea?

Let's assume only one path is present to detect a game's config/data files.

If one creates a custom game entry via Customize for such a game and then edits the path to something incorrect, pressing Preview for that particular game on the Backup Mode page will cause it to disappear from the list due to there being no path matches. If we correct the custom path and want to preview again, we cannot because the game is no longer in the list to click. We must first do a full preview to see our custom path changes.

If we had a preview buttons on the entries found on the Custom Games page too, Ludusavi could append the game to the Backup Mode list if it happens to now be correct. Better than just being appended would be being correctly sorted in the list, and for Ludusavi to take us to the entry when clicking Preview via a Custom Games entry.

Ludusavi 0.13.1

**Comment by mtkennerly** [comment]
Makes sense to me :+1: Done:

> https://user-images.githubusercontent.com/4934192/196571659-28bfdb52-693b-4e44-a6af-09a0f6429acb.mp4
