### ISSUE TITLE
Speed up compilation times for development

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#140]
### What's your idea?

I recently read about the Rust game engine [Bevy](https://bevyengine.org/).  In the [setup section](https://bevyengine.org/learn/book/getting-started/setup/#compile-with-performance-optimizations) they advise to disable optimizations for the project which uses Bevy while keeping it enabled for all dependencies.

I tried that and it actually reduces ludusavi compile times for a debug release on my machine.  The patch would look like this:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index f9f7b95..e97fd1b 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -57,5 +57,16 @@ winres = "0.1.12"
 maplit = "1.0.2"
 pretty_assertions = "1.2.1"
 
+## 2022-10-13 SL try some optimization based on Cargo.toml recommendations for bevy
+## https://bevyengine.org/learn/book/getting-started/setup/
+
+# [profile.dev]
+# opt-level = 3
+
+# Enable a small amount of optimization in debug mode
 [profile.dev]
+opt-level = 1
+
+# Enable high optimizations for dependencies, but not for our code:
+[profile.dev.package."*"]
 opt-level = 3
```

**Comment by mtkennerly** [comment]
Thanks! This is a great suggestion. On my system, it cut the incremental debug build time from 14 seconds to 4 seconds, without any noticeable impact on the scanning speed. I've updated master with this change.
