### ISSUE TITLE
Support Flatpak installations of native Linux games

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#143]
### What's your idea?

Split off from #142. Some Linux games are available via Flatpak, without any other store/launcher. This would require mapping each game to its Flatpak ID, which isn't currently listed on PCGW.

**Comment by LeSnake04** [comment]
I will defiantly try to get ths ids to PCGW. 

But I think for the forseable futere the api route would be more sucessful: https://github.com/mtkennerly/ludusavi/issues/142#issuecomment-1285260054

**Comment by mtkennerly** [comment]
Re: https://github.com/mtkennerly/ludusavi/issues/142#issuecomment-1288228001 (@LeSnake04)

> Maybe it makes sense to implement the system for getting flatpaks defined by the manifest and just manually define the heroic and steam id for now.

Yeah, I can do that. If there are some specific games that are relevant for you, we could add them first to get some sample data and do some testing. Then when we have a good way to bulk add the remaining IDs and tie them to specific PCGW game names, it'll "just work".

> For that it makes sense to add a root for the flatpak var. (its possible to use a .var at a different location, so users should be able to set it manually).

Good point. I'm curious, would the "home folder" root cover this? For example, let's say you set up a home root to "/tmp/home", which then implied that Ludusavi should check "/tmp/home/.var/app/{id}". That might not be intuitive, so I'm not opposed to adding a separate config, but I'm just wondering how much freedom you have to move `.var` around.

**Comment by LeSnake04** [comment]
The home path way would work. Flatpak only supports portable repositories for now and no portable data/config

I will search some games and their corusponding ids.
For steam and heroic we should set the id to `*` to indicate search for all

I think a good way to help users manually bridging is to add a new type of custom entries for flatpaks where to user provides a flatpak id and a list of PCGW ids (or click an toggle to enable scanning for all games.)

**Comment by LeSnake04** [comment]
Bad news 
![](https://media.discordapp.net/attachments/497830372281942027/1034095877226233926/4f6a2da1-7d62-4422-8cca-075f068f75c7.png)

**Comment by LeSnake04** [comment]
Now we eighter have to push changes to each flatpak repo, which will take ages, or make a own system. 

I can make a simple gui for adding entries

**Comment by mtkennerly** [comment]
> I think a good way to help users manually bridging the gap is to add a new type of custom entries for flatpaks where the user provides a flatpak id and a list of PCGW ids (or click an toggle to enable scanning for all games.)
I had some situations in the past where I missed this feature.

Can you explain how you'd expect an "all games" option to work? Would you want a single "custom game" that actually backs up the data for every Flatpak game you have installed at once? If so, that doesn't really fit how Ludusavi organizes saves by game, but you could make a custom entry using globs to back up `~/.var/app/*/data` and `~/.var/app/*/config`.

> Bad news

Hmm, I'm not sure why they seem opposed to providing context. Oh well.

I managed to find a discussion on their server from 2021 where someone asked about adding the Snap store, starting here: https://discord.com/channels/165183350913499136/327384491343478784/828417676484935700.

It sounds like the main concern was that uploads aren't guaranteed to be official:

https://discord.com/channels/165183350913499136/327384491343478784/828450116980572171
> Aemony — 04/05/2021
>> This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.
>
> I hate "stores" or platforms that actually allows random strangers online from publishing an application or game on it

https://discord.com/channels/165183350913499136/327384491343478784/828452599128129566
> Aemony — 04/05/2021
> Mhm, I don't doubt there's official ones -- I did see that they had "verified account" tags, but random end users would not really care about that sort of thing when adding these sorts of stuff to PCGW, and eventually I fully expect that most of the listed snaps we'd list as if they were official releases would in fact be unaffiliated unofficial repackages which neither has official support nor endorsement from the actual devs or pubs
> Btw, sorry if I sound frustrated -- I've had a frustrating last few hours and these sorts of random platforms that allows third-party re-releases where end-users must put their trust into a random stranger online unaffiliated with the original product is one of my pet peeves, so my frustration from earlier (and entirely different unrelated things) sorta comes across here

I think the concern itself is valid, anyway. Does Flathub have some way of filtering/valiating official releases? I wouldn't want to include unofficial ones in the manifest either, to avoid supporting anything illegal (or at least seeming to, even if it weren't intentional).

**Comment by mtkennerly** [comment]
You could only ever have Ludusavi do that for one game, though, or else you'd get duplicate backups. For example:

* Manifest contains three Flatpak IDs: `com.game1`, `com.game2`, `com.game3`
* Ludusavi checks for any saves of Game 1. It backs up all known Flatpak IDs (game1, game2, game3)
* Ludusavi checks for any saves of Game 2. It backs up all known Flatpak IDs (game1, game2, game3)
* Ludusavi checks for any saves of Game 3. It backs up all known Flatpak IDs (game1, game2, game3)

You would then have 3 copies of each game's Flatpak save data.

**Comment by LeSnake04** [comment]
each game has it own home dir, so the game save from widelands will not be found in the supertux flatpak home dir

**Comment by LeSnake04** [comment]
The situation regarding official downloads has changed! 

Flatpaks can be verifed by the developer now. (@mtkennerly you might want to log into flathub with your github account to verify the ludusavi flatpak)

the verification status can be seen in the API output. To list the data of all flatpaks read the data from `https://flathub.org/api/v2/search/: `. Then we can just filter out all games and check their verified status.

**Comment by mtkennerly** [comment]
@LeSnake04 Thanks for the heads-up! I logged in and it says verified in the developer settings, so I assume the badge will show up soon.

As a stopgap (until the data is automatically included), I can at least add support for a new field in the manifest, which could then be populated by a custom game entry or by a secondary manifest (https://github.com/mtkennerly/ludusavi/issues/95 , once it's implemented). I'll try to look into that for the next release.

**Comment by mtkennerly** [comment]
I've added the support for this [in Ludusavi](https://github.com/mtkennerly/ludusavi/commit/53f3b04a62eb8a8865ddf6fdbd98567465be39b4) and in [the manifest schema](https://github.com/mtkennerly/ludusavi-manifest/commit/841e7ce581acb99a0478b864abc7c72dc56e7d88).

The missing piece is a way to automatically add Flatpak IDs to the manifest. `https://flathub.org/api/v2/search/:` is very promising, but we'd need an approach that can avoid false positives like linking https://flathub.org/apps/com.hunterwittenborn.Celeste with https://www.pcgamingwiki.com/wiki/Celeste . In that specific case, we could ignore it because it's not verified or because it's not in the game category, but it's just an example of how names can be misleading.

@LeSnake04 For now, if there are some specific games you'd like to see added, you could submit a PR that modifies [manifest-override.yaml](https://github.com/mtkennerly/ludusavi-manifest/blob/master/data/manifest-override.yaml). If the game is already in the manifest and just missing the Flatpak ID, you could add an entry like this:

```yaml
Example Game:
  id:
    flatpak: com.example.Game
```

If it's not in the manifest at all, then ideally we would create a PCGW article and then add the Flatpak ID as above. You can also add a whole game entry from scratch in manifest-override.yaml, but PCGW is better if at all possible.
