### ISSUE TITLE
Heroic and GRIP: Combat Racing: game not found due to name mismatch

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#148]
### Ludusavi version

v0.13.1

### Operating system

Linux (Steam Deck)

### Installation method

Standalone

### Description

Related to #94

- The game is listed as "GRIP: Combat Racing" in the ludusavi `manifest.yaml`.
- heroic `.config/heroic/gog_store/library.json` names it as `"title": "GRIP"`
- during `heroic::detect_gog_games` it is properly found and memorized as "GRIP"
- `ludusavi backup` does not recognize it since it compares the name from the manifest with the name from the library.json which do not match

I expect quite some games to have this issue, for example "X-Morph: Defense Complete Edition" (`gog_store/library.json`) versus "X-Morph: Defense" (`manifest.yaml`) seems problematic as well.

**Comment by sluedecke** [comment]
Another option might be to get data from [GOG DB](https://www.gogdb.org).  They provide access to their complete data ([moreinfo](https://www.gogdb.org/moreinfo)) here: https://www.gogdb.org/backups_v3/

With some work one can build aliases in the manifest from that:

- for GRIP their [`product.json`](https://www.gogdb.org/data/products/1342466874/product.json) includes the game id (aka `appName` in `HEROIC_CONFIG/gog_store/library.json`): 1342466874
- this id can be used in https://pcgamingwiki.com/api/gog.php?page=1342466874 to get to the PCGaming Wiki page 
- and from there one can retrieve the proper game title also found in the  ludusavi manifest.

**Comment by sluedecke** [comment]
X-Morph is detected by the heroic code as "X-Morph: Defense Complete Edition" but normalize reduces it to "x morph".  Thus no backup.

**Comment by mtkennerly** [comment]
I'm open to the GOG DB option or even a combination of both. Just need to play around with it and see how it goes.

Since GOG DB names might conflict with PCGW article titles, I would probably store it like this and just build a mapping of alias -> official on the client side:

```yaml
GRIP: Combat Racing:
  aliases:
    - Grip
```

**Comment by sluedecke** [comment]
Yes, thats what I had in mind as well.  In `heroic::memorize_game` a check could work like this:

1. title matches?
2. alias matches?
3. normalized matches?
4. Log an error

**Comment by sluedecke** [comment]
In fact it can be queried from the pcg wiki cargo API:

```
{{#cargo_query:
tables=Infobox_game
|fields=Infobox_game.GOGcom_ID, Infobox_game._pageName
|where=GOGcom_ID holds "1342466874"
}}

```

Result:
```json
[
    {
        "GOGcom ID": [
            1342466874,
            1926778718
        ],
        "_pageName": "GRIP: Combat Racing"
    }
]
```

**Comment by sluedecke** [comment]
Or to put it as HTML request: `https://www.pcgamingwiki.com/w/api.php?action=cargoquery&tables=Infobox_game&fields=Infobox_game._pageName=Page,Infobox_game.GOGcom_ID&where=Infobox_game.GOGcom_ID%20holds%20%221342466874%22&format=json`

results in

```json
{"cargoquery":[{"title":{"Page":"GRIP: Combat Racing","GOGcom ID":"1342466874,1926778718"}}]}
```

1926778718 is the GOG product ID for the GRIP soundtrack

**Comment by mtkennerly** [comment]
Completed in #152.

**Comment by sluedecke** [comment]
PS: detects everything on the deck now, too!  Including X-Morph: Defense.
