### ISSUE TITLE
Specify ludusavi configuration directory on the command line

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#151]
### What's your idea?

I sometimes play around with different settings in the config.yaml and manifest.yaml.  Also on steam deck, when used within a wrapper script, it (correctly!) uses XDG_CONFIG_HOME which is not always what I want it to use.

Can we have a `--config DIR` option telling ludusavi to let use `DIR` as it's configuration folder?

**Comment by mtkennerly** [comment]
Sure, I think that makes sense to add. For now, you can work around it with something like:

```
XDG_CONFIG_HOME=/tmp ludusavi backup --preview
```

**Comment by mtkennerly** [comment]
Completed in #153.
