### ISSUE TITLE
Custom Steam game saves are not detected

### ISSUE THREAD

**Issue by minimeee** [mtkennerly/ludusavi#154]
### Ludusavi version

v0.14.0

### Operating system

Linux (Steam Deck)

### Installation method

Flatpak

### Description

I've installed some Steam games and two custom games (one from GOG and one from Amazon) on my Steam Deck. I'm running both custom games via Steam, so they have their own prefix folder below `/home/deck/.local/share/Steam/steamapps/compatdata`:

```
(deck@steamdeck compatdata)$ pwd
/home/deck/.local/share/Steam/steamapps/compatdata
(deck@steamdeck compatdata)$ ll
total 48K
drwxr-xr-x 3 deck deck 4.0K Aug 30 16:26 0
drwxr-xr-x 3 deck deck 4.0K Oct  9 10:05 102840
drwxr-xr-x 3 deck deck 4.0K Aug 29 12:16 1493710
drwxr-xr-x 3 deck deck 4.0K Aug 28 20:59 1887720
drwxr-xr-x 2 deck deck 4.0K Oct 20 22:21 203160
drwxr-xr-x 3 deck deck 4.0K Oct 21 10:38 3696693751
drwxr-xr-x 3 deck deck 4.0K Oct 29 14:43 3856528840
drwxr-xr-x 3 deck deck 4.0K Oct  7 13:31 44350
drwxr-xr-x 3 deck deck 4.0K Oct 20 20:48 462770
drwxr-xr-x 3 deck deck 4.0K Aug 28 20:59 464060
drwxr-xr-x 3 deck deck 4.0K Oct  7 13:37 520720
drwxr-xr-x 4 deck deck 4.0K Aug 30 11:28 979690
```
The two custom games are `3696693751` ("Shadow of Mordor", GOG) and `3856528840` ("Broforce", Amazon). 

Now, the problem is that the saves of both custom games are not detected by Ludusavi, although they are there alongside the "native" Steam games:

```
(deck@steamdeck compatdata)$ find 3696693751/ -name "GameData.sav"
3696693751/pfx/drive_c/users/steamuser/Documents/WB Games/Shadow of Mordor/Saves/GameData.sav
```
However, it works if I add `/home/deck/.local/share/Steam/steamapps/compatdata/3696693751/pfx/` as a new root of type `Wine prefix`.

At first I thought that Ludusavi may need the installation files of a game to identify it (which are not in the "right place" for custom games), but it also detects Steam "native" games that I've uninstalled long time ago...

**Comment by mtkennerly** [comment]
Hi! This is actually a new feature coming in the next release (originally discussed in #130). The main issue here is mapping between a "non-Steam game" ID like 3696693751 and a regular Steam ID like 241930 (Shadow of Mordor).

**Comment by minimeee** [comment]
Oh, very nice! And thanks for the quick response! I've actually been looking at the open issue list before posting but, apparently you've closed that one only 3 days ago...
