### ISSUE TITLE
Issue closed

### ISSUE THREAD

**Issue by dlee6036** [mtkennerly/ludusavi#155]
Sorry! I spoke too soon.

**Comment by mtkennerly** [comment]
Hi! Would you be willing to share a few files so I can try to debug this?

First, to generate a log file, please run this command (but replace `GAME NAME HERE` with one of your non-Steam games):

```
flatpak run --env=RUST_LOG=ludusavi=trace com.github.mtkennerly.ludusavi backup --preview "GAME NAME HERE"
```

Then please post these files:

* Your Ludusavi `config.yaml`. This should be in `~/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi`
* Any `.log` files in the same folder as `config.yaml`
* Your Steam `shortcuts.vdf`. This should be in `/home/deck/.steam/steam/userdata/<id>/config/shortcuts.vdf`
