### ISSUE TITLE
Allow importing backups from other tools

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#158]
### What's your idea?

Allowing imports from other tools (mainly GameSave Manager) would make it easier for people to switch to Ludusavi.

**Comment by Triplesweet** [comment]
Just an opinion, but can't you just restore all saves you have on those apps, then back them up in ludusavi? It shouldn't take so much unless the library is huge, even then I don't believe it is worth spending so much time on it, again just an opinion 

In order to make this process easier, you can instead be sure finding games, finding saves, backing them up, have the least amount of problems, because having an import from other apps will probably have their own problems that might needs fixing and I believe it is not that hard to do in the way I said, 

Wish you the best tho,  ✧⁠◝⁠(⁠⁰⁠▿⁠⁰⁠)⁠◜⁠✧

**Comment by mtkennerly** [comment]
Ideally, yeah, I agree that's the best option. Unfortunately, it doesn't seem like GameSave Manager can restore saves if the original folder doesn't exist (or at least it didn't seem to work when I tested it), so it's hard to switch if you have a lot of backups for games that aren't installed anymore.

**Comment by Triplesweet** [comment]
Tou mean the folder that the save should be? If yes I can give it a try now? I have the app right now wish some backups

**Comment by mtkennerly** [comment]
Hmm, this is what I just tried:

* In `C:\Program Files (x86)\Steam\steamapps\common`, rename the subfolder `1000 Amps` to `1000 Amps - temp`
* Open GSM -> "open archive(s)" -> choose gsba file for 1000 Amps
* <img width="790" alt="image" src="https://user-images.githubusercontent.com/4934192/203841247-ecc54019-d819-475c-ba80-dd5e8d7f04c6.png">

But if I put the folder name back to the original, then it works:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/4934192/203841317-c9904851-953d-4ead-b631-e3ba37f25e33.png">

Maybe it's different for Steam-based paths and OS-level paths (like LocalLow)?

**Comment by Triplesweet** [comment]
The app has problems with steam folder all around. I backed up userdata folder uninstalled steam restored the files isays no error but there is not steam folder (⁠╯⁠°⁠□⁠°⁠）⁠╯⁠︵⁠ ⁠┻⁠━⁠┻

**Comment by Triplesweet** [comment]
So if you log in to the same acc it works if not good luck, NGL you will have to spend a lot of time to have a proper import function, I still say it's not worth it

**Comment by skafiend** [comment]
Hi. It's insane. The app works fine, but the playnite plugin is completely broken. Whatever I do I just get a bunch of errors. 
![Screenshot_1](https://github.com/mtkennerly/ludusavi/assets/71149098/df2c9c6d-4a2c-4d0f-bc82-fdad3f947c1d)
![Screenshot_2](https://github.com/mtkennerly/ludusavi/assets/71149098/e918c858-d21e-4a72-b9cb-b607c4b05b35)
![Screenshot_3](https://github.com/mtkennerly/ludusavi/assets/71149098/93f68977-5971-47ed-b2a1-744e0f297dd1)
![Screenshot_4](https://github.com/mtkennerly/ludusavi/assets/71149098/6b13aa61-bf1c-4d4a-a61c-be8a9872549c)

**Comment by mtkennerly** [comment]
@skafiend Could you send me a copy of `extensions.log` from Playnite?

Also, if you open Playnite and go to: (Playnite icon) -> Add-ons... -> Extension settings -> Generic -> Ludusavi, what setting do you have for `Name or full path of the Ludusavi executable`?

**Comment by skafiend** [comment]
![image](https://github.com/mtkennerly/ludusavi/assets/71149098/8125ba35-3f85-4d18-9351-1df71f2fe598)
[extensions.log](https://github.com/mtkennerly/ludusavi/files/14612556/extensions.log)
I noticed one more thing. If I'm launching the app from the menu it works 
![image](https://github.com/mtkennerly/ludusavi/assets/71149098/c10c2b96-cd1b-4707-9902-4efda6b5b483)
, but when I press Backup saves for all games, I get this 
![image](https://github.com/mtkennerly/ludusavi/assets/71149098/da74e70e-1991-4370-9fb1-a0f05ffc917d)
![image](https://github.com/mtkennerly/ludusavi/assets/71149098/b375cb3f-3995-4495-93cc-bc882715baac)
![image](https://github.com/mtkennerly/ludusavi/assets/71149098/82f20909-1877-4576-bf2d-9c05d8fa6baf)

**Comment by skafiend** [comment]
nvm. I figured it out. I've tried saving files to another location and it worked. must be something wrong with folder permissions. thank you for your response :)

**Comment by skafiend** [comment]
@mtkennerly Finally, I figured out what happened, and extensions.log helped a little. I'm using ludusavi.exe in portable mode and when I run it directly, it uses config files from the folder. my guess is the extension used settings from %appdata%. I cleaned up this folder and now everything works fine. thank you for your response, those mistakes drove me crazy :D

**Comment by mtkennerly** [comment]
I found that someone else has actually made a script to convert from GSM backups: https://github.com/jose-l-martins/GSM-to-Ludusavi-converter

I've added a link to it in the README's community section. Since that was the main use case for this feature, I'll go ahead and close this.
