### ISSUE TITLE
Suggestion: Export in human-parsable format

### ISSUE THREAD

**Issue by wtjones** [mtkennerly/ludusavi#16]
It would be great if each entry was maybe saved in a zipped structure with original file names. Potential reasons for this:
- I want to restore individual files
- I want to restore without the app (maybe I can't run it for some reason?)
- I switch operating systems and need to hand-pick the files to restore (This is a real-world scenario for me when I switched from Windows -> Linux and had to examine/extract the GameSaveManager archives.
- I just want to see what is there. :shrug:

**Comment by mtkennerly** [comment]
I'd like to do this (my original idea was just a normal folder that mirrors your real system's organization), but there are some problems that I wasn't sure how best to handle:

* How do you represent drive names in a consistent, cross-platform way?
* How do you represent folders for games like .hack//G.U. or \*\*\* ([yes, that's a real title](https://www.pcgamingwiki.com/wiki/***))?

Something like this might work:

```
~/ludusavi-backup/
  mapping.yaml
  .hack{slash}{slash}G.U./
    registry.yaml
    drive-1/
      Users/
        SoAndSo/
          file.txt
```

where mapping.yaml could translate `drive-N` into a Windows drive letter or `/` as appropriate, and registry.yaml contains Windows registry entries (if any). Substitutions like `.hack{slash}{slash}G.U.` or `{star}{star}{star}` should be reversible as long as no one decides to be funny and actually name their game that - probably a very low risk, but I can't help but wonder if it'll happen someday.

I'm definitely open to suggestions about how to implement this, though. What do you think about the above option?

**Comment by wtjones** [comment]
Rather than escape them in the folder structure you could use the single quote protection in yaml and have an ordered list of folders in the mapping that relate to flattened folders named 1..n. Only the name of the archive folder (or zip) would have to be encoded for cross platform.

```
~/ludusavi-backup/
  .hack{slash}{slash}G.U-2020-7-10/
    1/
       save.dat
    2/
      config.dat
    mapping.yml
```
in mapping.yml (pardon my yml)
```
folders:
 folder-1
   path: <home>Appdata/.hack//.Gui**
 folder-2
   path: <home>Windows/temp/foo
registryItems:
  HKEY/FOO/....
 ```
Basically this would use the original manifest to map the folders. Some similarities with GSM but with more cross-plat considerations.

**Comment by mtkennerly** [comment]
Referencing the manifest placeholders would be interesting, but also a lot more complicated for users (more so than the current base 64 approach, I think). Just take a look at all the [special handling for Proton paths](https://github.com/mtkennerly/ludusavi/blob/03d45aa5533184805d58477567d1c17b0c6b2358/src/prelude.rs#L152) - not fun.

As far as using a flatter style like GSM does, wouldn't that still make it hard (or at least a bit inconvenient) to restore without going through Ludusavi? Although the number might be more human-friendly than base 64, it's probably harder to script checking a YAML file than doing base 64 conversion if you need/want to restore without Ludusavi:

```bash
$ echo Q2VsZXN0ZQ== | base64 --decode
Celeste

$ for folder in `find ~/ludusavi-backup -maxdepth 1 -mindepth 1 -type d`; do basename ${folder}Cg== | base64 --decode; done
1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)
1001 Spikes
Chantelise: A Tale of Two Sisters
Chime
Celeste
...
```

**Comment by wtjones** [comment]
In my cross-OS scenario, I was simply extracting the files to the equivalent location in Linux. The GSM path wasn't useful. I'll admit this is probably not a common occurrence

The title of this item was poorly chosen, as it is a 'how', not a 'why'. 

I'm thinking I'll 1) attempt to break down the use-cases 2) close this item 3) move useful ones to separate topics

- Ability to query the backed-up files
  - Some backup tools have something like this (Mozy if I remember)
  - Provides a piece-of-mind
  - Can be performed via shell script as you mentioned
  - Could also be provided by a 'view backup logs' link maybe as a first step
- Ability to restore a title to a specific folder
  - The original root may no longer available (OS wipe + repartition)
  - The OS performing the restore may be different

**Comment by mtkennerly** [comment]
Hey, @wtjones, that second use case (restoring to a different location) is now covered in v0.4.0 with redirects. You can see a quick demo here: https://github.com/mtkennerly/ludusavi/issues/7#issuecomment-661623604 . Let me know what you think!

For the first use case, since you mentioned the idea of a "backup log", do you think it would provide more peace of mind if the backup folder had a file like this?

```
MTAwMCBBbXBz:
  name: 1000 Amps
  files:
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTE=: D:/Steam/steamapps/common/1000 Amps/save1
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTI=: D:/Steam/steamapps/common/1000 Amps/save2
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTM=: D:/Steam/steamapps/common/1000 Amps/save3
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2V0dGluZ3M=: D:/Steam/steamapps/common/1000 Amps/settings
```

**Comment by wtjones** [comment]
That's even more fine-grained that I envisioned, so yea I think that works great.

The log looks good. It could be useful for troubleshooting as well.
