### ISSUE TITLE
Ignore casing when matching titles via name

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#161]
### Ludusavi version

v0.15.0

### Operating system

Windows

### Installation method

Standalone

### Description

I have the GOG release of [CHAOS;HEAD NOAH](https://www.gog.com/game/chaos_head_noah). The issue is that the PCGW entry is cased as [Chaos;Head NoAH](https://www.pcgamingwiki.com/wiki/Chaos%3BHead_NoAH), which causes Ludusavi to not recognize it when trying to back up. I was wondering if it could be possible to ignore the casing to match the game

![image](https://user-images.githubusercontent.com/1389286/202978376-2985b983-274f-4073-b5d1-bf09e2ee0395.png)

![image](https://user-images.githubusercontent.com/1389286/202978800-aa05de91-8a77-4309-857b-4cdd56d92b0d.png)

### Logs

Ludusavi Playnite Logs

```
21-11 00:12:41.880|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: find --api --path "C:\Users\Brandon\MEGAsync\OneDrive\Backups\saves\PC" --backup -- "CHAOS;HEAD NOAH"
21-11 00:12:43.691|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 1 and valid JSON content
```

**Comment by mtkennerly** [comment]
You can do this with the normalization option, which is also available in the Playnite extension now:

![image](https://user-images.githubusercontent.com/4934192/202979556-c6c3b193-c170-4505-bbf9-3457eb7c3564.png)

```
        --normalized
            Look up game by an approximation of the title. Ignores
            capitalization, "edition" suffixes, year suffixes, and some special
            symbols. This may find multiple games for a single input
```

The Playnite plugin will pick the first game if it ends up with multiple results.

**Comment by darklinkpower** [comment]
oh I had not noticed that. That works, thanks!
