### ISSUE TITLE
save not being found

### ISSUE THREAD

**Issue by Triplesweet** [mtkennerly/ludusavi#162]
### Ludusavi version

v0.15.0

### Operating system

Windows

### Installation method

Standalone

### Description

i got the game of child of light, there is a general folder that it saves as well aside from the ubisoft folder
%PROGRAMDATA%\Orbit\611
but when i press the name of the game in the list it doesnt show this this path

i tried to add it myself but weirdly enough this path was already there, but i still tried to refresh the list, it still doest show that path 

i had to manually a search the folder for it to see them, why does this path (the one it had in the start) doesn't see it?

![Screenshot_20221124_024839](https://user-images.githubusercontent.com/77248142/203771619-b06fa122-4dde-45b4-93b0-4f2af77a773c.png)
![Screenshot_20221124_024750](https://user-images.githubusercontent.com/77248142/203771627-ce0cf95c-4877-47d9-9c5d-ff08aa4653e3.png)
![Screenshot_20221124_024825](https://user-images.githubusercontent.com/77248142/203771629-b117f87a-1225-4021-838a-2d9c3c02e05d.png)

**Comment by mtkennerly** [comment]
Thanks for reporting this issue. It looks like Ludusavi is incorrectly interpreting `<winProgramData>` as `C:/Windows/ProgramData`, when it should be `C:/ProgramData`. I'll fix this for the next release, but in the meantime, you can spell out `C:/ProgramData/Orbit/611` explicitly to make it work.

**Comment by mtkennerly** [comment]
This is fixed now in the new release (0.15.1).
