### ISSUE TITLE
settings and custom games

### ISSUE THREAD

**Issue by Triplesweet** [mtkennerly/ludusavi#163]
### What's your idea?

It would be really nice if we could backup or just have the data ludusavi creates, so we can move all the data to another PC with all custom games or settings (if they get complicated later on)

**Comment by mtkennerly** [comment]
You can back up and transfer Ludusavi's configuration folder: https://github.com/mtkennerly/ludusavi#configuration . Is there anything in particular you think needs to be added to make this easier?

**Comment by Triplesweet** [comment]
First of all I should apologize since I didn't read the wiki first (⁠๑⁠•⁠﹏⁠•⁠)
Second is it basically fixes my problem,
Sorry to take your time and support

**Comment by mtkennerly** [comment]
No worries :)

I'll take a look at the wiki features and see if it would be a good fit. I do prefer to have the README file as the main source of info, but it wouldn't hurt to have links to it on the wiki along with some additional info.
