### ISSUE TITLE
Custom Game paths do not support square brackets "[ ]" in path

### ISSUE THREAD

**Issue by kvnxiao** [mtkennerly/ludusavi#165]
### Ludusavi version

v0.15.1

### Operating system

Windows

### Installation method

Standalone

### Description

Ludusavi does not support adding a custom game with square brackets `[` and `]` in its path name.

I have a bunch of local games in a folder where I name the folder prefixed with `[ developer / publisher name ]` as a way of self-organizing the game folders.

However, I noticed that when I try to add to ludusavi and run the preview refresh button, it states that "No save data found" for any parent folder path containing square brackets `[]`.

To reproduce:
1. Create two folders on desktop with names `test` and `[a] test`.
2. Place an empty text file inside both folders
3. Start up ludusavi and add both folders as custom game paths to backup
![image](https://user-images.githubusercontent.com/14130413/206149103-b94da3c4-7cb8-49b8-b08c-08019a4d2260.png)
4. Observe preview on `test` -> "Save data found"
![image](https://user-images.githubusercontent.com/14130413/206149293-5edbc0fc-4390-45cb-8994-30861ab3e684.png)
5. Observe preview on `[a] test` -> "No save data found"
![image](https://user-images.githubusercontent.com/14130413/206149248-0a9f11bd-4b81-4d2e-b153-81d380f281f1.png)

**Comment by mtkennerly** [comment]
Hi! This is because brackets are special in [glob syntax](https://en.wikipedia.org/wiki/Glob_(programming)). You can escape a bracket by surrounding it in another pair of brackets:

> <img width="578" alt="image" src="https://user-images.githubusercontent.com/4934192/206204497-f6cda1ce-ea2f-4157-a7fe-c1db983fcca2.png">

Which will then find results:

> <img width="578" alt="image" src="https://user-images.githubusercontent.com/4934192/206204653-2b23f946-c892-43a9-87b9-bb782b06b4af.png">

I'll fix the folder picker so that it automatically escapes any special characters, and I'll also add some documentation to explain this.

**Comment by kvnxiao** [comment]
Oh! I didn't realize it was glob syntax by default. Should've known since it was mentioned in the readme. Thanks for the explanation! Maybe you could put an additional excerpt / warning in the readme?

Feel free to close this issue.
