### ISSUE TITLE
Ludusavi doesn't restore registry saves

### ISSUE THREAD

**Issue by DragonightFury** [mtkennerly/ludusavi#166]
### Ludusavi version

v0.15.1

### Operating system

Windows

### Installation method

Standalone

### Description

It just doesn't. They don't appear in registry

### Logs

[ludusavi_r2022-12-21_18-13-33.log](https://github.com/mtkennerly/ludusavi/files/10280201/ludusavi_r2022-12-21_18-13-33.log)

**Comment by mtkennerly** [comment]
Thanks for reporting this. I'm not sure how I overlooked this, but I have a fix ready and will do a new release shortly.

**Comment by mtkennerly** [comment]
This is now fixed in 0.15.2.
