### ISSUE TITLE
Suggestion: Make merge backup the default config

### ISSUE THREAD

**Issue by micke1m** [mtkennerly/ludusavi#167]
Long story short I was stupid and managed to annihilate my save backup with a fresh ludusavi install because I forgot merging isn't the default.

**Comment by mtkennerly** [comment]
Hi! Merge has been the default since v0.11.0, although it won't retroactively update the config if you had used an older version before that.

**Comment by micke1m** [comment]
Hey! My bad, there must have been an old config lying around then.
