### ISSUE TITLE
How does ludusavi handle `<path-to-game>`?

### ISSUE THREAD

**Issue by Bakr-Ali** [mtkennerly/ludusavi#168]
### What's your question?

Hello there!

I had installed [Yu-Gi-Oh! Power of Chaos: Yugi the Destiny](https://www.pcgamingwiki.com/wiki/Yu-Gi-Oh!_Power_of_Chaos:_Yugi_the_Destiny) a _long_ time ago, and wanted to backup its save files using ludusavi.

The paths listed on [PCGW](https://www.pcgamingwiki.com/wiki/Yu-Gi-Oh!_Power_of_Chaos:_Yugi_the_Destiny#Save_game_data_location) `<path-to-game>\..\Yu-Gi-Oh! Power of Chaos Common\system.dat` are accurate, but I'm not sure how ludusavi handles the `<path-to-game>` part of the path. I have added the path to the game `D:/Local Disk D` as a root in ludusavi as I assumed that `<path-to-game>` will be handled as a root folder, but it didn't recognize the game files.

I'm not quite sure how to make ludusavi recognize the path without adding it as a custom game?

**Comment by mtkennerly** [comment]
Hi! Sorry for the late reply. This depends on the root type:

* Let's say you have an "other" root pointing to `D:/Games`. In that case, the `<path-to-game>` for `Some Game` would be `D:/Games/Some Game`.
* Let's say you have a Steam root pointing to `D:/Steam`. In that case, the `<path-to-game>` for `Some Game` would be `D:/Steam/steamapps/common/Some Game`.

There are also some heuristics to match folders with names similar to the game title, but not exact (e.g., `Some Game` vs `some-game` vs `SOME_GAME`).

In your specific case, if `D:/Local Disk D` is an "other" root, then Ludusavi will be looking for `D:/Local Disk D/
Yu-Gi-Oh! Power of Chaos: Yugi the Destiny` (or a folder with a "roughly similar" name, which tries to account for things like capitalization and punctuation).

Could you tell me what the game's real folder name is? (not the "Common" folder, but the folder specifically for Yugi the Destiny)

**Comment by Bakr-Ali** [comment]
The game's real folder name is `D:/Local Disk D/Yu-Gi-Oh! Power of Chaos Yugi the Destiny`.
The game's executable is `D:/Local Disk D/Yu-Gi-Oh! Power of Chaos Yugi the Destiny/yug.exe`.
And the save files' folder is `D:/Local Disk D/Yu-Gi-Oh! Power of Chaos Common`.
So the game's folder and the game's saves folder are "siblings" in the same parent folder.

> then Ludusavi will be looking for `D:/Local Disk D/ Yu-Gi-Oh! Power of Chaos: Yugi the Destiny`

The colon `:` can't exist in file/folder names on Windows. Maybe that's the part that is not being handled properly?

Or is it the `\..\` part in the save files path `<path-to-game>\..\Yu-Gi-Oh! Power of Chaos Common\system.dat` that is causing the problem? I assumed it means "go up to the parent folder of the game location, and find `Yu-Gi-Oh! Power of Chaos Common\system.dat` inside it". Is that correct?

**Comment by mtkennerly** [comment]
> The colon : can't exist in file/folder names on Windows. Maybe that's the part that is not being handled properly?

Yeah, it looks like that's the issue. I'll include a fix for this in the next release.

In the meantime, you can work around this by using a custom entry:

> <img width="744" alt="image" src="https://user-images.githubusercontent.com/4934192/212835778-46689e59-62dc-477a-b41a-0830f6cfc8a2.png">

> I assumed it means "go up to the parent folder of the game location, and find Yu-Gi-Oh! Power of Chaos Common\system.dat inside it". Is that correct?

That's correct! Ludusavi can understand `..`, so no worries there.
