### ISSUE TITLE
How to fix: VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by Songtronix** [mtkennerly/ludusavi#17]
Adding this https://github.com/hecrj/iced/blob/master/.github/workflows/build.yml#L44
to the github flow will ensure that "VCRUNTIME140_1.dll was not found" won't appear anymore.

Got that tip from Iced creator himself. Figured I would share that.

**Comment by mtkennerly** [comment]
Nice! I'll make sure to add that setting.
