### ISSUE TITLE
Using secondary (single-game) .ludusavi.yaml files 

### ISSUE THREAD

**Issue by kw4s** [mtkennerly/ludusavi#170]
### What's your question?

https://github.com/mtkennerly/ludusavi-manifest states that:

> Game developers may include a secondary manifest (named `.ludusavi.yaml`) with their games, so that backup tools can automatically detect and use it to discover what files need to be backed up for save data and configuration.

I'm trying to do this:
Root is `/var/media/Games` (ludusavi is configured to scan this root and it does pick up other games contained in this root that are configured in main manifest)
Games contains let's say `GameA`, `GameB`, `GameC`
Each of those folders contains yaml file named `.ludusavi.yaml` describing save structure of the game, for example:
```
'GameA':
  files:
    <base>/www/save/:
      tags:
        - config
        - save
      when:
        - os: windows
        - os: linux
```
so for example a structure for a single game might look something like:
```
/var/media/Games/
  GameA/
    .ludusavi.yaml
    www/
      save/
        config.rpgsave
        file1.rpgsave
        global.rpgsave
```
(those are simple rpgmaker games)

ludusavi is not picking up games described in this way.
So my question is: is the support for those single-game .ludusavi.yaml implemented in ludusavi? Because I took a quick look at the source code and didn't see anything like that in there (but then again, I'm no Rust developer)?
Or maybe I am doing something incorrectly here and this is not how this functionality should be used (but then a more detailed description in ludusavi-manifest would help)...

**Comment by mtkennerly** [comment]
Hi! Unfortunately, it's not implemented just yet. I do still plan to add it, but it wasn't a high priority since no one had wanted to use it yet 😅 Time permitting, I'll try to look into implementing this soon.

**Comment by mtkennerly** [comment]
This is now implemented and will be included in the next release!

It won't affect your example, but I [made the `.ludusavi.yaml` location more specific](https://github.com/mtkennerly/ludusavi-manifest/commit/70f541fc263b0a564451bea25144d8a413036f11) to avoid degrading the scan performance. You already have it in the game's `<base>`, so no need to change anything.
