### ISSUE TITLE
REG_BINARY registry keys are not backed up, `HKEY_LOCAL_MACHINE\SOFTWARE` keys redirection

### ISSUE THREAD

**Issue by Bakr-Ali** [mtkennerly/ludusavi#171]
### Ludusavi version

v0.15.2

### Operating system

Windows

### Installation method

Standalone

## REG_BINARY registry keys are not backed up

After trying to backup [Yu-Gi-Oh! Power of Chaos: Yugi the Destiny](https://www.pcgamingwiki.com/wiki/Yu-Gi-Oh!_Power_of_Chaos:_Yugi_the_Destiny) as a custom game https://github.com/mtkennerly/ludusavi/issues/168#issuecomment-1384943541 and adding the associated registry keys, I noticed that the the REG_BINARY registry keys are not being backed up. 

These are the registry keys as exported from Registry Editor:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\KONAMI\Yu-Gi-Oh! Power Of Chaos\system]
"CommonDir"="D:\\Local Disk D\\Yu-Gi-Oh! Power of Chaos Common"
"flcrc - copy"=hex:82,f5,01,41,01,f8,75,04,30,ee,8f,bc,10
"flcrc"=hex:82,f5,01,41,01,f8,75,04,60,c0,08,27,2e
```

And this is what is backed up by ludusavi in the registry.yaml from `HKEY_CURRENT_USER/SOFTWARE/Classes/VirtualStore/MACHINE/SOFTWARE/WOW6432Node/KONAMI/Yu-Gi-Oh! Power Of Chaos/system`:
```
---
HKEY_CURRENT_USER:
  "SOFTWARE\\Classes\\VirtualStore\\MACHINE\\SOFTWARE\\WOW6432Node\\KONAMI\\Yu-Gi-Oh! Power Of Chaos\\system":
    CommonDir:
      sz: "D:\\Local Disk D\\Yu-Gi-Oh! Power of Chaos Common"
```

Notice how both keys `flcrc` and `flcrc - copy` are not backed up. (`flcrc - copy` is manually added for testing)

![image](https://user-images.githubusercontent.com/49000030/213142199-34e2f857-d99d-448c-bc60-2055a0687b5e.png)

## Back up one registry key only?

On a related note, is it possible to backup the `flcrc` key only (as the `CommonDir` key is for the location of the Common folder which probably differs from system to system)? I tried appending `/flcrc` to the end of the registry path but it didn't seem to work.

## `HKEY_LOCAL_MACHINE\SOFTWARE` & Virtualstore handling for registry keys?

Also, ludusavi doesn't seem to handle registry redirection for `HKEY_LOCAL_MACHINE\SOFTWARE`. See https://www.pcgamingwiki.com/wiki/Glossary:Game_data#Windows_registry (similar to this issue https://github.com/mtkennerly/ludusavi/issues/109)

I'm not sure what is the best way to handle it since there might be 2 different config/save keys depending on whether the game was run with or without Admin privileges?

In this specific case, the game has to be played with Admin privileges for it save progress correctly, so the keys are redirected from `HKEY_LOCAL_MACHINE\SOFTWARE\KONAMI\Yu-Gi-Oh! Power Of Chaos\system` to `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\KONAMI\Yu-Gi-Oh! Power Of Chaos\system`.

However, if the game is played without Admin privileges, the keys will be redirected to `HKEY_CURRENT_USER\SOFTWARE\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\KONAMI\Yu-Gi-Oh! Power Of Chaos\system`.

**Comment by mtkennerly** [comment]
> REG_BINARY registry keys are not backed up

Thanks for bringing this up. Ludusavi ignores these right now (i.e., more of a missing feature than a bug). I need to double check why I didn't add this to begin with, but I should be able to add support for it.

> Back up one registry key only?

You can't skip specific registry values within a key, but I think that makes sense to add as an option.

> HKEY_LOCAL_MACHINE\SOFTWARE & Virtualstore handling for registry keys?

Oh, I didn't know about this. I think Ludusavi could just always check for all three versions (plain, `WOW6432Node`, and `Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node`). Whichever ones it finds, it would treat them as distinct saves and back up/restore them independently. I wouldn't want to accidentally overwrite the wrong one if it tried to guess which one is the "main" save.

**Comment by Bakr-Ali** [comment]
> all three versions (plain, `WOW6432Node`, and `Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node`)

I think this should be all _four_ versions. The fourth one being `HKEY_CURRENT_USER\Software\Classes\VirtualStore\MACHINE\SOFTWARE`.

> but I should be able to add support for it.

> I think that makes sense to add as an option.

Thanks for considering it!

**Comment by mtkennerly** [comment]
All of this is now implemented and ready for the next release. I'm hoping to have it out within the next few days.
