### ISSUE TITLE
Implement wildcards for custom game entries.

### ISSUE THREAD

**Issue by pivotiiii** [mtkennerly/ludusavi#173]
### What's your idea?

Hi,
I would like to use Ludusavi to backup the saves of my emulated games.
Depending on the console and emulator, the .sav files tend to get placed next to the rom files.
I was using GameSave Manager in the past which allowed me to specify a backup location as "D:\ROMs\GBA\*.sav" which would only backup the .sav files in the GBA directory and any subdirectories and ignore the actual ROMs.

**Comment by mtkennerly** [comment]
Hi! This is already supported with [glob syntax](https://en.wikipedia.org/wiki/Glob_(programming)). In your example, you could use `D:\ROMs\GBA\**\*.sav` to find all of these:

* `D:\ROMs\GBA\foo.sav`
* `D:\ROMs\GBA\foo\bar.sav`
* `D:\ROMs\GBA\foo\bar\baz.sav`
