### ISSUE TITLE
Could support for EmuDeck saves be added

### ISSUE THREAD

**Issue by Crown0815** [mtkennerly/ludusavi#175]
### What's your idea?

As an [emudeck](https://www.emudeck.com/) user, it would be great to be able to easily back up and sync save games.

**Comment by sluedecke** [comment]
Do you know where emudeck stores the save games?  If it is a single folder, a quick solution would be to define a custom game which points to this folder ([Custom games](https://github.com/mtkennerly/ludusavi#custom-games)).

If you combine it with a [redirect](https://github.com/mtkennerly/ludusavi#redirects) you should be able to sync savegames across devices.

**Comment by mtkennerly** [comment]
Yes, a custom entry would be ideal for this. You might want to try some of the save locations [in this post](https://www.reddit.com/r/SteamDeck/comments/u3qlpd/q_where_do_i_find_the_savegames_from_emudeck/). It sounds like it's ultimately up to how the individual emulators are configured, though, and not directly controlled by Emudeck.
