### ISSUE TITLE
App hangs when i add a custom game

### ISSUE THREAD

**Issue by Sanfe** [mtkennerly/ludusavi#176]
### Ludusavi version

v0.15.2

### Operating system

Linux (Steam Deck)

### Installation method

Flatpak

### Description

Ludusavi hangs when i try to restore Silent Hill: Homecoming save.

How to reproduce the problem.

Make a save of any game, delete the last save, and copy a old save. App hangs not only in restore, but also, making a backup. If I disable the custom entry, the app work as usual. The mapping.yaml associated with this file is also added, but no way to continue. If I copy manually, the savedata works as expected.

The app has some database that is alive outside flatpak install? i unistalled, delete all app data and install again, but the problem continue. Also, deleting the save manually restored in the backup folder doesn't solve the problem.

**Comment by mtkennerly** [comment]
> Make a save of any game, delete the last save, and copy a old save.

Just to clarify, are you referring to the normal save location, or are you referring to the backed up version?

Also, could you please run the following command in a terminal? Afterwards, please share any log files from `~/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi`.

```
flatpak run --env=RUST_LOG=ludusavi=trace com.github.mtkennerly.ludusavi backup --preview "Silent Hill: Homecoming"
```

**Comment by mtkennerly** [comment]
Closing this for now since I can't investigate without the logs. Feel free to respond here if you get a chance.
