### ISSUE TITLE
Deck: Undertale not grabbing all files in manifest (only the first configuration file)

### ISSUE THREAD

**Issue by JSin** [mtkennerly/ludusavi#178]
### Ludusavi version

v0.15.2

### Operating system

Linux (Steam Deck)

### Installation method

Flatpak

### Description

When trying to back up Undertale, even though the configuration contains `undertale.ini` (which is correct in PCGamingWiki and [manifest](https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml)), ludusavi for some reason doesn't retrieve the file. Ludusavi does grabs registry files which are not required for saving.

Another question is should Ludusavi throw an error if not all the files are found if PCGamingWiki provides file path instead of folder paths? PCGamingWiki doesn't mark files as optional so should it be assumed all files are mandatory?

I have attached logs, configuration, and the ls of the game files (all files have the same read/write permissions in the directory)

### Log
```
INFO [ludusavi::cli] beginning backup with 1 steps
DEBUG [ludusavi::prelude] ranking installations for Steam: /home/deck/.local/share/Steam
DEBUG [ludusavi::prelude] [Undertale] selecting subdir with score 9223372036854775807: Undertale
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/drive_c/users/steamuser/AppData/Local/UNDERTALE/file9
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/drive_c/users/steamuser/AppData/Local/UNDERTALE/file9
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/drive_c/users/steamuser/AppData/Local/UNDERTALE/file0
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/drive_c/users/steamuser/AppData/Local/UNDERTALE/config.ini
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/system.reg
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/user.reg
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/userdef.reg
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/drive_c/users/steamuser/AppData/Local/UNDERTALE/file0
DEBUG [ludusavi::prelude] [Undertale] found: /home/deck/.local/share/Steam/steamapps/compatdata/391540/pfx/drive_c/users/steamuser/AppData/Local/UNDERTALE/config.ini
INFO [ludusavi::layout] [Undertale] no need for new backup
INFO [ludusavi::cli] completed backup
```

### config
```
---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: ~
language: en-US
theme: light
roots:
  - path: /home/deck/.local/share/Steam
    store: steam
redirects: []
backup:
  path: /home/deck/ludusavi-backup
  ignoredGames: []
  merge: true
  filter:
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: /home/deck/ludusavi-backup
  ignoredGames: []
  sort:
    key: name
    reversed: false
customGames:
  - name: Undertale
    files:
      - "<root>/userdata/<storeUserId>/391540/remote"
      - "<winLocalAppData>/UNDERTALE/file0"
      - "<home>/Library/Application Support/com.tobyfox.undertale"
      - "<home>/.config/UNDERTALE_linux"
      - "<winLocalAppData>/UNDERTALE/config.ini"
      - "<home>/.config/UNDERTALE_linux_steamver"
      - "<winLocalAppData>UNDERTALE/undertale.ini"
      - GOG
      - "<winLocalAppData>/UNDERTALE/file9"
    registry: []
```

### directory
![undertable-dir](https://user-images.githubusercontent.com/1067010/216785729-2ccd120d-4210-44b9-a49d-5f1c275c90bc.png)

**Comment by sluedecke** [comment]
There might be a typo in your custom configuration - the line with the `undertale.ini` misses a / in front of `UNDERTALE`:

excerpt:
```
      - "<winLocalAppData>/UNDERTALE/config.ini"
      - "<winLocalAppData>UNDERTALE/undertale.ini"
```

HTH

**Comment by sluedecke** [comment]
This error originates from the data on pcgamingwiki:  https://www.pcgamingwiki.com/wiki/Undertale

**Comment by JSin** [comment]
Thanks @sluedecke for noticing the typo.  Apologies for being blind. I'll mark this ticket as closed and open an issue with PCGamingWiki

**Comment by JSin** [comment]
Curious @sluedecke to get your thoughts on my other comment, if it makes sense to throw an error throw an error if not all the provided files (file path not directory path) are found from PCGamingWiki? PCGamingWiki doesn't mark files as optional so should it be assumed all files are mandatory?

**Comment by sluedecke** [comment]
In the scenario when you have started the game once, but did not yet create a save game, some files might be rightfully missing.  I would go for a warning if some files or folders are not present.

But: ludusavi would then need to aware which 'system' you are using (no need to warn about missing macos files on a linux machine etc.) and I am not sure if it is at the moment.  The manifest includes such information, but `prelude::scan_game_for_backup` uses a list of paths generated in `prelude::parse_paths` and this list no longer has this information.  Maybe @mtkennerly has some more thoughts on that.

**Comment by sluedecke** [comment]
Giving it some more thought, I would even question having a warning, for example [Dwarf Fortress](https://www.pcgamingwiki.com/wiki/Dwarf_Fortress): versions < 50.x store their saves in `<path-to-game>/data/save`, but the latest version 50.x and up store it in `<path-to-game>/save`.  There is no information on how to differentiate that, so even a warning would be potentially misleading here.

**Comment by mtkennerly** [comment]
Yeah, it's really hard to do a warning like that without false positives, since it can vary by game and how complete/accurate the PCGW page is.

Thanks for helping catch the data error here :+1:
