### ISSUE TITLE
Allow redirects to be reordered (drag and drop?) in the UI

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#179]
### What's your idea?

Redirects are searched until a matching one is found.  This allows for having a 'catch all' entry as last entry and some earlier ones to handle games specifically, e.g.:

* /home/deck/.../steam/gamea <-> /GAMEA_HOME
* ...
* /home/deck/.../steam' <-> /STEAMHOME

So my feature request is to implement some reordering in the UI, e.g. via drag and drop or with some up/down buttons.

**Comment by mtkennerly** [comment]
I think drag and drop would be ideal, but it's also much more complicated to do, so I'll add some up/down arrows for now.

Preview:

> https://user-images.githubusercontent.com/4934192/223566295-838db20c-3911-45dc-a71a-67fb914fb953.mp4
