### ISSUE TITLE
Allow Annotations to Backups on a per Game Basis

### ISSUE THREAD

**Issue by dla-kramski** [mtkennerly/ludusavi#180]
### What's your idea?

At DLA Marbach, we have begun providing literary and narrative computer games to our library users - mostly via Steam.

Our academic users who research and analyze computer games are typically on site for a few days.

We therefore need to keep prepared game saves on hand, as none of them want to start at level 1 with just a crowbar in hand, but would prefer to find a fully explored game world or specific milestones in the gameplay. Or we need to reset game levels to a defined state after their visit.

In this context, Ludusavi is a blessing, especially because it can be scripted and works independently of Steam Cloud.

What is still missing is the ability to add game-specific annotations to individual, selected backups that describe the content of the saved game state. So, for example, "Fresh installation", "Shortly before the final ascent to the transmission tower" or similar.

One could e.g. offer a new menu item "Annotation" in the GUI in the Restore Mode view per backup version, which shows an existing description in a small text editor or lets create one.

In the CLI mode I can hardly imagine such a function, because the input would interrupt the backup process and not every backup needs an annotation.

Granted, this is a special use case, but describing game states might be useful in general too.

Anyway, thanks for a great software that is already very useful for us.

Regards, Heinz

**Comment by mtkennerly** [comment]
Thanks for the suggestion! I think this would be a good addition.

I'm very happy to hear that Ludusavi has been helpful to your institute :)

**Comment by mtkennerly** [comment]
Thanks for the suggestion! I think this would be a good addition.

I'm very happy to hear that Ludusavi has been helpful to your institute :) Would you mind if I possibly added a short mention of this in the README? I just think it's an exciting milestone for the project.

**Comment by dla-kramski** [comment]
I will be happy if we can support the project ideally. I just have to point out that we are just setting up the provision of computer games. So there are not many users yet.

**Comment by mtkennerly** [comment]
@dla-kramski This will be included in the next release, hopefully within a week or two. I'm open to ideas for changes/improvements to how it works, but this is what I have right now:

> https://user-images.githubusercontent.com/4934192/223600043-ee5baeb8-ce18-40dc-8756-b481dc403dbf.mp4

**Comment by dla-kramski** [comment]
Look great and fits nicely into the existing shashlik menu! Thanks a lot!

**Comment by mtkennerly** [comment]
[v0.16.0 is now available](https://github.com/mtkennerly/ludusavi/releases/tag/v0.16.0) :)
