### ISSUE TITLE
UI Element Separation

### ISSUE THREAD

**Issue by freezerburn26** [mtkennerly/ludusavi#181]
There's no indication of the separate UI areas so it just seems like things get broken at random when you click between tabs or whatever because you have this big empty space that isn't filling up and all your root list seemingly got overwritten by the add root button. If possible, it would be nice if the the UI had separators and scroll bars so you could visually grasp that the root area is not supposed to overflow into the game list.

**Comment by mtkennerly** [comment]
I've been thinking about moving the roots to the other screen so it's doesn't take up valuable space from the game list. That would also help make the boundaries clearer.

There is a scroll bar next to the roots, but I know it can get small if you have a lot of roots.
