### ISSUE TITLE
Flaptak install don't run and show Invalid window geometry for errors

### ISSUE THREAD

**Issue by yodatak** [mtkennerly/ludusavi#183]
### Ludusavi version

v0.15.2

### Operating system

Linux

### Installation method

Standalone

### Description

with the flatpak install i can't run the program it don't show anything

févr. 24 23:37:47 fedora.home systemd[2503]: Started app-gnome-com.github.mtkennerly.ludusavi-7306.scope - Application launched by gnome-shell.
févr. 24 23:37:47 fedora.home systemd[2503]: Started app-flatpak-com.github.mtkennerly.ludusavi-7306.scope.
févr. 24 23:37:47 fedora.home gnome-shell[2665]: Invalid window geometry for xdg_surface@31. Ignoring for now, but this will result in client termination in the future.
févr. 24 23:37:47 fedora.home gnome-shell[2665]: Invalid window geometry for xdg_surface@56. Ignoring for now, but this will result in c

### Logs

flatpak info com.github.mtkennerly.ludusavi                                                    

ludusavi - Ludusavi is a tool for backing up your PC video game save data.

          ID: com.github.mtkennerly.ludusavi
         Ref: app/com.github.mtkennerly.ludusavi/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.15.2
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 15,8 Mo
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: d1bdf2de8cd42682faa18e40dd30d375fa0b375d35ee67f3315fb97f5d665999
      Parent: 532f9a937ca838b8162829397eebe11eb739a8948b027fb629c2a3707d9d1c30
     Subject: Update for v0.15.2 (0657a460)

**Comment by yodatak** [comment]
Same error for non flatpak installation

**Comment by mtkennerly** [comment]
What GPU model and graphics drivers do you have? Could you please make sure your graphics drivers are up to date and see if that helps?

**Comment by mtkennerly** [comment]
Let me know if you get a chance to try with updated graphics drivers. I think that's the most likely explanation, but if that still doesn't help, then we can try to get some logs from the graphics library.

**Comment by yodatak** [comment]
Hi thanks it was an issue with nvidia driver I think I cannot reproduce anymore but weird issue
