### ISSUE TITLE
Redirects path are wrongly parsed when synced across OS 

### ISSUE THREAD

**Issue by WangEdward** [mtkennerly/ludusavi#185]
### Problem

I was trying to sync some game progress between a Mac and a Windows PC, and the path for the game saves as follows:
Mac: `/Users/edward/.config/Ryujinx/...`
Windows: `C:\Users\admin\AppData\Roaming\Ryujinx\...`

I first tried to use Bidirectional on the Windows PC, configured as follows:
<img width="919" alt="Screenshot 2023-03-01 at 22 07 48" src="https://user-images.githubusercontent.com/73746306/222168523-2312b0e3-e372-45b6-b9ba-b912154bbc3c.png">
And this is what I got (on Mac):
<img width="1239" alt="Screenshot 2023-03-01 at 22 28 44" src="https://user-images.githubusercontent.com/73746306/222169500-097ee937-3cd6-4f40-acbe-8e85007ca7b8.png">
**What seems to have happened is that on Windows, `/Users/edward/.config/Ryujinx/...` is recognised as a relative path and it auto-completes it to a windows 'absolute path' `C:/Users/edward/.config/Ryujinx/...`** 😥

### Temperally workaround

A rough way of making the program functional is config the two devices as follows:
<img width="908" alt="Screenshot 2023-03-01 at 22 08 24" src="https://user-images.githubusercontent.com/73746306/222172953-2015076e-a475-4243-83ba-9aa785759046.png">
<img width="992" alt="Screenshot 2023-03-01 at 22 34 51" src="https://user-images.githubusercontent.com/73746306/222172966-09885020-3104-42ef-872f-5bba4a67eae0.png">
**When just redirecting the restore path, the backup path saved in the `mapping.yaml` will be correct.**

It can let the game save work. However, the root cause is not solved therefore there's still a small problem:
On mac upon restoration, `C:/Users/admin/AppData/...` is recognised by mac as a  relative path and it converted it to a mac 'absolute path' `/Users/edward/C_/Users/admin/AppData/...`😂
<img width="966" alt="Screenshot 2023-03-01 at 22 53 53" src="https://user-images.githubusercontent.com/73746306/222175918-c9493bae-fd51-4336-8935-73230f681bb9.png">
This setting does work because the redirect path on mac is being parsed the same way, it's now just a minor 'display error'.

### Possible Solution

- The `is_absolute` method might need a small fix.
- Adding a checkbox to let the user set if the path is absolute can be a very user-friendly solution.
- Or it might be possible to use a certain format for the path input to indicate if the path is an absolute/relative directory. e.g. add `$` before the relative paths
- Allowing users to use curtain environment variables in the path (as mentioned in https://github.com/mtkennerly/ludusavi/issues/16#issuecomment-656701853) can also solve the problem.

Anyway, thanks very much for your effort on this project, it's very helpful.❤️
(I was trying to make this issue short, but my English level does stop me from that, my apologies)

**Comment by mtkennerly** [comment]
Yeah, this could definitely use some improvement. It should probably be able to highlight these cases and streamline the redirect creation.

> What seems to have happened is that on Windows, `/Users/edward/.config/Ryujinx/...` is recognised as a relative path and it auto-completes it to a windows 'absolute path' `C:/Users/edward/.config/Ryujinx/...` 😥

On Windows, it assumes any path starting with `/` means the primary drive letter. To some extent, this is a feature (e.g., I have a `C:/tmp` folder that can map as-is to Linux `/tmp`), but it's not helpful in your case since you really do want to redirect it into a version without a drive letter. It probably makes more sense to treat `/`-prefixed paths on Windows as invalid and require a redirect for them.

> (I was trying to make this issue short, but my English level does stop me from that, my apologies)

No worries, your English is great! Thanks for bringing this up.
