### ISSUE TITLE
Garbled characters will appear when the tool is switched to ChineseSimplified

### ISSUE THREAD

**Issue by xiexiaosheng** [mtkennerly/ludusavi#187]
### Ludusavi version

v0.15.2

### Operating system

Windows

### Installation method

Standalone

### Description

![QQ截图20230305234746](https://user-images.githubusercontent.com/64482026/222970878-a4d666a4-7972-4832-8c89-e6bc8e19c86d.png)

**Comment by mtkennerly** [comment]
There's an existing ticket for this: https://github.com/mtkennerly/ludusavi/issues/9. Unfortunately, this is still a limitation of Iced, the graphics library that Ludusavi uses, but there has been some progress lately. I'm hoping that this will be fixed within the next few months. Please see https://github.com/mtkennerly/ludusavi/issues/9 for any updates.
