### ISSUE TITLE
Document installation via scoop

### ISSUE THREAD

**Issue by sharkusmanch** [mtkennerly/ludusavi#19]
I created a [scoop](https://github.com/lukesampson/scoop) manifest for ludusavi to handle automated installs and updates.

https://github.com/lukesampson/scoop-extras/pull/4413

Once that is merged, can be installed via:
```
scoop bucket add extras
scoop install ludusavi
```

Upgrade
```
scoop update ludusavi
```

**Comment by mtkennerly** [comment]
That's awesome, thanks! I'll add a note as soon as your PR gets merged :+1:

**Comment by mtkennerly** [comment]
FYI, v0.5.0 is out now, but your PR should still be fine. Once it gets merged, I think they have some processes in place to keep things up to date.

**Comment by sharkusmanch** [comment]
It's been merged. Still using 0.4.0, but they check for new versions hourly and will be using 0.5.0 when the update occurs.

**Comment by mtkennerly** [comment]
Great! I've added the note to the README. For reference, I was able to install it before they updated to v0.5.0, and I found that I also had to run `scoop update` in order for `scoop update ludusavi` to realize there was a newer version.
