### ISSUE TITLE
Add root button missing

### ISSUE THREAD

**Issue by canepan** [mtkennerly/ludusavi#191]
### Ludusavi version

v0.16.0

### Operating system

Linux

### Installation method

Standalone

### Description

The README mentions the way to add a new root is to "click add root", but I cannot find that in any of the program tabs

**Comment by canepan** [comment]
The button is present in v0.15.2

**Comment by mtkennerly** [comment]
Sorry, I'll need to update that instruction. It's been moved to the"other" screen (roots section -> plus icon).

**Comment by mtkennerly** [comment]
The documentation is now updated. For reference, here's the new location:

> ![image](https://user-images.githubusercontent.com/4934192/227266717-c019a6a1-63c8-41a7-8472-85187df7c34c.png)
