### ISSUE TITLE
Limitable concurrency in scanning / backup process

### ISSUE THREAD

**Issue by telyn** [mtkennerly/ludusavi#193]
### What's your idea?

First off thanks for making this software! I'm so glad it exists!

When backing up to a relatively slow drive with poor seek times, the parallel iterators currently used start writing many zip files simultaneously. This results in poor performance & disk thrashing. 

In my admittedly rather tortuous use case (backing up directly from my steam deck to a samba share which is 3 or more network sockets away from the actual physical disk) if I could limit the number of concurrently-running backups to small single-digit numbers I'd see much better performance and my server's hard drive would thrash a lot less :)

An option in the Other menu for this, or in the cog menu in the Backup Mode would be incredible :-) 

From a [quick google](https://github.com/rayon-rs/rayon/blob/master/FAQ.md) it looks like I might be able to sort myself out using the `RAYON_NUM_THREADS` environment variable - I'll try it out next time I back up my saves and get back to you.

**Comment by mtkennerly** [comment]
That sounds reasonable! The Rayon option might work for the CLI, but the GUI also uses Tokio, so it would definitely be good to have a unified option.

**Comment by mtkennerly** [comment]
I think limiting Tokio's threads would be fine. The GUI itself runs on the main thread, and async tasks aren't used for too much besides scanning games. It looks like newer versions of Tokio added an environment variable to set this, but Ludusavi v0.16.0 is still using an older version.

For an idea of how this impacts performance (although I'm not using network storage), on my system, here's the total time for a backup preview:

| threads | seconds |
| - | - |
| 16 | 10.30 |
| 8 | 11.23 |
| 4 | 16.90 |
| 2 | 30.65 |
| 1 | 56.17 |

And this is how the option will look:

> <img width="277" alt="image" src="https://user-images.githubusercontent.com/4934192/230620040-f0f6acad-508c-4392-bf68-6e4701f20e81.png">

**Comment by telyn** [comment]
Hello! Just wanted to check in and say thank you so much! The last few times I've used ludusavi it's **not** made my server sound like it's full of intensely angry bees, at only a minor speed penalty!

These changes have worked beautifully for me and I'm very grateful!
