### ISSUE TITLE
no Chinese language in Language Setting

### ISSUE THREAD

**Issue by J-EnJay** [mtkennerly/ludusavi#195]
![image](https://user-images.githubusercontent.com/44085839/230784797-91b50efc-8ca5-4c5f-9a54-25a81fadd12e.png)

**Comment by mtkennerly** [comment]
Unfortunately, there are some technical limitations around this. You can enable it experimentally by editing the [config file](https://github.com/mtkennerly/ludusavi#configuration-file) and setting `language: zh-Hans`, but it probably won't display correctly until https://github.com/mtkennerly/ludusavi/issues/9 is resolved. Iced (the graphics library that Ludusavi uses) has recently made some good progress toward the necessary text support, but there's no specific date when it would be ready for Ludusavi to use.
