### ISSUE TITLE
Reverse Function Ludusavi (Delete saved games)

### ISSUE THREAD

**Issue by TheJAXi** [mtkennerly/ludusavi#196]
Would this be possible? I already figured out the earlier issue (kinda, just a way around by changing paths away from C drive. Still would love a way to ignore default save imports on !single portable! Ludusavi instance).

Now facing a problem when having different people playing on my PC and I'd love to have their saved games safe as well. I made Windows profiles for those people already & figured out how to back them all up safely using altering configs.

Just when for example someone new wants to play a game they haven't played before, obviously it's going to have a backup that hasn't been overridden by theirs yet. Probably shouldn't include this in the GUI, but CLI function to delete saved games from those locations set in Ludusavi/config.

**Comment by TheJAXi** [comment]
Is there a way to only keep the custom ones enabled but ignore others? I'd like to have two ludusavi instances. One from Playnite that handles steam games & other games and one that only handles emulator save data.

**Comment by mtkennerly** [comment]
This is certainly doable, although I would worry that some games may not handle it well if the files are deleted. Hopefully most games are robust enough to recreate the files in a default state, but I bet it could cause errors for some games.

For now, you could accomplish this with a small script that takes the `backup --preview --api` CLI output and loops over all the files.

> Still would love a way to ignore default save imports on !single portable! Ludusavi instance

If I understood correctly, you have some custom entries that overlap with a default entry, and you'd like to disable the default one. Is that correct? Either of these options should work:

* Uncheck the default entry in the list of scanned games
* Override it with a custom entry and blank out its files/registry list

**Comment by TheJAXi** [comment]
Hi, yeah... I think some games would be like that but from what I've seen and what I have 40 000 games library and growing all of them recreate folders (just recently wiped out my virtual machine and all of the games I've tried so far work).

I didn't quite understand the command. What does it do? Delete the existing files even though there's no backup?

And yup, you understood correctly. Just that I don't use the GUI (trying to automate stuff). I got it working by moving Yuzu folder to different drive.

I'm so close to getting this perfect gaming box build that can be wiped any time & supports multiple users with own save files & backups to cloud.




JAXi 3124990-9
________________________________

**Comment by mtkennerly** [comment]
> I didn't quite understand the command. What does it do? Delete the existing files even though there's no backup?

It performs a scan and tells you all save files on the system, but doesn't back them up (because of `--preview`).

Here's an example from running `ludusavi backup --preview --api "1000 Amps"`. Since the command includes a specific game name(s), it only has results for that game, but normally it would just list everything.

```json
{
  "overall": {
    "totalGames": 1,
    "totalBytes": 2531,
    "processedGames": 1,
    "processedBytes": 2531,
    "changedGames": {
      "new": 1,
      "different": 0,
      "same": 0
    }
  },
  "games": {
    "1000 Amps": {
      "decision": "Processed",
      "change": "New",
      "files": {
        "C:/Program Files (x86)/Steam/steamapps/common/1000 Amps/save1": {
          "change": "New",
          "bytes": 843
        },
        "C:/Program Files (x86)/Steam/steamapps/common/1000 Amps/save2": {
          "change": "New",
          "bytes": 843
        },
        "C:/Program Files (x86)/Steam/steamapps/common/1000 Amps/save3": {
          "change": "New",
          "bytes": 843
        },
        "C:/Program Files (x86)/Steam/steamapps/common/1000 Amps/settings": {
          "change": "New",
          "bytes": 2
        }
      },
      "registry": {}
    }
  }
}
```

You could then use a script (e.g., in Python) to do something like this (**untested, but should delete all save files on your system**):

```python
import subprocess
import json
from pathlib import Path

result = subprocess.run("ludusavi backup --preview --api", stdout=subprocess.PIPE)
data = json.loads(result.stdout)

for game in data["games"].values():
    if "files" in game:
        for file in game["files"]:
            Path(file).unlink()
```

(This example won't delete any registry-based saves, but you could extend it to do that.)

> And yup, you understood correctly. Just that I don't use the GUI (trying to automate stuff). I got it working by moving Yuzu folder to different drive.

Gotcha. It does remember if you uncheck something, so you'd only need to set it up once. You could also edit the config file directly if you want to avoid the GUI altogether:

```yaml
backup:
  ignoredGames:
    - Yuzu
```
