### ISSUE TITLE
Ability to pin selected backup

### ISSUE THREAD

**Issue by Xarnowit** [mtkennerly/ludusavi#200]
### What's your idea?

Sometimes for games with limited save slots, or single save, it would be nice to have ability to pin save state so it is ignored by retention rules and doesn't get deleted. For example imagine reaching important milestones in a game with multiple choices, and then pining that save with annotation about upcoming decision. This would allow one to keep relatively low retention number while still maintaining ability to keep most important saves backed up.

**Comment by mtkennerly** [comment]
I think that's a great idea :+1:
