### ISSUE TITLE
Saves in Bottle based wine-prefix not deteced

### ISSUE THREAD

**Issue by JHerseth** [mtkennerly/ludusavi#205]
### What's your question?

Hi,

First of all, great work on this software.

I'm trying to set up backup of some games I have in a wine-prefix managed by Bottle. The `drive_c` folder is located within `/home/jonas/.var/app/com.usebottles.bottles/data/bottles/bottles/Games`, so this is the path I've set up as a new root in the `Other` tab in ludusavi.  The type is set to wine-prefix.

I have a couple of games installed here from GOG, like Tunic and DREDGE, but they are not picked up by ludusavi.  Am I doing something wrong in my setup? Thank you!

**Comment by mtkennerly** [comment]
Hi! If you installed Ludusavi via Flatpak, then it probably doesn't have permission to view Bottles' files. Can you try using Flatseal to give it access to `/home/jonas/.var/app/com.usebottles.bottles` ?

**Comment by JHerseth** [comment]
Thanks @mtkennerly . I had checked flatseal already and saw that ludusavi had `All user files` enabled by default, so I didn't think to add the Bottles directory manually also, since it resides in /home/. But adding it resolved the issue!
