### ISSUE TITLE
Location of heroic gog library.json has changed

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#214]
### Ludusavi version

v0.18.2

### Operating system

Linux (Steam Deck)

### Installation method

Cargo

### Description

Original title: Cult of the Lamb: `<home>/AppData/LocalLow/Massive Monster/Cult Of The Lamb/saves` not recognized

I want to back up another fine game, but ludusavi does not find any file for it.  Apparently 
`<home>/AppData/LocalLow/Massive Monster/Cult Of The Lamb/saves` is not recognized properly.  

On the other hand, saves for "Alba: A Wildlife Adventure", which has a similar file structure, are recognized.

After some digging it turns out that heroic no longer stores your gog library information in `.config/heroic/gog_store/library.json`, but uses `.config/heroic/store_cache/gog_library.json` instead.

**Comment by sluedecke** [comment]
This might suffice to fix it, but needs verification. Right now I don't grok heroics code too well to even find when this change was introduced :(

```diff
diff --git a/src/scan/launchers/heroic.rs b/src/scan/launchers/heroic.rs
index 7697a22..f762274 100644
--- a/src/scan/launchers/heroic.rs
+++ b/src/scan/launchers/heroic.rs
@@ -152,7 +152,7 @@ fn detect_gog_games(root: &RootsConfig, title_finder: &TitleFinder) -> HashMap<S
     );
 
     // use gog_store/library.json to build map .app_name -> .title
-    let library_path = root.path.joined("gog_store").joined("library.json");
+    let library_path = root.path.joined("store_cache").joined("gog_library.json");
     let game_titles: HashMap<String, String> =
         match serde_json::from_str::<GogLibrary>(&library_path.read().unwrap_or_default()) {
             Ok(gog_library) => gog_library
```

**Comment by mtkennerly** [comment]
It looks like this was introduced in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2538, so Heroic 2.7.0 or newer. Thanks for reporting this!
