### ISSUE TITLE
Button to open the backup / restore directory (or any settable path)

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#219]
### What's your idea?

It would be convenient if there was a way to quickly open the path which is set for the backup or restore directory.

Instead of introducing an additional button for this function (if UI space is a concern), it may be nice for the folder icon button (which is used to set the backup / restore path) to double as the open-folder-in-file-manager button via the same Ctrl / Shift feature that the game row menu buttons use for their quick actions, such as Preview.

The above suggestion makes more sense if you consider extending this feature to _all_ folder icons in Ludusavi, such as all those shown on the _Custom Games_ and _Other_ tabs. This way, any path that can be set via said icon could be quickly used to browse it in a system's file manager.

Thanks!

Ludusavi 0.19.0

**Comment by mtkennerly** [comment]
I went with shift+click \:D Demo:

https://github.com/mtkennerly/ludusavi/assets/4934192/f1d73418-aa8d-4c37-afbc-2c9e764e96f5

**Comment by redactedscribe** [comment]
Very nice! Thanks for the addition 😄
