### ISSUE TITLE
Custom games exclude folders/files

### ISSUE THREAD

**Issue by TeamLinux01** [mtkennerly/ludusavi#220]
### What's your idea?

I would like to be able to tell the tool to include all but one or several files from a directory.
It could be broken up to have the include list above the exclude list for a custom game.

I can manually just include all the subfolders and files I want to include and leave the one file out, but it would be easier to be able to list the one file I would like to be excluded.

Thank you very much for your time, effort and dedication.

**Comment by TeamLinux01** [comment]
- name: Sonic Adventure DX (mod)
    files:
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/programming
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_TEX_ENT_COMMON_JP.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/EROBO_GC.NB
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_HINT_G.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/ABC_TXT.PVR
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/EV_EGGMOBLE0.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_SONIC_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_HINT_J.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTO_CMN.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/ADV03MODELS.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_STG_KINDER_AD_TEX.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_TAILS_F.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA6.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA7.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_OPTION.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/ADV02MODELS.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CON_REGULAR_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTO_CMN_SHOW_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/BOSSCHAOS0MODELS.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_E102_G.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_BIG.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_EC_H.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_KNUCKLES_G.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_E102_F.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/E101R_GC.NB
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/PRESSSTART.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_RACE_F.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_KNUCKLES_F.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_BIG_F.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CON_REGULAR.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/ADV00MODELS.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/RE-US.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MILESRACE.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_TITLE.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_HINT_F.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA3.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_EC_B.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_EC_A.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_AMY.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_TITLE_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_SNDTEST.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHRMODELS_orig.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA5.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAOSTGGARDEN02MR_NIGHT.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_AMY_F.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_TAILS.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_SONIC_F.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_BIG_G.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_TITLE_CMN_SMALL.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_RACE_S.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_GTITLE0_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_SONIC_G.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_TAILS_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MIS_C_EN.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTO_CMN_SHOW.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/ADV01CMODELS.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_TEX_ODEKAKE_MENU_EN.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MIS_C_J.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_SNDTEST_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_DX_OBJ_CMN.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_SONIC_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA4.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_OPTION_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_RACE_G.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_KNUCKLES_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHRMODELS.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_MR_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_TITLE_CMN.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_SS.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AVA_GTITLE0.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_RACE_J.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_RACE_E.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_KNUCKLES_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA2.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAOSTGGARDEN02MR_EVENING.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA1.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_MR_A.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_BIG_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_SONIC.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_PAST_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_KNUCKLES.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_AMY_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_ODEKAKE_E.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_TEX_ODEKAKE_MENU_JP.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_PAST_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_BLACKMARKET_E.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/RE-JP.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_E102.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/SA8.mpg
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MISSION.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_TAILS_G.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_DX_TEX_XYBUTTON.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_E102_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_HINT_E.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_AMY_G.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAOSTGGARDEN02MR_DAYTIME.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_E102_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_TEX_ENT_COMMON_EN.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/AL_TEX_ENT_COMMON_FR.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_TAILS_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_AMY_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/MAP_MR_J.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTOMSG_BIG_S.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/ADV01MODELS.DLL
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/GARDEN00SS.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/TUTO_CMN_E.PVM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/system/CHAODX_MESSAGE_HINT_S.BIN
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/AppLauncher
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/mods
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0032.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0704.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0140.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/2048.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/2045.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0712.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/2046.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0104.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/2047.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0158.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0014.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/2044.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0050.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0122.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0086.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_JP/WMA/0068.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0032.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0140.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/2048.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/2045.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/2046.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0104.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/2047.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0158.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0014.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/2044.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0050.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0122.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0086.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SoundData/VOICE_US/WMA/0068.adx
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SADXModManager.pdb
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SADX Mod Installer.log
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/jansson.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libogg.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/avutil-vgmstream-56.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SADXModManager.exe
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/sonic.exe
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libvorbisfile.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/7z.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/COPYING_VGMSTREAM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libcelt-0110.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libg7221_decode.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/d3d8.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/steam_appid.txt
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/COPYING_D3D8TO9
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/ModManagerCommon.pdb
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/loader.manifest
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/sonicDX.bak
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/AppLauncher.exe
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/AppLauncher.crc
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/avcodec-vgmstream-58.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SharpDX.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SharpDX.DirectInput.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libmpg123-0.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/AppLauncher.dat
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/7z.exe
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libcelt-0061.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libatrac9.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libspeex.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libg719_decode.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/Steam Launch Options.txt
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/ModManagerCommon.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SADX Steam Conversion.log
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/bass_vgmstream.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/swresample-vgmstream-3.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/bass.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/sadxmlver.txt
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/Newtonsoft.Json.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/d3d8m.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SADXModManager.exe.config
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/sonic_original.exe
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/avformat-vgmstream-58.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/COPYING_BASS_VGMSTREAM
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/libvorbis.dll
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/SDL2.dll

I would like to exclude the file
      -/steam/SteamLibrary/steamapps/common/Sonic Adventure DX/mods/SADXModLoader.ini

This file is the configuration file, so it stores the resolution of the game. Since my PC and Steam Deck have different resolutions, this file will change between them, depending on which system does the backup. If I could exclude that file, no other changes would show up between the two systems.
I would then create a separate custom game for just the configuration file for each system.

If this is out of scope for what you want Ludisavi to do, I understand.

It has been a big help keeping both my game saves and game installs in sync and I thank you for that.

**Comment by mtkennerly** [comment]
Gotcha. That's a bit more complicated than what the glob functionality can do. The easiest two options would be either:

* Include everything, scan the game, and then uncheck that file in the scan results. It will stay unchecked on future scans.
* Add the file to the list of global backup exclusions so it doesn't even show up in the scan results.

Of course, since those settings aren't attached to the custom game directly, they wouldn't be shared between computers in the context of #217 or #95.

> If this is out of scope for what you want Ludisavi to do, I understand.

On one hand, I'd prefer to stick to the current "include and uncheck" solution since it's simple, but on the other hand, I'm open to other solutions if it's a common pain point or if it can't handle certain use cases.

> It has been a big help keeping both my game saves and game installs in sync and I thank you for that.

I appreciate that :D I'm glad you've found it helpful.

**Comment by TeamLinux01** [comment]
If I can easily copy the exclusion file into the config.yaml, that works for me if it is a global exclude.

**Comment by mtkennerly** [comment]
Sure, you can control  it with the `backup.filter.ignoredPaths` and `backup.filter.ignoredRegistry` keys. You should see `ignoredPaths: []` as the default setting. You can set it like this:

```yaml
    ignoredPaths:
      - /steam/SteamLibrary/steamapps/common/Sonic Adventure DX/mods/SADXModLoader.ini
```

**Comment by mtkennerly** [comment]
By the way, since you're comfortable working with the config file directly, you can also use `backup.toggledPaths` to prevent backup of specific paths (but still have them show up in the scan results). For example:

```yaml
backup:
  toggledPaths:
    "Sonic Adventure DX (mod)":
      "/steam/SteamLibrary/steamapps/common/Sonic Adventure DX/mods/SADXModLoader.ini": false
```
