### ISSUE TITLE
Windows Defender Flags as Virus - Trojan:Win32/Bearfoos.A!ml 

### ISSUE THREAD

**Issue by Hawxxer** [mtkennerly/ludusavi#221]
### Ludusavi version

v0.19.0

### Operating system

Windows

### Installation method

Standalone

### Description

![image](https://github.com/mtkennerly/ludusavi/assets/46371370/b82e5861-9a57-42cb-92da-6b6079eb68a8)

Newest Version gets flagged as Virus.

**Comment by mtkennerly** [comment]
This is definitely a false positive, but unfortunately, I don't really have any control over it. For what it's worth, VirusTotal doesn't report any concerns:

* Windows 64-bit: https://www.virustotal.com/gui/url/b5ffeac7a9805cfc2181c16204062870686ee5d76e4932d3e0cfb2724823766d?nocache=1
* Windows 32-bit: https://www.virustotal.com/gui/url/8e1eefb6ddbf0e4eb158304caa552c17571671174a15fb1793858d53618f9c7b?nocache=1
