### ISSUE TITLE
Multiple Backup Destinations

### ISSUE THREAD

**Issue by Aznlilly** [mtkennerly/ludusavi#224]
### What's your idea?

It would be great if you could select multiple backup locations so you don't have to switch the destination and mess with the number of delta backups.

**Comment by mtkennerly** [comment]
Could you give me some context about how you would use this so I can understand your use case? Why do you want to create backups in two local folders at once?

**Comment by Aznlilly** [comment]
I don't. I use things like rclone to mount cloud storage and backup to it, it would be nice to be able to set up multiple destinations.  Also the google drive for desktop or dropbox or any other cloud storage mount would let you get both local and off site backups.

**Comment by mtkennerly** [comment]
I see, so you want one backup to a pure local folder and one backup to an Rclone remote. Have you tried using Ludusavi's own Rclone integration (configured on the "other" screen)? It can make the local backup first and then upload it. If you choose a "custom" remote in Ludusavi, you can even give it the name of your existing remote and reuse it.

If you want to upload to multiple remotes, you could try Rclone's [`union` remote](https://rclone.org/union) feature with the [`all` policy](https://rclone.org/union/#policy-descriptions). I haven't tried it myself, though.

**Comment by TeamLinux01** [comment]
That's how I do it. It backs up to a local folder on my PC then it rclone to a folder on my server, same with my Steam Deck.

Keeping the three in sync does require a little extra work by pressing the sync to/from the "cloud" location.

One more thing that I did was put both of the config.yaml (each one in a folder named for the computer) into the same root folder as the rest of the backups and symbolic linked them to their original location, so they get synced with the rest of the saves.
