### ISSUE TITLE
Filter games by save status and/or platform

### ISSUE THREAD

**Issue by kekonn** [mtkennerly/ludusavi#225]
### What's your idea?

I propose two new filters:

- Save status: new, updated, no filter
- Platform: Based on the list in Roots, i.e.: show only steam games, ...

**Comment by mtkennerly** [comment]
For the root type filter:

* In `scan::scan_game_for_backup`, when we add a path found by `scan::parse_paths`, we can track the root type the same way that we currently track whether the path is case-sensitive. Then, when we find a path that exists, we can keep a set of all unique root types with a match and store that as part of the returned `ScanInfo`.
* `search::FilterComponent::qualifies` would then be able to access that new field from `ScanInfo`.

We could even store the root type as part of each individual `ScannedFile`, but we're only filtering at the game level right now, so I don't think that's necessary. We could also consider putting a badge in `game_list::GameList` for the root types, if there's room for it.

**Comment by mtkennerly** [comment]
Based on the discussion in #329, I think the underlying use case is now addressed by #44, but please let me know if you have any other ideas or issues related to this.
