### ISSUE TITLE
Command & Conquer 3: Kane's Wrath on Steam is not backed up on Linux.

### ISSUE THREAD

**Issue by TeamLinux01** [mtkennerly/ludusavi#227]
### Ludusavi version

v0.19.0

### Operating system

Linux

### Installation method

Standalone

### Description

The files for Command & Command 3: Kane's Wrath (App ID  24810) uses a different Proton Prefix than Command & Conquer 3: Tiberium Wars (App ID 24790), so the files are not detected to be backed up. I asked about having a dedicated page for Kane's Wrath, but was denied. https://www.pcgamingwiki.com/wiki/Topic:Xkfft1htsdih90vt

I am wondering if there is anything that can be done besides manually entering the paths for the saves?

I am sorry if I didn't go about requesting the changes on PCGamingWiki correctly. I am very new to it.

**Comment by mtkennerly** [comment]
Thanks for bringing this up. PCGW's infobox template has a `steam appid side` field that we could start using to get secondary app IDs. I'll look into adding support for this in the next release.
