### ISSUE TITLE
Is there a way to exclude a filename from all backups?

### ISSUE THREAD

**Issue by TeamLinux01** [mtkennerly/ludusavi#228]
### What's your question?

I noticed that remotecache.vdf is included for some Steam Cloud backups, which seems to be a file steam uses to check when the save has changed.

Sometimes this file can be slightly different on several machines, which shows up as a delta change. I would prefer for it to be ignored.

Is there a way to globally exclude all remotecache.vdf files from all my backups, no matter the paths they are located?

**Comment by mtkennerly** [comment]
This isn't possible right now, since the backup exclusions (`backup.filter.ignoredPaths`) only consider full paths. I'll look into adding support for files/globs in the exclusions as well.

**Comment by TeamLinux01** [comment]
Thanks for considering it.

**Comment by mtkennerly** [comment]
In the next release, you'll be able to do this by specifying `**/remotecache.vdf` as a backup exclusion.
