### ISSUE TITLE
Mac version simply won't install

### ISSUE THREAD

**Issue by siainbuletin** [mtkennerly/ludusavi#229]
### Ludusavi version

v0.19.0

### Operating system

Mac

### Installation method

Standalone

### Description

Been trying to install this on my intel macintosh but it won't actually detect it as an application. Instead it shows up as an unreadable document. I tried installing Rust on my system, but no luck either.

**Comment by mtkennerly** [comment]
I think you just need to mark it as executable. Can you run `chmod +x ./ludusavi` and try again?
