### ISSUE TITLE
Shift+click for path selector dialogs with `<placeholders>` don't open

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#241]
### Ludusavi version

v0.20.0

### Operating system

Windows

### Installation method

Standalone

### Description

Shift+clicking the path selector icon for `<winDocuments>/TrackMania/Config` for example results in an "Unable to open directory" error.

I think this is limited only to custom games.

Thanks.

P.S. It could be useful to be able to copy / select pop-up error text.

**Comment by mtkennerly** [comment]
Thanks for reporting this! It won't be able to handle some like `<base>`, but I can definitely add support for the placeholders that have a single resolution.
