### ISSUE TITLE
Assassins Creed III Remastered, IV Black Flag and Rogue: savegames not detected

### ISSUE THREAD

**Issue by sysms** [mtkennerly/ludusavi#242]
### Ludusavi version

v0.20.0

### Operating system

Linux

### Installation method

Standalone

### Description

Dear developer,

the savegames for Assassins Creed III Remastered, AC IV Black Flag and AC Rogue are not detected by ludusavi and thus not saved.
Only the *.ini-files get saved.

I suspect, it's because these are Ubisoft Connect games installed via Steam on Linux with Proton.

I found a similar issue here, but it's closed as fixed: https://github.com/mtkennerly/ludusavi/issues/76

If I can provide anything more to help, please let me know!

**Comment by mtkennerly** [comment]
Hi! Thanks for reporting this. You're right that there's a gap here with the specific combination of Ubisoft Connect + Steam + Proton.

Using Black Flag as an example, PCGW says the saves should be in `<Ubisoft-Connect-folder>\savegames\<user-id>\437\` . Could you help find the equivalent of `<Ubisoft-Connect-folder>` inside of the game's Proton folder (`steamapps/compatdata/242050/pfx`)? Normally, it would be `C:\Program Files\Ubisoft\Ubisoft Game Launcher` (or the x86 version of Program Files).

Once we confirm its location, I can add some handling for it.

**Comment by sysms** [comment]
Hi, thanks for looking into this!

Sure - on my Installation of AC4 Black Flag the "Ubisoft Connect" installation resides in the Proton pfx at:

drive_c/Program\ Files\ \(x86\)/Ubisoft/Ubisoft\ Game\ Launcher/savegames/<user-id>/437/

Translating this to a Windows path, this would be

C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\<user-id>\437\

I've verified, that the same installation path is also correct for AC3 Remastered and AC Rogue.

So it seems, the only difference here is "Program Files (x86)" vs. "Program Files".

HTH!
