### ISSUE TITLE
Numerical directives for file and folder names (like ##) not backing up

### ISSUE THREAD

**Issue by instinctualjealousy** [mtkennerly/ludusavi#244]
### Ludusavi version

v0.20.0

### Operating system

Windows

### Installation method

Scoop

### Description

I've got Sonic Riders and Sonic Heroes set up with Ludusavi (via Playnite, but that shouldn't mean anything). The PCGW info, as well as the current manifest.yaml, correctly define the save and config locations for both games. However, at backup time, it doesn't actually find the specified and definitely existing save data.

I figure one example is plenty, Sonic Riders:
`<base>/Save/Game Data##/save.dat`

and its actual path on my system (formatted for consistency with the yaml):
`<base>/Save/Game Data01/save.dat`

The config backs up fine, so it is finding <base> without issue:
`<base>/Save/Config.ini`

I've made many user errors so far, so I didn't want to report an issue until I was pretty sure it was an actual issue. I think this is one. Data that should be matching isn't matching. It's also worth noting that Sonic Heroes' failed match is on a file instead of a folder, so this applies to both file and folder matches.

**Comment by mtkennerly** [comment]
Hi! Actually, Ludusavi doesn't support using `#` for numbers. [I updated the article](https://www.pcgamingwiki.com/w/index.php?title=Sonic_Riders&diff=1435089&oldid=1428143) to use glob syntax instead \:) PCGW doesn't enforce a specific wildcard standard, but `*` is quite common on the wiki, and I haven't gotten any opposition to switching `#`/`?` to `*` when I run into them.

> I've made many user errors so far, so I didn't want to report an issue until I was pretty sure it was an actual issue.

No worries! There's no harm in asking for help or clarification if you need it.
