### ISSUE TITLE
<storeUserId> adjacent to * glob breaks matching

### ISSUE THREAD

**Issue by instinctualjealousy** [mtkennerly/ludusavi#245]
### Ludusavi version

v0.20.0

### Operating system

Windows

### Installation method

Scoop

### Description

I noticed this with Need for Speed: Underground, and I believe the discussion I've associated below may have something to do with it. Underground's manifest entries utilize `<storeUserId>` (converted from `<user-id>`), which as you've stated, is simply interpreted as a `*` glob.

When backing the data up, it correctly matches `<winProgramData>/NFS Underground/Adam.cfg` from `<winProgramData>/NFS Underground/<storeUserId>.cfg`, which makes sense, given the conversion to `*.cfg` internally.

However, it does not match my file `<winProgramData>/NFS Underground/Adam0.ugd` from `<winProgramData>/NFS Underground/<storeUserId>*.ugd`. This may have something to do with it ending up with an internal value of `**.ugd`.

I've changed the entry on PCGW to make more sense (all `*.ugd` are saves, and I think it's not the best use of `<user-id>`- it's better suited to account ID than an internal game profile name), but this still brought up a very real issue in parsing.

>Right now, `<storeUserId>` is regrettably just interpreted as `*`, because I'm not sure if it's feasible to account for all possible ID patterns. For example, [one comment](https://github.com/mtkennerly/ludusavi/issues/39#issuecomment-815860719) in the other ticket noted that, within a Steam root, GTA 4 used some other pattern for its ID rather than a typical Steam pattern.

>Maybe we could have an option to enable stricter matching of known patterns, but there will be a risk of missing saves. For the default configuration, I think it's better to find too many files than too few, since at least it gives the user a chance to deselect them instead of miss them entirely.

>_Originally posted by @mtkennerly in https://github.com/mtkennerly/ludusavi/issues/236#issuecomment-1609731715_

**Comment by mtkennerly** [comment]
Good catch! It'll definitely need some special handling around that. Thanks \:D
