### ISSUE TITLE
Does not launch on Wayland unless forcing XWayland

### ISSUE THREAD

**Issue by VortexAcherontic** [mtkennerly/ludusavi#246]
### Ludusavi version

v0.20.0

### Operating system

Linux

### Installation method

Flatpak

### Description

Hello there just came across this little tool and was about to test it but I noticed without manual intervention the app does not start on my setup.
If not forced to run via XWayland using flatseal the app does not start.

OS: openSUSE Aeon
Kernel: 6.4.3-1-default
Desktop: Gnome 44.3
Display Server: Wayland 1.22.0
GPU Model: NVidia RTX 3080
Driver: 535.86.05
EGL: 1.22.0
NVidia EGL: 1.1.12

### Logs

gnome-shell[2089]: Invalid window geometry for xdg_surface@31. Ignoring for now, but this will result in client termination in the future.
gnome-shell[2089]: Invalid window geometry for xdg_surface@57. Ignoring for now, but this will result in client termination in the future.

**Comment by mtkennerly** [comment]
Hi! There have been a couple of other reports like this. It's hard to say exactly what causes it, but it does depend on the system. Most likely, it will be fixed when [Iced](https://github.com/iced-rs/iced) 0.10.0 comes out and Ludusavi is updated to use it. For reference:

* https://github.com/mtkennerly/ludusavi/issues/234
* https://github.com/flathub/com.github.mtkennerly.ludusavi/issues/24
