### ISSUE TITLE
Flatpak version doesn't check for saves in non-sandboxed folders with `$XDG_` paths (e.g. `$XDG_CONFIG_HOME`)

### ISSUE THREAD

**Issue by games647** [mtkennerly/ludusavi#249]
### Ludusavi version

v0.20.0

### Operating system

Linux

### Installation method

Flatpak

### Description

The Flatpak version doesn't appear to expand `<xdgConfig>` from save files to `/home/.../.config`. This means that a lot of save files are not found even though the Flatpak version has permissions to that files (i.e. `home` flag). Below is an example game configuration. The last path was added manually. Before that, data inside `/home/.../.config/War Thunder` were not found.

![War Thunder game configuration, with an additional entry that replaces <xdgConfig> with <home>/.config/ ](https://github.com/mtkennerly/ludusavi/assets/1957196/fe89bdff-52b4-45af-a4d9-168f56c73315)

This is only reproduced in the Flatpak variant not with the standalone version. Maybe this line is the source for that:

https://github.com/mtkennerly/ludusavi/blob/03f000679d505eab45036c8db084f19833b1be66/src/scan.rs#L350

**Comment by mtkennerly** [comment]
Thanks for reporting this!

Currently, it checks `$XDG_CONFIG_HOME` or, if that's not set, then `$HOME/.config`, but not both. In this context, `$XDG_CONFIG_HOME` is set to a Flatpak-specific location, so it takes precedence. It probably makes sense for Ludusavi to just check both paths proactively.

**Comment by games647** [comment]
BTW: This affects `.local/share/` (behind `$XDG_DATA_HOME`) as well. Example game is [Borderlands 2](https://www.pcgamingwiki.com/wiki/Borderlands_2#Configuration_file.28s.29_location)
