### ISSUE TITLE
[Feature Request] Sync Directory For Games Without Steam Cloud

### ISSUE THREAD

**Issue by seniorm0ment** [mtkennerly/ludusavi#251]
It would be really cool to have an option that simply enables a 2nd directory. It'd host all the saves for any games that don't have Steam Cloud. Then have it symlink to the games directory the save files.

This would allow the user to use any program, say Syncthing, to simply select that folder, and Sync all the games across different devices such as the Steam deck and PC and keep their saves up to date seamlessly. So users don't have to manually go in and find and choose a folder for every game for syncthing.

Note my suggestion does not imply "archiving" the saves there.
So you would still have Ludus's normal behavior of archiving up all the games to a folder. This would simply add a 2nd folder strictly for non cloud games that allow syncing (or it could be all saves it doesn't really matter I guess). This is important so it doesn't screw with save backups and risk corruption and what not. And any time these are updated, ideally the saves in the backup area are too.

I hope this makes sense. There might be a better way to do it. But the ability to sync games across devices without having to dig for the folder and manually go select it and put it in syncthing, then go link it on the other device manually, would be amazing. 
I wouldn't suggest Ludus as the actual sync program, but simply a central storage so the user can simply pick that folder that all the games are pointed at, and sync it.

**Comment by mtkennerly** [comment]
Thanks for this idea :) I'm not sure this quite fits the use case that Ludusavi is targeting, but you could leverage Ludusavi's CLI as part of a solution. Specifically, `ludusavi backup --preview --api` would give you the file paths, and then you'd just need to write a script to manage the symlinks.
