### ISSUE TITLE
Further improvements to the filters + some ideas

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#252]
### What's your idea?

I think it would be useful if the filter states for the _Backup/Restore Modes_ were remembered across each session of Ludusavi:

- Remember whether the filter (button) was enabled or not (red/blue) when quitting Ludusavi and restore state when running next time.
- Also remember the individual drop-down menu and checkbox states which the filter is comprised of. What wouldn't be remembered would be the search field's value.
- Perhaps make it an option whether or not to remember filter states across sessions (_Other_ tab).

I usually don't care about disabled games and so I hide them when things are cluttered. I must first enable the filter, then change the drop-down menu from _Disabled_ to _Enabled_, and finally click its checkbox. If the filter and its drop-down menu states were remembered, there'd be a lot of flexibility: Perhaps the filter is enabled but the checkbox is empty (just click the checkbox), or perhaps the checkbox is filled, but the whole filter isn't enabled (just click the filter button) -- both cases assume the drop-down box's value of _Enabled_ has been remembered from the previous session.

In addition to remembering states:

- A reset button to clear the filter: Search field and checkboxes, but without changing the drop-down values.
- There might be some sense in decoupling the search field (labelled _Filter_) from the filter itself. In one way, they do make sense to be coupled, but I think the benefit of the search field always being available, no matter the filter state, could be a plus. The filter button would then just reveal the extra filters (the checkboxes and drop-downs).
    - This would strike a balance of not eating up too much additional permanent screen space, whilst always having quick access to finding that one game you might've opened Ludusavi for. The sacrifice would be that if you filtered by a search term, you wouldn't be able to toggle that term from filtering via the filter button, but instead need to clear the field, however I don't see that as much of a loss due to it being unlikely that using the filter in this way has much practical benefit.
    - If the search field was decoupled from the filter and a reset button was also introduced, it would present the problem of there now needing to be two reset buttons, one for the search field, and one for the extras filters which I'm not initially liking the idea of. However, if the button for the search field is more of an "(x)" within the text field, and a "Reset" or "Clear" button for the drop-downs, it could work whilst not feeling too redundant. Not sure. I'd personally be fine with having the whole filter open at all times as I have the screen space for it, it does however look busier, but still quite understandable (only when the backup settings button is also enabled do the rows of options begin to get confusing).

Remembering of state and a way to clear the filters seem like good ideas. Maybe the decoupling of the search bar and the filter leads to having to rework too many little things when the filter remaining open across sessions is just a simple solution. 

As for when both the filter and settings rows of options are shown, something could be done to make each group of rows more distinct from one another:

![ludusavi_2023-08-11_00-40-16](https://github.com/mtkennerly/ludusavi/assets/25013746/c213db89-bb47-4733-b041-078d84259096)

For example, if the backup settings options (which are always the middle set of rows) had a light grey background to them, it'd be enough of a visual distinction to break up all three sections, e.g.:

![ludusavi-edit_2023-08-11_00-40-16](https://github.com/mtkennerly/ludusavi/assets/25013746/41b54229-9254-4be4-86e3-265d5d444d3f)

Thanks!

**Comment by mtkennerly** [comment]
Thanks for the suggestions :)

> I usually don't care about disabled games and so I hide them when things are cluttered. I must first enable the filter, then change the drop-down menu from Disabled to Enabled, and finally click its checkbox.

On the other screen, there's a "show deselected games" toggle, which is remembered between sessions. There are also similar toggles for unchanged and unscanned games. I imagined these as a subset of the filter functionality that would be more useful to keep between sessions, whereas we reset the filters since some combinations are only briefly useful (like "only show me disabled games that have no duplicates").

Beyond those three toggles on the other screen, are there other filter settings/combinations that you'd like to be able to persist?

> A reset button to clear the filter: Search field and checkboxes, but without changing the drop-down values.

I don't mind adding that. Just curious, would you still like this even if the filter isn't retained between sessions? I'm wondering how often you might need to clear the filter within a single session.

> As for when both the filter and settings rows of options are shown, something could be done to make each group of rows more distinct from one another:

Agreed, this could use some better styling :+1:

**Comment by redactedscribe** [comment]
> On the other screen, there's a "show deselected games" toggle, which is remembered between sessions. There are also similar toggles for unchanged and unscanned games. I imagined these as a subset of the filter functionality that would be more useful to keep between sessions, whereas we reset the filters since some combinations are only briefly useful (like "only show me disabled games that have no duplicates").

I should've been more observant. I can see that the _Other_ tab's options are tied to whether some of the drop-down filters are even visible. My first impression is that I'm not too fond of this approach, but I can see why you would've thought to tuck these options away. There are benefits, such as not necessarily even needing to open the filter to have some items always hidden, and that the option applies to both mode tabs, but I don't know if saving the vertical height taken by the filter is a good reason alone for having these options elsewhere (rather than a persistent filter).

Those options you point out don't necessarily negate a reason for the filter to function as I suggest. I could get used to it as it is, but my thinking was that having it all controlled via the tab you're on would be better since the visible state of the list is always reflected by the sticky filter at the top. I toggle the visibility of de-/selected items often enough that always going to another tab feels a bit clunky. if the drop-downs at minimum remembered their last value (not necessarily if the drop-down is enabled or not, just its selected value), then opening the filter and clicking the checkbox would still be quicker than three clicks going to the _Other_ tab and back. I guess I just prefer my approach, but it's kind of nitpicking at this stage since the end goal functionality is already implemented.

To summarise:

- I think the filter being open at all times wouldn't be a bad thing and instead a button to toggle whether any of it is filtering or not.
- Most devices probably have the screen space for it always visible.
- Being always visible gives quick access to the search field any why the list is or is not showing some items.
- Could be combined with the global overrides already present in the _Other_ tab.
- I'm fine with giving up on this idea if it's not worth the effort :)

> Beyond those three toggles on the other screen, are there other filter settings/combinations that you'd like to be able to persist?

Can't think of any at this time.

> I don't mind adding that. Just curious, would you still like this even if the filter isn't retained between sessions? I'm wondering how often you might need to clear the filter within a single session.

There's a bit of free space to the right of the drop-downs even at minimum window width, and maybe it's still worth it in a single session to save on some clicks, e.g. when wanting to clear the checkboxes just to set a single one or something.

Other feedback:

- Option in _Other_ tab is named _Show deselected games_, but the corresponding options in one of the drop-downs are _Enabled_/_Disabled_. Maybe one of these should be renamed, e.g. _Enabled_/_Disabled_ -> _Selected_/_Deselected_?

**Comment by mtkennerly** [comment]
I've made a few adjustments here:

* Moved the backup format/retention settings to the "other" screen to reduce clutter
* Changed "select all" to "enable all", "deselect all" to "deselect all" and "show deselected games"  to "show disabled games"
* Added button to reset filters
* Added background color to filters

For now, I think I'd rather not persist the filters or separate the title filter. I have some thoughts for #201 and #260 that may affect that behavior.

> https://github.com/user-attachments/assets/13183cbd-fe2c-4cf8-bd77-aef349787803
