### ISSUE TITLE
Purpose of Preview button for custom games not too helpful

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#258]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Scoop

### Description

Clicking _Preview_ for a custom game doesn't really preview anything. If even only _one_ entry is valid, we get "Save data found.", but if all are invalid, we get "No save data found.". To me this is more of a _Validate_ button than a preview button in its current state. When disabling a custom game and then clicking _Preview_, no feedback is given at all.

I'm not sure if this footer line of info is a bug because I don't recall this button's behaviour from the previous version (I would've thought _Preview_ would have at least shown a pop-up or something with all the items the defined paths contain, or maybe tick marks / crossed beside each path to indicate validity).

Thanks.

**Comment by mtkennerly** [comment]
There's definitely some room to improve the UX on this. It does generate a preview, but it's shown on the backup tab. Part of the idea is that you can add a custom game and use its scan button so it shows up in the main list without having to do a full scan just to make it show up. Displaying the results in a modal would probably be a good improvement.

> When disabling a custom game and then clicking Preview, no feedback is given at all.

Good catch! That part is definitely a bug.

**Comment by redactedscribe** [comment]
> Part of the idea is that you can add a custom game and use its scan button so it shows up in the main list without having to do a full scan just to make it show up.

Ah, yes. I remember reading or discussing something about this. It's not clear that this is happening though, so perhaps _Preview_ should jump to the game entry in _Backup Mode_ tab? I think that would be the most common case for pressing _Preview_ since that's its purpose. Then a modifier key could be used for _Preview_ to preview without jumping to the _Backup Mode_ tab (if wanting to click _Preview_ on several custom games). Just a thought.

> Displaying the results in a modal would probably be a good improvement.

This wouldn't be needed with what I've just outlined, but perhaps that's a good reason to see the results on the _Custom Games_ tab, I don't know.

**Comment by mtkennerly** [comment]
This will be in the next release:

> https://github.com/user-attachments/assets/7fdadd71-bed8-41f9-aa17-9851e128bca8
