### ISSUE TITLE
Navigating custom game entires between tabs

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#259]
### What's your idea?

With v0.21.0, we now have a "(CUSTOM)" badge next to custom entries in the _Backup Mode_ tab. This takes us to the same entry but on the _Custom Games_ tab, nice, but there is no way to traverse in the opposite direction. Some kind of button to to return back to the _Backup Mode_ tab revealing the custom game entry would be useful, particularly because custom games cannot be filtered at this time, and so finding custom games still requires scrolling up/down to find them (unless you're like me and have prepended all custom games with a special character to each to group them all at the top).

After a little brainstorming, here's an idea that could also influence #257:

Previewing requires Shift to be held for entries in the _Backup Mode_ tab. If the _Custom Games_ tab's Preview button was renamed "Validate" (for reasons in #257), then holding Shift in this tab could change the button's state to show "Preview" and do something more preview-y than it currently does (which would keep some consistency between tabs and what the modifier keys do). Depends on how you originally imagined previewing etc on the _Custom Games_ tab to work, I'm just looking in from the outside.

At the very least, if not a dedicated button to jump to the game over on the _Backup Mode_ tab, a modifier key to change the current Preview button to a go-to-in-backup-mode-tab button. Shift changes folder buttons into a go-to type button, so maybe Shift should also do the same for the Preview button too, instead of what I proposed above.

Thanks.

**Comment by mtkennerly** [comment]
I think this will be covered in v0.26.0 by the changes for https://github.com/mtkennerly/ludusavi/issues/258#issuecomment-2423164931. v0.25.0 also added the option to filter the backup list by custom games only.
