### ISSUE TITLE
How to use Ludusavi with Rclone Mount

### ISSUE THREAD

**Issue by utkarshdalal** [mtkennerly/ludusavi#263]
### What's your question?

I see the documentation says `If you use Rclone's mounting functionality, then you can configure Ludusavi to use the mount folder.`

How? I'm trying to do this and I don't understand.

**Comment by utkarshdalal** [comment]
Do I just need to make my backup folder a folder on the mount?

**Comment by mtkennerly** [comment]
> Do I just need to make my backup folder a folder on the mount?

Yeah, you can just change the path on the backup screen. I can edit that section to make it clearer.

**Comment by utkarshdalal** [comment]
Got it. Thank you, this worked 🙂
