### ISSUE TITLE
Redirect not working.

### ISSUE THREAD

**Issue by TeamLinux01** [mtkennerly/ludusavi#264]
I just tried out [Bazzite](https://universal-blue.org/blog/2023/08/20/bazzite-10/) and it has /home as a symbolic-link for /var/home. I did a redirect (bidirectional) of /var/home to /home, but it still wants to backup as /var/home.

It is using flatpak with version 0.21.

Thanks for any input.

**Comment by mtkennerly** [comment]
Thanks for reporting this! It looks like Ludusavi shouldn't re-normalize paths (which involves traversing symlinks) after applying the redirects. I'll look into fixing this, but it may take some time to figure out.

In the meantime, a workaround would be to make a bidirectional redirect with a dummy path that isn't symlinked, like mapping `/var/home` to `/home-bazzite`.

**Comment by mtkennerly** [comment]
@TeamLinux01 I have a build with a fix for this. Would you be able to test it out?

[ludusavi-v0.24.0-post.11+cc507f2-linux.zip](https://github.com/user-attachments/files/15829349/ludusavi-v0.24.0-post.11%2Bcc507f2-linux.zip)

**Comment by TeamLinux01** [comment]
I just tested it and it works correctly. Mapping `/var/home` to `/home` will result in the archive having a path of `drive-0/home/`.

Thank you.

**Comment by mtkennerly** [comment]
Awesome :) Thank you for testing!
