### ISSUE TITLE
Manifest Error

### ISSUE THREAD

**Issue by sunencheng** [mtkennerly/ludusavi#265]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Standalone

### Description

I downloaded the new version to replace the old one.Then start ,got this error.
Error:The manifest file is invalid.
while parsing a block mapping, did not find expected key at line 62029 column 1

I use VPN to download the manifest.(The only way.)

**Comment by mtkennerly** [comment]
Hi! The current manifest is working on my end. It sounds like you manually downloaded the manifest in a browser, right? Could you try downloading it again from https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml and double check?

**Comment by sunencheng** [comment]
> Hi! The current manifest is working on my end. It sounds like you manually downloaded the manifest in a browser, right? Could you try downloading it again from https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml and double check?

How could I use this file after i downloaded it?

**Comment by mtkennerly** [comment]
You can put it in `%APPDATA%\ludusavi` and replace the existing copy of manifest.yaml.

**Comment by sunencheng** [comment]
> You can put it in `%APPDATA%\ludusavi` and replace the existing copy of manifest.yaml.
Thanks a lot.

**Comment by mtkennerly** [comment]
No problem :)

I'm not sure why you ran into the original issue, but please do let me know if it happens again, and we can try to troubleshoot it further.
