### ISSUE TITLE
Games that have save files in directory with other game files have everything copied over

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#27]
Games that have save files in directory with other game files have everything copied over

Example game: [Iconoclasts](https://www.pcgamingwiki.com/wiki/Iconoclasts)

![imagen](https://user-images.githubusercontent.com/1389286/88864250-5d788580-d1ca-11ea-89a4-50cf4fe5d107.png)

Just those 3 files are save files.
![imagen](https://user-images.githubusercontent.com/1389286/88864225-4e91d300-d1ca-11ea-911f-3a651bf6b3f6.png)

All game files and folders get backed up:
![imagen](https://user-images.githubusercontent.com/1389286/88864329-9153ab00-d1ca-11ea-923d-1a94e4f6ac56.png)

I'm not sure if it's something that should be fixed on Ludosavi or PCGW side but I imagine there must be a lot of games that will have this issue.

Even if the entry was pointed directly in PCGW, it could be a problem that this game has a save file for each save slot, for example: `save1`.

**Comment by mtkennerly** [comment]
This would ultimately need to be narrowed down on PCGamingWiki. Ludusavi itself just uses whatever is in the [primary manifest](https://github.com/mtkennerly/ludusavi-manifest). In the manifest importer script, I preemptively filter out some paths as "too broad", like the game install directory itself and the user's home directory, but it's not a perfect system.

In accordance with PCGW, the manifest currently has these paths for Iconoclasts:

```
<base>/Contents/Resources/Data
<base>/data
```

So, for example, it won't back up anything from `steamapps/common/Iconoclasts/assets` (if such a folder exists) - only the `data` folder. Ideally, PCGW would specify `data/save*` and `data/settings`. PCGW allows you to specify multiple paths per platform (just add another `|` between the paths), and I've seen a precedent for using globs to match multiple files (which Ludusavi supports as well). If someone updates the wiki article, then the changes will be imported into the primary manifest before long (it's manual for now, but I plan to automate the import script once I'm confident enough in it), and the extraneous files won't be included anymore.

**Comment by darklinkpower** [comment]
Thanks for the quick reply. I asked in the PCGW discord and an editor told me this:
![imagen](https://user-images.githubusercontent.com/1389286/88867190-59e8fc80-d1d2-11ea-8a29-dec2b9613f9e.png)

https://www.pcgamingwiki.com/w/index.php?title=Cat_Quest_II&type=revision&diff=983549&oldid=980970

So using `{{code|*}}` is fine, although it seems there's still some discussion on the standard that should be used in the future.

![imagen](https://user-images.githubusercontent.com/1389286/88867546-60c43f00-d1d3-11ea-94b2-220b451a24ab.png)

And one last question, how often is the manifest file updated for ludavis? In any case, I'll try to update wiki entries for as many games as I can.

**Comment by mtkennerly** [comment]
When I asked on the wiki, some admins (I think) responded that `{{code}}` should not be used in the `Game data` template, only in inline text or prose: https://www.pcgamingwiki.com/wiki/Topic:Vq7f55yqvou5g8mx . I actually cleaned up some articles to remove it from `Game data` instances, but fortunately the importer script is able to handle it correctly as well (any `{{code|blah}}` is converted to `*` in a `Game data` path).

I also started a discussion thread about globs, but no one responded: https://www.pcgamingwiki.com/wiki/Topic:Vq7b1hakctr7scyh . Still, I made some edits to convert non-standard placeholders to globs, and no one seems to have objected yet.

Right now, I'm updating the manifest about every 3 to 5 days. There's just one issue (related to page redirects) that I need to fix before I can fully automate it, and then I'll probably set it up to run once every 24 hours.

**Comment by darklinkpower** [comment]
My bad, I confused the `{{code}}` that is this with the actual information in the game data.  The code was for this:
![imagen](https://user-images.githubusercontent.com/1389286/88868390-abdf5180-d1d5-11ea-9be0-35ed6b96fb72.png)

Just `*` is fine 
![imagen](https://user-images.githubusercontent.com/1389286/88868451-d5987880-d1d5-11ea-99b4-56093efa6a39.png)

Consider this issue solved.
