### ISSUE TITLE
Updating the icon

### ISSUE THREAD

**Issue by gfigueroap** [mtkennerly/ludusavi#272]
### What's your idea?

Its possible to modify the icon ever so slightly so that it could be replicated by just drawing dots on a grid and then combine dots to form lines.

The following image showcases the possible alternatives the icon could be modified to. While the second one is closer to the original, Im personally drawn to the first one. Let me know if this is an idea worth exploring, so i could work on their respective .kra or .svg files.

![ludusavi_icon_alternatives](https://github.com/mtkennerly/ludusavi/assets/75149324/bbc18725-52f8-4432-a903-ed37d7fe3e04)

**Comment by mtkennerly** [comment]
Hi! Sorry for the late reply. I like this idea :) I would prefer variant 2, since it's closer to the original and has a 10x10 grid.
