### ISSUE TITLE
Sync between Steam Deck - Windows

### ISSUE THREAD

**Issue by chema8132** [mtkennerly/ludusavi#273]
### What's your question?

Hi!

First I would like to congratulate the work put behind ludusavi, as its amazing how fast and flexible It is 💯 

As for my question, I'm currently setting up a gamesaves Sync scenario between my main Windows PC and Steam Deck, making use of Syncthing to maintain the coherence between both systems.

It is already working nicely, but I'm struggling with the redirects on the paths. My last and final goal would be backup/restore between the two systems while maintaining coherence. I've been playing with redirects, and I can backup/restore, but if I backup from Windows, then restore on Linux, Ludusavi instantly detects there are new files to be backed up for that one game on the Linux side, which makes It hard to detect real changes.

Is this achievable? Thanks!

**Comment by mtkennerly** [comment]
Hi! This is definitely a difficult problem to solve. You can theoretically do it with redirects, but it would require manual configuration for each game, and there are rough edges like you ran into. I'd recommend keeping an eye on https://github.com/mtkennerly/ludusavi/issues/194, which would make this a lot easier.

**Comment by chema8132** [comment]
Hi!

I see. I'll follow that enhancement.

Thanks a lot!
