### ISSUE TITLE
ludusavi kept getting stuck in a loop trying to scan something

### ISSUE THREAD

**Issue by Heus-Sueh** [mtkennerly/ludusavi#274]
### Ludusavi version

v0.21.0

### Operating system

Linux

### Installation method

Flatpak

### Description

ludusavi kept getting stuck in a loop trying to scan something
![image](https://github.com/mtkennerly/ludusavi/assets/98482469/157807d6-bf49-44cb-99b7-2f04335eaf94)

### Logs

[ludusavi_rCURRENT.log](https://github.com/mtkennerly/ludusavi/files/12716287/ludusavi_rCURRENT.log)

**Comment by mtkennerly** [comment]
This can happen if there is one game with significantly more save data than the others (e.g., 10+ GB for a single game), since the progress bar only updates per game rather than per file/byte. It should finish scanning eventually, but it could take a long time depending on the game and system. I'll look into better ways to represent progress in this kind of situation.

**Comment by mtkennerly** [comment]
I'm not sure, but the errors in your log might be a permissions issue with accessing `/var/home/heus/.var/app/com.usebottles.bottles`. The Flatpak version of Ludusavi now has broader permissions by default, so it should be able to read that path now. You can also use Flatseal to allow additional paths if needed.

If you still see this issue, could you try running with `--env=RUST_LOG=ludusavi=trace`? That way, the log file should indicate the last game being scanned that takes so much extra time.

**Comment by Heus-Sueh** [comment]
> I'm not sure, but the errors in your log might be a permissions issue with accessing `/var/home/heus/.var/app/com.usebottles.bottles`. The Flatpak version of Ludusavi now has broader permissions by default, so it should be able to read that path now. You can also use Flatseal to allow additional paths if needed.
> 
> If you still see this issue, could you try running with `--env=RUST_LOG=ludusavi=trace`? That way, the log file should indicate the last game being scanned that takes so much extra time.

I tried to create a backup recently and the bug no longer appeared
