### ISSUE TITLE
How do I restore a backup into another computer ?

### ISSUE THREAD

**Issue by raaffaaeell** [mtkennerly/ludusavi#276]
### What's your question?

What I'm facing is this. I have my main computer with some games installed with bottles, ludusavi can pickup these games and backup the save/config folders.

Then I wanted to restore these saves into my steamdeck, in the prefix where I have the game installed there, but ludusavi shows the path from the main computer, how would I go about this ?

**Comment by TeamLinux01** [comment]
You should add a redirect path in the config on the Steam Deck that points to the /home/deck location for the restore from the original computer's home path.

**Comment by raaffaaeell** [comment]
Oh my goodness, didnt even notice that, that's brilliant, thanks
