### ISSUE TITLE
Support for Legendary standalone?

### ISSUE THREAD

**Issue by Elaborendum** [mtkennerly/ludusavi#278]
### What's your question?

I'm using Legendary through Playnite instead of Heroic because there's no Heroic library plugin and so far it works fine like this. To my understanding I need to add the path where the game files are saved to roots, but due to my setup they are in their own folder with a custom name `C:\Users\Admin\Legendary-Games` and none of the presets seem to be working. Am I doing something wrong or is there no support for legendary on its own?

**Comment by mtkennerly** [comment]
This isn't supported at the moment, but I can look into it :)

**Comment by darklinkpower** [comment]
I would also really appreciate support for this as I'm in the same use case.
