### ISSUE TITLE
Steam Astro Colony not detecting?

### ISSUE THREAD

**Issue by Subtixx** [mtkennerly/ludusavi#279]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Standalone

### Description

Save games are: `%USERPROFILE%/AppData/Local/AstroColony/Saved/SaveGames/`

![image](https://github.com/mtkennerly/ludusavi/assets/20743379/a437cc7f-d1fd-4d53-9722-e895be01354f)

**Comment by mtkennerly** [comment]
Hi! Ludusavi ultimately sources information from [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Home), which doesn't currently have an article for Astro Colony. If you or anyone else creates the article and adds the save locations to it, then Ludusavi will automatically incorporate that data within a few hours :)
