### ISSUE TITLE
Xenia game saves 

### ISSUE THREAD

**Issue by Koriebonx98** [mtkennerly/ludusavi#281]
### What's your idea?

Says it in the name.

it would be good to have the playnite addon work with this so then playing a rom will back up and restore set rom data 

for now I’ve had to add each game separately 
E.g “d:/xenia/content/<skate 3 I’d>00001” 
Replace skate 3 id with acc game I’d number 

for me I’ve placed xenia and other emulators for playnite inside of a playnite portable folder set like
“D:/playnite os/emulation/emulators/xenia/xenia.exe”  xenia itself is portable

**Comment by mtkennerly** [comment]
Ludusavi won't directly support emulated games, but since you're using Playnite, I would recommend this approach:

* In Ludusavi, make a single custom entry with the same name as the platform from Playnite. This would probably include your whole `d:/xenia/content` folder.
* In the Playnite plugin settings, enable the `back up save data by platform name after playing non-PC games` option.

If the game has multiple platforms in Playnite, then the plugin will use the first one.

**Comment by Koriebonx98** [comment]
I did think this however Xenia’s content folder also includes dlcs and title updates so the overall size will become huge after time, 

for just game save data it would have to follow the rom data I provide above. So potentially for now have to do it manually, if I go through the pain Of setting the games up one by one is there a way you could convert into a public thing so then Xenia would be supported?

I have tried the second thing you suggested but didn’t do what I was hooking so manually setting up Xenia saves with the plugin does work

**Comment by mtkennerly** [comment]
> I did think this however Xenia’s content folder also includes dlcs and title updates so the overall size will become huge after time,

Gotcha. If the saves are always in a folder that ends with `00001`, then you could use a glob like `d:/xenia/content/*00001`, but I don't know how consistent it is.

> if I go through the pain Of setting the games up one by one is there a way you could convert into a public thing so then Xenia would be supported?

Yes, that just became possible with Ludusavi 0.22.0. You could host your own YAML manifest file (like in a simple GitHub repository) with something like:

```yaml
Insert Game Title Here:
  files:
    "<root>/content/12345678900001":
      tags:
        - save
```

Then in Ludusavi, on the "other" screen, you can add the URL to the additional manifest and add an `other`-type root for `d:/xenia`.

**Comment by Koriebonx98** [comment]
im pretty sure yuzu is similar too but its on smdc or nand, ill look into it but would be good if comunity came toggther and added full emu support
