### ISSUE TITLE
Ludusavi hangs seemingly forever during restore

### ISSUE THREAD

**Issue by HenrikPoulsen** [mtkennerly/ludusavi#284]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Standalone

### Description

When trying to restore a backup for a game that lives in C:\Program Files (x86) it hangs seemingly forever.
When checking the logs it's obviously a permission issue, but the GUI doesn't inform the user that anything is wrong.
And it tries 100 times per file, so if there's a lot of files there will be no response for a very long time.

Launching it with admin permissions resolved the issue.
Would be nice to get some kind of prompt to help avoid this issue.

### Logs

Access is denied. (os error 5)

**Comment by mtkennerly** [comment]
Thanks for reporting this. The retries were originally meant to help with duplicate backups causing files to be busy, but that's a relatively minor edge case and doesn't justify causing delays for other kinds of errors. I've removed the retry logic.
