### ISSUE TITLE
2 small quirks

### ISSUE THREAD

**Issue by Originalimoc** [mtkennerly/ludusavi#287]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Standalone

### Description

1\ Windows path, seems like / and \ both works and default backuped mapping.yaml is using / for Windows too and won't even load when you change to \\, but both redirect feature and custom game is /\ sensitive. One would not show another(in backup mode appears as new if backed up file or redirect is /).
2\ After restore needs to press preview again, or it'll keep the "new"/"updated" status hint in UI.

**Comment by Originalimoc** [comment]
Full scan/stats takes long. But stat known scanned/previewed files should be really fast(see the speed of Github Desktop)

**Comment by mtkennerly** [comment]
I've updated the title search to automatically focus after clicking the filter button.

I'm still not sure about the `/` vs `\` sensitivity from the initial post. If you can provide an example of how to reproduce the issue, then I'd be happy to investigate it.

For clearing the statuses after a scan, we can use this ticket: https://github.com/mtkennerly/ludusavi/issues/160
