### ISSUE TITLE
Redirect only works on "Back up" and "Bidirectional"

### ISSUE THREAD

**Issue by Originalimoc** [mtkennerly/ludusavi#288]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Standalone

### Description

If you choose "Restore" neither mode would recognize the redirection.

**Comment by Originalimoc** [comment]
Huh.....

My understanding is first redirect input is what's path actually on disk, second input is what's on the mapping.yaml, then configured accordingly and it works in Bidrectional mode I'm using because I sync accross 2 Win + 1 Linux.

This understanding to me is natural but seems, wrong?

**Comment by mtkennerly** [comment]
For a restore redirect:

* The first input is where it was originally backed up from
* The second input is where you'd like it to be restored to

There are some more notes and examples here: https://github.com/mtkennerly/ludusavi#redirects

**Comment by Originalimoc** [comment]
Then how can make sense of bidirectional when restore and backup both field mean different thing?

**Comment by mtkennerly** [comment]
* In backup mode, a bidirectional redirect behaves like a backup redirect, with the same field order.
* In restore mode, a bidirectional redirect behaves like a restore redirect, *with the fields reversed*.

In other words:

* Backup redirect: When we back up a file from [source], we back it up as if it were from [target] instead
* Restore redirect: When we restore a file that was backed up from [source], we restore it to [target] instead
* Bidirectional redirect:
  * When we back up a file from [source], we back it up as if it were from [target] instead
  * When we restore a file that was backed up from [target], we restore it to [source] instead

(`[source]` is the first field, and `[target]` is the second field)
