### ISSUE TITLE
A more human-friendly way to organize saves

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#29]
This is a follow-up to discussions in #16, #26, and #28. This could simplify the requirements for #25.

Right now, saves are organized like this, using Base64 for encoding:

```
the-backup-folder/
  MTAwMCBBbXBz/  # 1000 Amps
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTE=  # D:/Steam/steamapps/common/1000 Amps/save1
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTI=  # D:/Steam/steamapps/common/1000 Amps/save2
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2F2ZTM=  # D:/Steam/steamapps/common/1000 Amps/save3
    RDovU3RlYW0vc3RlYW1hcHBzL2NvbW1vbi8xMDAwIEFtcHMvc2V0dGluZ3M=  # D:/Steam/steamapps/common/1000 Amps/settings
  MS4uLiAyLi4uIDMuLi4gS0lDSyBJVCEgKERyb3AgVGhhdCBCZWF0IExpa2UgYW4gVWdseSBCYWJ5KQ==/  # 1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)
    other/
      registry.yaml
```

Each game can also have an `other` folder with a `registry.yaml` if it has any registry data to back up.

It would be nice to use something more human-friendly than Base64, but there are some challenges:

* How to represent drive letters (`C:`) and UNC path prefixes (local: `\\?\C:\`, remote: `\\shared_drive\`) in a safe, cross-platform way
* How to represent game names with special characters that aren't folder-safe (like `.hack//G.U.` and [`***`](https://www.pcgamingwiki.com/wiki/***))
* How to represent the full, original location of each file

The solution to the above points needs to be simple enough that you can write a script to do the restoration without depending on Ludusavi at all. The current Base64 approach allows that (just decode to get the original path, then copy), but at the cost of human-readability.

Here's a possible option, using Base64 just for the game name and path prefix, but otherwise storing things normally:

```
the-backup-folder/
  MTAwMCBBbXBz/  # 1000 Amps
    RDo=/  # D:
      Steam/
        steamapps/
          common/
            1000 Amps/
              save1
              save2
              save3
              settings
  MS4uLiAyLi4uIDMuLi4gS0lDSyBJVCEgKERyb3AgVGhhdCBCZWF0IExpa2UgYW4gVWdseSBCYWJ5KQ==/  # 1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)
    registry.yaml
```

An advantage of this is that, although Ludusavi uses UNC paths internally to avoid the legacy Windows path limits, each component of a UNC path still can't exceed 255 or so characters, so a very long original path might produce Base64 that's too long for a UNC path component.

A further step would be to only use Base64 for the game names when they aren't a valid folder name, but otherwise just store them normally. That creates a special case in the rules, which I think is a dealbreaker, but it would make a lot of cases friendlier. Ignoring the special case issue, there would need to be a super clear indicator for which style is in use, because some things that look human-readable could actually be valid Base64 too: `Whoopsie` = `Z\x1a(\xa6\xc8\x9e`.

**Comment by mtkennerly** [comment]
@darklinkpower, responding to [your comment](https://github.com/mtkennerly/ludusavi/issues/25#issuecomment-666761898):

I have some concerns with removing special characters from game names in order to generate a folder name:

* What do you do if there are no characters left? [`***`](https://www.pcgamingwiki.com/wiki/***) is 100% invalid as a folder name.
* What do you do if there's a collision? Let's say the person who made `***` decides to release `***?`.
* What do you do if you actually need to *add* characters? Let's say someone makes a game called `.` or `..` - you need at least 3 dots for it to be a valid folder name. (Windows Explorer won't let you create it, but you can do it from the console, and Windows itself will accept it.)

**Comment by mtkennerly** [comment]
Well, I've just realized that `/` is one of the possible characters in Base64, so we have a problem anyway ☹️  `???` will be encoded into Base64 as `Pz8/`. That means Base64 isn't technically safe to use either, although I think the situations where `/` can occur are relatively limited at least. Replacing `/` with another character would violate the Base64 standard, and switching to Base32 would surely make the file names too long for the UNC path limit on 255 characters per path component.

So that definitely changes my position here and escalates the need to change how Ludusavi handles this. I might need to handle drives/UNC prefixes closer to what I mentioned in https://github.com/mtkennerly/ludusavi/issues/16#issuecomment-656457972 after all. I'll need to think some more about this.

**Comment by darklinkpower** [comment]
You are right about that, what a difficult topic. Sadly those edge cases are what is pushing this problem.

> A further step would be to only use Base64 for the game names when they aren't a valid folder name, but otherwise just store them normally[...]

Sounds like the only sensible solution for user friendliness, although consistency would be sacrificed. Perhaps only do that when the game meets the edge cases you describe above? That way only very few cases would be affected, maybe even less than %0.01~

For example, there's [Root Double -Before Crime * After Days-](https://www.pcgamingwiki.com/wiki/Root_Double_-Before_Crime_*_After_Days-), which has a `*` in it's name. In my opinion, converting the whole game name and sacrifice human friendliness for one character in an already long game would be unnecessary and the full name without cuts could always be stored in a manifest file as I mention in #25

**Comment by mtkennerly** [comment]
I'm leaning toward something like this:

```
the-backup-folder/
  mapping.yaml
  1000 Amps/
    drive-2/
      Steam/
        steamapps/
          common/
            1000 Amps/
              save1
              save2
              save3
              settings
  1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)/
    registry.yaml
  Root Double -Before Crime _ After Days-:
    drive-1/
      example.txt
  ludusavi-renamed-1/
    drive-1/
      example.txt
```

where mapping.yaml would look like this:

```yaml
drives:
  drive-1: 'C:'
  drive-2: 'D:'
games:
  1000 Amps: 1000 Amps
  1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby): 1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)
  'Root Double -Before Crime * After Days-': 'Root Double -Before Crime _ After Days-'
  '***': ludusavi-renamed-1
```

The process would be:

* If it's safe to save the name as-is, do so
* If not, try replacing bad characters with underscores:
  * If it ends up as all underscores, then call it `ludusavi-renamed-1` and keep increasing the number
  * If it ends up as a folder already in use, then `ludusavi-renamed-1`
  * If it's not already in use, then save it with underscores

Ludusavi processes games mostly alphabetically, but it's concurrent, so the order isn't exact. There's a small chance that a collision could produce inconsistent results between backups (e.g., first time `***` is `ludusavi-renamed-1` and `???` is `ludusavi-renamed-2`, next time it's the other way around), but that won't break anything (just makes it harder to compare backups in the rare case that it happens) and is a manageable risk.

The main challenge will be reliably determining the drive mappings, especially UNC paths, but it should be doable. On Linux, perhaps it could use a special `drive-0` without a mapping since Linux doesn't have the same drives concept that Windows does. If the drive mapping only has to handle Windows, then that'll simplify how I have to determine the drive/prefix part.

**Comment by mtkennerly** [comment]
Based on further discussions, I'll use a separate mapping.yaml for each game. That way, there isn't a single point of failure if the file is deleted/corrupted, and you can move individual game backups around easily since they're independent from each other. The file would look like:

```yaml
name: 'Root Double -Before Crime * After Days-'
drives:
  drive-1: 'C:'
  drive-2: 'D:'
```

**Comment by mtkennerly** [comment]
This is now implemented. There are a few differences from what I described above:

* Drive folder on Linux and Mac is `drive-0`.
* Drive folders on Windows, in the common case, are `drive-C`, `drive-D`, etc. If we can't simplify it (e.g., remote UNC path), then we escape it the same way we do for game folders, so `\\remote` would be `drive-__remote`.
* In the event of a total rename, like the title `***`, only then do we use some Base64 (with `/` replaced by `_`); e.g., `ludusavi-renamed-Kioq`. I went with that instead of numbers so that it would be deterministic, and it's a really rare edge case anyway. You can rename it yourself if you want, and Ludusavi will use the new name, since all that really matters is mapping.yaml.
* I didn't bother handling what happens if two folders have the same name - they'll either fail or one game will "win". The reason I didn't bother at this time is because, out of all 42,495 games in the manifest right now, not a single pair can produce a conflict after escaping (which surprised me - I thought there'd be at least a few conflicts). You could force it to happen with custom games, but I doubt it'll happen unless someone does it deliberately. In the future, I'd like to add a warning in case it happens, though.

![ludusavi-readable-layout-3](https://user-images.githubusercontent.com/4934192/89104252-ec151e80-d3e5-11ea-871e-e7feeb5537e8.png)

**Comment by darklinkpower** [comment]
Just as a suggestion, I think it could be useful to store the date and time of the backup date inside this mapping file so Ludusavi or other tool that reads it can display that information too.

**Comment by mtkennerly** [comment]
That could be interesting, but it could also hurt the use case of comparing backups in a diff tool, since then every single folder would get flagged as having a difference:

> ![image](https://user-images.githubusercontent.com/4934192/89106586-19b79300-d3f9-11ea-8c6d-ba0e5a5d7e6e.png)

For now, I think tools that want to show the timestamp should just check the last modified time of mapping.yaml. It may not be 100% accurate in all cases, but it should be fairly reliable.
