### ISSUE TITLE
File picker not working with Wayland

### ISSUE THREAD

**Issue by bipox** [mtkennerly/ludusavi#290]
### Ludusavi version

v0.21.0

### Operating system

Linux

### Installation method

Flatpak

### Description

OS: tested on Fedora and Nobara (Fedora based)
DE: Gnome (Wayland)

Hi,

Ludusavi works for the most part, games get detected automatically and I can backup the files. 
But when I try to add games manually the file picker shows "unable to browse on your system"

starting ludusavi with `flatpak run --nosocket=fallback-x11 --socket=x11` fixes the issue, the file picker then works normally.

(disabling `socket=wayland` in Flatseal works too)

Thank you for making Ludusavi, it's really great!

**Comment by sluedecke** [comment]
On an OS = Arch Linux installation (no flatpack) with DE = gnome the file picker opens normally. 

```shell
$ echo $XDG_SESSION_TYPE 
wayland
```

but I get the same error when using a flatpack install.

**Comment by sluedecke** [comment]
This is an example for a flatpak install which apparently is able to use zenity (which is the only tool on my system, no kdialog here): https://github.com/fastrizwaan/WineZGUI

Maybe the flatpack parameters of ludusavi stop it from seeing zenity in `/usr/bin`?

**Comment by sluedecke** [comment]
After fiddling around with flatpak, I suggest to change the socket specification in the [flatpak manifest](https://github.com/flathub/com.github.mtkennerly.ludusavi/blob/master/com.github.mtkennerly.ludusavi.yaml):

```yaml
finish-args:
  - --socket=fallback-x11
```

to be `--socket=x11`

**Comment by mtkennerly** [comment]
Thanks for looking into this :) I've generated a test build with the `--socket=x11` change. Please give it a try and let me know if everything works:

```
flatpak install --user https://dl.flathub.org/build-repo/70244/com.github.mtkennerly.ludusavi.flatpakref
```

**Comment by sluedecke** [comment]
Works for me, thanks for fixing it.

**Comment by mtkennerly** [comment]
Great! I've published the fix for the regular Flatpak version as well now.

**Comment by bipox** [comment]
Awesome, thanks to the both of you
