### ISSUE TITLE
crash on startup: interface 'wl_surface' has no event 2

### ISSUE THREAD

**Issue by cndofx** [mtkennerly/ludusavi#294]
### Ludusavi version

v0.21.0

### Operating system

Linux

### Installation method

Other

### Description

arch linux hyprland
I get this error when trying to launch ludusavi. I've tried installing through cargo and cloning and building the repo, both with the same issue.

### Logs

interface 'wl_surface' has no event 2
warning: queue 0x7f6cfc000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@35 still attached
  zwp_primary_selection_device_manager_v1@28 still attached
  wl_data_device@34 still attached
  wl_seat@33 still attached
  wl_data_device_manager@32 still attached
  wl_registry@31 still attached
warning: queue 0x5555568878a0 destroyed while proxies still attached:
  zxdg_toplevel_decoration_v1@26 still attached
  wl_pointer@25 still attached
  wl_surface@24 still attached
  wl_shm_pool@21 still attached
  xdg_wm_base@20 still attached
  wl_surface@19 still attached
  wl_output@14 still attached
  wl_output@13 still attached
  xdg_activation_v1@12 still attached
  zwp_text_input_manager_v3@11 still attached
  zwp_relative_pointer_manager_v1@10 still attached
  zwp_pointer_constraints_v1@9 still attached
  zxdg_decoration_manager_v1@8 still attached
  wl_seat@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Comment by mtkennerly** [comment]
Hi! Could you try setting `WINIT_UNIX_BACKEND=x11` and/or `ICED_BACKEND=tiny-skia` in your environment variables? It's hard to say if this is an issue with your graphics drivers or with Ludusavi's graphics libraries, but those options may give you a workaround.

**Comment by cndofx** [comment]
`ICED_BACKEND=tiny-skia` doesn't seem to work, but `WINIT_UNIX_BACKEND=x11` does. I know you said it's hard to say if it's a problem with my drivers or with ludusavi, but does that new info tell you anything?

**Comment by mtkennerly** [comment]
I did some digging, and I think https://github.com/Smithay/client-toolkit/pull/406 may be relevant. I've pushed a `bugfix/wayland-startup` branch of Ludusavi that updates to a version of `smithay-client-toolkit` with that fix. Could you try building that branch and let me know if it works?

**Comment by cndofx** [comment]
`bugfix/wayland-startup` works great

**Comment by mtkennerly** [comment]
Nice! Thanks for confirming. I'll include that fix in the next release :)
