### ISSUE TITLE
Game Aliases in ludusavi

### ISSUE THREAD

**Issue by WisdomCode** [mtkennerly/ludusavi#296]
### What's your idea?

This Idea was already brought up in #189, but not continued by the issuer because it could be done in his game manager itself.
However, I came to this from **lutris**, with some games that are a bit obscure in their naming. Renaming them in the Interface, although technically working as a workaround (simply change the name in the yml accordingly), this seems unelegant to me.
For example, I like a game called "Rise of Legends", which is a spin-off from the predecessor "Rise of Nations". Due to its similarities, it is called "Rise of Nations: Rise of Legends" in the wiki. I find this name misleading and would like to keep a naming scheme in lutris that in doubt can differ from the one in the wiki.
I can think of scenarios where other, non-standardized installations, especially of old games may lead to similar results. The same goes for the HD Edition, GOTY, as well as obscurely long titles (like "Anno 1602: Creation of a New World").

**Solution:**
The Game aliases as proposed in #189 would be an ideal solution for this case: Providing the option for a mapping of names. For example:
```
"Age of Empires II HD": "Age of Empires II (2013)"
"Rise of Legends": "Rise of Nations: Rise of Legends"
```
This could make many custom game yml scenarios obsolete and ease the amount of manual configuration, especially if such a list would be crowdsourced and integrated the same way the wiki yml manifest is (although that definitely is beyond this request).

**(Current) Workaround:**
Make sure your game names match exactly the entries in the wiki. In the case of lutris, if you have to enter the name manually anyway, one could try to enter the correct ones recognized by the wiki here. 

Unfortunately, I am really not used to rust, so I can gladly help with testing, but not with coding.

**Comment by mtkennerly** [comment]
I'm open to adding this 👍
