### ISSUE TITLE
Ludusavi crashes immediately on startup

### ISSUE THREAD

**Issue by kekonn** [mtkennerly/ludusavi#297]
### Ludusavi version

v0.21.0

### Operating system

Linux

### Installation method

Other

### Description

After the latest update, when I open ludusavi, it crashes immediately after it shows the window. Logs attached. Ludusavi installed from the AUR.

### Logs

interface 'wl_surface' has no event 2
warning: queue 0x7f3e14000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@51 still attached
  zwp_primary_selection_device_manager_v1@47 still attached
  wl_data_device@50 still attached
  wl_seat@44 still attached
  wl_data_device_manager@36 still attached
  wl_registry@46 still attached
warning: queue 0x55ca19455dc0 destroyed while proxies still attached:
  xdg_wm_base@23 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Comment by mtkennerly** [comment]
Hi! This will be fixed in the next release. It was also reported here: https://github.com/mtkennerly/ludusavi/issues/294

In the meantime, you can work around it by setting `WINIT_UNIX_BACKEND=x11` in your environment variables.

**Comment by kekonn** [comment]
Yup, the env var fixed it!
