### ISSUE TITLE
Support for SMB file shares with Samba

### ISSUE THREAD

**Issue by publicarray** [mtkennerly/ludusavi#300]
### What's your idea?

Currently the export fails:
![image](https://github.com/mtkennerly/ludusavi/assets/5497998/80f98c7a-f9ea-4f13-8665-171ad796fb1b)

![image](https://github.com/mtkennerly/ludusavi/assets/5497998/b07dafb3-0e3a-4ab5-9afd-714818d854b0)

This is on a Manjaro GNOME edition system saving to a NAS

**Comment by mtkennerly** [comment]
Hi! I would suggest mounting the share and then referencing the mount point in Ludusavi. The Rclone integration does support SMB, but if you only want a remote copy, then I think mounting would be the best solution here.

**Comment by publicarray** [comment]
It is mounted on gvfs, but I know that you mean 'mount & ftab the folder directly' I think this more a compatibility issue with Nautilus and gvfs mounts and how it represents the filesystem.
