### ISSUE TITLE
Err value: BadDisplay in Manjaro Wayland with NVIDIA

### ISSUE THREAD

**Issue by Milor123** [mtkennerly/ludusavi#302]
### Ludusavi version

v0.22.0

### Operating system

Linux

### Installation method

Cargo, Standalone, Flatpak

### Description

The program stucks (freeze) at start

![image](https://github.com/mtkennerly/ludusavi/assets/14153649/701b2c25-b2db-4585-8ffe-b7ee86ea8dd8)

I try **cargo install and standalone** version but both shows the same issue

### Logs

```
❯ cd /home/noe/.cargo/bin
❯ ls
ludusavi
❯ ./ludusavi
thread 'main' panicked at /home/noe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/egl.rs:304:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue 0x5597f5f85ed0 destroyed while proxies still attached:
  xdg_wm_base@24 still attached
  zwp_text_input_manager_v3@15 still attached
  wl_output@14 still attached
  xdg_activation_v1@13 still attached
  wl_subcompositor@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  wl_seat@9 still attached
  wl_shm@8 still attached
  wp_fractional_scale_manager_v1@7 still attached
  wp_viewporter@6 still attached
  zxdg_decoration_manager_v1@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
```

Logs for flatpak

```
❯ flatpak run com.github.mtkennerly.ludusavi
F: Not sharing "/usr/share/applications" with sandbox: Path "/usr" is reserved by Flatpak
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadDisplay', /run/build/ludusavi/cargo/vendor/wgpu-hal-0.16.2/src/gles/egl.rs:304:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by mtkennerly** [comment]
Hi! Thanks for reporting this. Could you try setting `ICED_BACKEND=tiny-skia` in your environment variables to use the software renderer?

If there's a bug in wgpu-hal, then we may have to wait for the next Iced release to update its dependency.

**Comment by Milor123** [comment]
> Hi! Thanks for reporting this. Could you try setting `ICED_BACKEND=tiny-skia` in your environment variables to use the software renderer?
> 
> If there's a bug in wgpu-hal, then we may have to wait for the next Iced release to update its dependency.

Excelent using ICED_BACKEND=tiny-skia as env in wayland, it work for me, thank u very much
