### ISSUE TITLE
Batocera 38 Permission Denied when trying to backup

### ISSUE THREAD

**Issue by TeamLinux01** [mtkennerly/ludusavi#304]
### Ludusavi version

v0.22.0

### Operating system

Linux

### Installation method

Flatpak

### Description

Running installed flatpak on Batocera 38. Created a custom game of `_Batocera` that backs up `/userdata/saves/` and `/userdata/screenshots`.

Trying to backup to `/userdata/ludusavi-backup/_Batocera`, `/userdata/ludusavi-backup/` exists, but `_Batocera` does not.

Ran the command `flatpak override --filesystem=host com.github.mtkennerly.ludusavi`.

It detects the files to backup, but has a permission denied error when trying to write the backup.

Backup exclusions include:
`/etc/`, `/run/` and `/usr/`

**Comment by mtkennerly** [comment]
Hi! I'm not familiar with the Batocera distro, but to start:

* Does this also happen with the non-Flatpak version of Ludusavi?
* Could you upload your Ludusavi log file (if there is one)?
* Was Ludusable able to create `/userdata/ludusavi-backup`, or did you manually create that folder?

**Comment by TeamLinux01** [comment]
I was able to copy the non-flatpak version to the system and execute it, no errors and works as intended.
[ludusavi_rCURRENT.log](https://github.com/mtkennerly/ludusavi/files/13853854/ludusavi_rCURRENT.log)
I manually copied the `/userdata/ludusavi-backup` from my other systems.

It seems Batocera runs as the root user/group. Not sure if it is running flatpaks as a different user and maybe the reason it gets a permission denied.

I didn't even think about running the binary, as it doesn't have a normal package manager. Thanks for asking.

**Comment by mtkennerly** [comment]
Nice, so it's definitely something with Flatpak permissions. I found a couple of tickets that might be relevant:

* https://github.com/batocera-linux/batocera.linux/issues/5097
* https://github.com/batocera-linux/batocera.linux/issues/4351

If those don't help and you can't fix the permissions in Flatseal, then this may need a new bug report to Batocera.

**Comment by TeamLinux01** [comment]
I found a better way to run it on Batocera.

After downloading `ludusavi` from github, I put it in the `/userdata/roms/ports` folder and added:

`/userdata/roms/ports/ludusavi.sh`
```
/userdata/roms/ports/ludusavi
```

Configuration file is stored in `/userdata/system/.config/ludusavi/config.yaml`
Then it will show up under ports to be launched via EmulationStation.

The only down side is that I only know how to close the app via `Alt`+`F1`, as the exit button does not appear under the Other tab.

**Comment by mtkennerly** [comment]
If Ludusavi sees `/home/deck`, then the exit button will show up, so that would be a hacky solution for now. I should probably add a proper config option for it (or just make it always present).

**Comment by TeamLinux01** [comment]
Thanks for the info. I don't think people would mind if it just always shows the exit button, but that is my personal opinion.

In case anyone is wondering, the home for the user on Batocera is `/userdata/system`, so I moved my backup to `/userdata/system/ludusavi-backup`.
