### ISSUE TITLE
Interface too large/not scaled on Steam Deck

### ISSUE THREAD

**Issue by TeamLinux01** [mtkennerly/ludusavi#305]
### Ludusavi version

v0.22.0

### Operating system

Linux (Steam Deck)

### Installation method

Standalone

### Description

When running Ludusavi on the Steam Deck (LCD and OLED) from the compiled github release causes the interface to be very large and offscreen in Desktop mode.

The flatpak version does not have this issue and I have copied the same config.yaml to both versions.
![Screenshot_20240108_113741](https://github.com/mtkennerly/ludusavi/assets/43735175/42860412-03aa-40d9-9853-9b549ca41ca1)

**Comment by mtkennerly** [comment]
This is covered in the README, but you just need to set `WINIT_X11_SCALE_FACTOR=1` in your environment variables. The Flatpak install sets it automatically. For some reason, Winit calculates a bad scale factor by default on the Steam Deck.

**Comment by TeamLinux01** [comment]
I am sorry for not looking through the readme about this. Thank you.
