### ISSUE TITLE
Does the wrap command not support custom games?

### ISSUE THREAD

**Issue by Supergamer1337** [mtkennerly/ludusavi#312]
### What's your question?

Hi! I tried to use the `wrap` command to automatically backup save files for my emulated games when launching through Steam, however it always says "Ludusavi does not recognize this game". Is it supposed to act like that, or is it a bug?

**Comment by mtkennerly** [comment]
Hi! The `wrap` command does support custom games. Could you share how you've configured the Steam launch options, and could you confirm if the custom name in Ludusavi matches the Steam title exactly?

**Comment by Supergamer1337** [comment]
It actually managed to resolve itself after a bit of trial and error, it may have been me simply messing up the custom name, or something else. It is working now however! Should I close this issue, or leave it open so others can read in case they have the same question (because people tend not to look at closed issues)?

**Comment by mtkennerly** [comment]
I think we can close it for now. The next release will include an `--infer steam` option that will make this easier.

For now, in case anyone else runs into this, here's an example of how to configure this for Steam: https://github.com/mtkennerly/ludusavi/pull/235#issuecomment-1871795950
