### ISSUE TITLE
Can I set a custom name?

### ISSUE THREAD

**Issue by Joackk** [mtkennerly/ludusavi#315]
### What's your question?

I want to set the scanned game name to the name I'm used to. But with custom it turns into two pieces. Using an alias will result in the game not being found. How can I change the scanned game name

**Comment by mtkennerly** [comment]
Hi! This isn't possible right now. Ludusavi will always display the name from the manifest. The aliases can be used for CLI input, but they're not used for display purposes. The closest thing right now would be making a custom game that's the same as the standard game, and then disabling (unchecking) the standard game in the backup list, but the standard name will still show up in the list as a disabled entry.

I'm open to adding something to help with this, but I have some questions to get a better idea of your use case:

* Do you just care about the display name in the program, or do you also care about the folder name used for the backup?
* I can think of a few situations where you might want a rename. Which ones are you mainly interested in?
  * changing the sort order  (e.g., `The Elder Scrolls` -> `Elder Scrolls` or `Final Fantasy XV` -> `Final Fantasy 15`)
  * removing marks and taglines (e.g., `DARK SOULS™: REMASTERED` -> `Dark Souls`)
  * changing language (`Atelier Sophie` -> `ソフィーのアトリエ`)
  * using the original title of a game that was republished (`Star of Providence` -> `Monolith`)

**Comment by Joackk** [comment]
Yes, I tried to set a custom for him, but it caused me to have too many projects, which made him look a little confused, so I wondered if I could overwrite the original and keep it simple

- I want to change the name of the display. Not the backup folder name
- Mainly in terms of language, I use Chinese, and I do not know their English name very well, so it is easy for me to distinguish which game is backed up. So I wanted to give him familiar names to identify them

**Comment by Dr4w** [comment]
I'd like to add something regarding this issue. Having a different display name causes the playnite plugin to not be able to backup some games. As an example, to make it more clear, it cannot distinguish between the "Control" game and its Ultimate Edition, which is called "Control Ultimate Edition". Therefore, unless changing the name to the latter by creating a custom game, it won't be able to perform the automatic playnite backup. But changing the name will cause to have duplicates, one called "Control" and the other "Control Ultimate Edition".
So being able to only change the display name without having a duplicate would be nice. I don't think the folder name also needs to be changed, but it would be a nice addition.

**Comment by mtkennerly** [comment]
This will be available in the next release:

> https://github.com/mtkennerly/ludusavi/assets/4934192/ef26bfe4-cd80-4205-ae73-8d7a84fd709f
