### ISSUE TITLE
Central location for additional manifests

### ISSUE THREAD

**Issue by mattman107** [mtkennerly/ludusavi#319]
### What's your question?

Is there a one stop shop repo for additional manifests?

Since the feature was added in v0.22.0 I think it would be cool if we could make a repo specifically for custom manifests the community is thinking about if there isn't already one. Just as an example I know that emulated game saves seem to be a highly suggested feature. If we opened that up as a community effort in a single place I'd bet we could fill it out.

**Comment by mtkennerly** [comment]
I haven't seen any secondary manifests shared by the community yet. I'm not quite comfortable creating/managing such a repo myself, but I'd be happy to put some links in the README if anyone does make some.
