### ISSUE TITLE
My ludosavi app is crashing at startup

### ISSUE THREAD

**Issue by fantasygone** [mtkennerly/ludusavi#322]
### Ludusavi version

v0.22.0

### Operating system

Windows

### Installation method

Standalone

### Description

Hello

When I open the executable (with or without admin permissions) this screen appears
![image](https://github.com/mtkennerly/ludusavi/assets/104144029/fece1c7d-eb1e-43c2-a05a-c6b5f477c1ac)

Then it closes by itself

I tried redownloading the file, removing the folder in roaming but nothing changes

No logs are created

**Comment by fantasygone** [comment]
It still creates the folder when I click on save data when I close a game through Playnite but I can't open the executable by myself

**Comment by TariqMK** [comment]
I had the same issue and resolved it with updating my Graphics Drivers.

**Comment by fantasygone** [comment]
> I had the same issue and resolved it with updating my Graphics Drivers.

I don't seem to have any update available

**Comment by mtkennerly** [comment]
Hi! Could you try a few tests?

* Test 1: Open Command Prompt and run the following

  ```
  set LUDUSAVI_DEBUG=1
  set RUST_LOG=trace
  C:\path\to\ludusavi.exe
  ```

  After running that, please upload a copy of `%APPDATA%\ludusavi\ludusavi_rCURRENT.log`
* Test 2: Open Command Prompt and run the following

  ```
  set ICED_BACKEND=tiny-skia
  C:\path\to\ludusavi.exe
  ```

  Does the same issue happen?
* Test 3: Please try the latest development version of Ludusavi to see if the issue happens there too: [ludusavi-v0.22.0-win64.zip](https://github.com/mtkennerly/ludusavi/files/14641579/ludusavi-v0.22.0-win64.zip)

**Comment by fantasygone** [comment]
This is the log
[ludusavi_r2024-03-19_08-36-31.log](https://github.com/mtkennerly/ludusavi/files/14647779/ludusavi_r2024-03-19_08-36-31.log)

Test 2 seems to open the app now but only from the Terminal

Test 3 triggered my Windows Defender claiming the .exe is a Defense Evasion

**Comment by mtkennerly** [comment]
> Test 3 triggered my Windows Defender claiming the .exe is a Defense Evasion

For what it's worth, on [VirusTotal](https://www.virustotal.com/gui/file/9ddde28dcba8eb6515421a5ca174c8e3840d9ed9822b8a73f90689379b48693a?nocache=1), Microsoft Defender is the only negative  report, so it's definitely a false positive. That said, I'll see if I can do anything to avoid setting it off.

In the meantime, here's a way to get option 2 working without the terminal:

* In the Start Menu, type "Edit the system environment variables" and click on the result with that name
* Click the "Environment Variables..." button
* In the upper half, click the "New..." button
* Variable name: `ICED_BACKEND`, variable value: `tiny-skia`

**Comment by mtkennerly** [comment]
@fantasygone I believe I've fixed the false positive from Windows Defender. Could you give this another try? (Just remember to remove the `ICED_BACKEND` variable first, if you followed the steps in the above comment.)

Download: [ludusavi-v0.22.0-post.31+c79111b-win64.zip](https://github.com/mtkennerly/ludusavi/files/14657358/ludusavi-v0.22.0-post.31%2Bc79111b-win64.zip)

VirusTotal: https://www.virustotal.com/gui/file/8099c5a53eb471fb6ec1a5aaf7fb4b41cbedecf3a66c739cc69296233f6ba2f1?nocache=1

**Comment by fantasygone** [comment]
> @fantasygone I believe I've fixed the false positive from Windows Defender. Could you give this another try? (Just remember to remove the `ICED_BACKEND` variable first, if you followed the steps in the above comment.)
> 
> Download: [ludusavi-v0.22.0-post.31+c79111b-win64.zip](https://github.com/mtkennerly/ludusavi/files/14657358/ludusavi-v0.22.0-post.31%2Bc79111b-win64.zip)
> 
> VirusTotal: https://www.virustotal.com/gui/file/8099c5a53eb471fb6ec1a5aaf7fb4b41cbedecf3a66c739cc69296233f6ba2f1?nocache=1

Tested, this one crashes as well. Which is odd since the .exe was working fine last time I used it and I didn't even update or anything (It still was the latest version)
Something on my end probably changed that makes it crash but I have no idea what

**Comment by fantasygone** [comment]
If I may ask, what does that environment variable mean and why does changing it solve the issue at hand? Thank you

**Comment by mtkennerly** [comment]
By default, Ludusavi uses the GPU to render, and it relies on DirectX, Vulkan, or Metal, depending on your system. Setting `ICED_BACKEND=tiny-skia` makes it use software rendering instead.

**Comment by fantasygone** [comment]
So that implies there is an issue with my GPU

**Comment by fantasygone** [comment]
My AMD update came just now so that's why I didn't find it the other day, it's working as intended now

Thank you mtkennerly and TariqMK for your time

**Comment by fantasygone** [comment]
I don't understand. It's happening again

When I clean uninstall AMD drivers with DDU, I can start ludosavi correctly, but I don't think I should use my pc without drivers

The moment I install AMD drivers even with Windows updates disabled I come across the same issue, I have no idea what to do

Is my GPU broken or something?

**Comment by fantasygone** [comment]
> It sounds like an issue with specific driver versions. Which version do you have now, and do you remember which version worked a few weeks ago? Are these the generic AMD drivers or ones from your computer manufacturer?

24.3.1 is the latest I downloaded with AMD Software: Adrenaline Version

![image](https://github.com/mtkennerly/ludusavi/assets/104144029/5bebfc61-adb6-4c1d-9451-62e2c2d7586f)

I don't remember what version it was the other time

**Comment by fantasygone** [comment]
Downgrading to 23.12.1 doesn't work either.

I would throw AMD into a dumpster on fire if I could. So many issues for no reason

**Comment by mtkennerly** [comment]
> Is there a way to test with any other program to see if it's a case specific with ludosavi?

There are some other apps that use the same graphics library here: https://iced.rs/ . You could give some of those a try and see if they have the same issue.

If you don't mind installing [Git](https://git-scm.com/download/win) and [Rust](https://rustup.rs/), you can try some tests in Command Prompt to narrow it down at the library level:

## Iced
```
git clone https://github.com/iced-rs/iced.git
cd iced

# latest version
cargo run -p counter

# version used by next Ludusavi release
git checkout 0.12.1
cargo run -p counter

# version used by Ludusavi v0.22.0
git checkout 0.10.0
cargo run -p counter
```

### Output
![image](https://github.com/mtkennerly/ludusavi/assets/4934192/38de31e2-63b5-417f-8880-27a3f941180d)

## Wgpu
```
git clone https://github.com/gfx-rs/wgpu.git
cd wgpu

# latest version
cargo run --bin wgpu-examples cube

# version used by next Ludusavi release
git checkout v0.19.3
cargo run --bin wgpu-examples cube

# version used by Ludusavi v0.22.0
git checkout v0.16.3
cargo run --example cube
```

### Output
![image](https://github.com/mtkennerly/ludusavi/assets/4934192/ee6c3125-3b2d-48ee-879c-57afcf263059)

**Comment by fantasygone** [comment]
> ## Iced
> ```
> git clone https://github.com/iced-rs/iced.git
> cd iced
> 
> # latest version
> cargo run -p counter

I tried the Iced option before and after installing AMD drivers. Before it opens and I can see the buttons like in your screenshoot, I can increase and decrease the count.

After installing the drivers, however, I get the same white screen and crash.

This is the error
![image](https://github.com/mtkennerly/ludusavi/assets/104144029/7e2ce298-bb0d-49f2-8336-1f6098a5ee74)

Could this just be AMD not supporting this thing? Kind of sad if this is it. Yet another thing AMD can't do compared to NVIDIA. Ugh.

**Comment by mtkennerly** [comment]
> Could this just be AMD not supporting this thing?

I'm not sure :/ Driver issues can definitely be a pain to narrow down, and I'm not an expert in that area. For now,  keeping `ICED_BACKEND=tiny-skia` set is the best advice I can suggest.

**Comment by mtkennerly** [comment]
If the Wgpu examples don't work either, you could try reporting the issue at https://github.com/gfx-rs/wgpu/issues along with your driver info. Maybe they could help.

**Comment by fantasygone** [comment]
![image](https://github.com/mtkennerly/ludusavi/assets/104144029/c7becf6c-6389-4ad8-a851-ebf3ab2bcdc8)

Same result sadly

**Comment by mtkennerly** [comment]
I can try reporting this to Wgpu and see what they say. Could you just copy/paste the full output for this?

```
set RUST_BACKTRACE=full
cd wgpu
cargo run --bin wgpu-examples cube
```

**Comment by fantasygone** [comment]
C:\Users\user\wgpu>cargo run --bin wgpu-examples cube
    Finished dev [unoptimized + debuginfo] target(s) in 9.15s
     Running `target\debug\wgpu-examples.exe cube`
[2024-04-12T08:22:20Z INFO  wgpu_examples::framework] Initializing wgpu...
[2024-04-12T08:22:21Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Using ClearRenderTargetView on Command List (0x0000014DEC8C6DE0:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0xD84F1E90: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x0000014DEC8B6920:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0xD84F1E70: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0xD84F1E50: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
[2024-04-12T08:22:21Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "AMD Radeon(TM) Graphics", vendor: 4098, device: 5688, device_type: IntegratedGpu, driver: "AMD proprietary driver", driver_info: "24.3.1 (AMD proprietary shader compiler)", backend: Vulkan }
[2024-04-12T08:22:21Z INFO  wgpu_examples::framework] Using AMD Radeon(TM) Graphics (Vulkan)
[2024-04-12T08:22:21Z INFO  wgpu_examples::framework] Entering event loop...
[2024-04-12T08:22:21Z INFO  wgpu_examples::framework] Surface resume PhysicalSize { width: 800, height: 600 }
[2024-04-12T08:22:21Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 1422, height: 700 }
[2024-04-12T08:22:21Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 800, height: 600 }
[2024-04-12T08:22:21Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 800, height: 600 }
HookApp::findGameWindow, injectWindow: 0000000000000000
HookApp::findGameWindow, graphicsWindow: 00000000000F06A2
error: process didn't exit successfully: `target\debug\wgpu-examples.exe cube` (exit code: 0xc000041d)

**Comment by fantasygone** [comment]
I have something weird to report

I have found out that my GPU 0 is not being used:
![image](https://github.com/mtkennerly/ludusavi/assets/104144029/e941e977-d775-413a-b598-0691a7d2b6cb)
![image](https://github.com/mtkennerly/ludusavi/assets/104144029/62dce6a0-61a6-40ae-98d0-1538b5e021d5)

![image](https://github.com/mtkennerly/ludusavi/assets/104144029/88262b97-0844-4904-992d-1c9d4d243127)
Only the GPU 1 is in use, how did this happen? Is this the culprit?

**Comment by fantasygone** [comment]
![image](https://github.com/mtkennerly/ludusavi/assets/104144029/8a07305a-3d15-4df4-b5c2-fd3ebe5e7eec)
Doing this solved my issue (for now)

Before I close the issue once again how do I set the first GPU by default and why did it change?

**Comment by mtkennerly** [comment]
That's a good find!

> Before I close the issue once again how do I set the first GPU by default and why did it change?

I'm not sure. On my system, the top option is labeled `Let Windows decide (High performance)`, and I have the `Performance` power plan selected (Control Panel > Choose a power plan), but I don't know if those are directly related.

I would guess that a driver update and/or Windows update caused the preference to change by accident, but it's hard to say for sure.

**Comment by fantasygone** [comment]
Alright, thank you

May this thread help someone else with the same issue
