### ISSUE TITLE
Ludusavi flashes for a second but does not start

### ISSUE THREAD

**Issue by TariqMK** [mtkennerly/ludusavi#323]
### Ludusavi version

v0.22.0

### Operating system

Windows

### Installation method

Standalone

### Description

Every time I try to run the EXE, I get a flash of what I can only assume is the Ludusavi screen before it closes (it happens too fast to actually load anything, so I cant see what it is).

Sometimes I have to attempt to start the program 9-10 times before it actually opens.

This happens on both v0.21.0 and v0.22.0, whether normal or portable installation.

**Comment by TariqMK** [comment]
Update:

I resolved this by updating my AMD Drivers (also mentioned under troubleshooting: [https://github.com/mtkennerly/ludusavi/#configuration](https://github.com/mtkennerly/ludusavi/#configuration)

**Comment by fantasygone** [comment]
Does AMD adrenaline version opens for you?
