### ISSUE TITLE
Support for prism launcher

### ISSUE THREAD

**Issue by Alfredoes234** [mtkennerly/ludusavi#324]
### What's your idea?

Add support for prism launcher which runs multiple minecraft instances. With saving of the worlds. It uses the same file structure as normal minecraft but in file instances inside of prism launcher instead.

**Comment by mtkennerly** [comment]
You can add this on the custom games screen :)

Depending on the size of your Prism folder, the scan might be slower than usual, so just be aware of that. It's not as optimized as it could be for cases where a single game's saves are disproportionately larger than all others.

**Comment by Alfredoes234** [comment]
> You can add this on the custom games screen :)
> 
> Depending on the size of your Prism folder, the scan might be slower than usual, so just be aware of that. It's not as optimized as it could be for cases where a single game's saves are disproportionately larger than all others.

Would I have to explicitly do the paths then for each instance?

**Comment by Alfredoes234** [comment]
Or could I do something like prismlauncher/instances/*/.minecraft/saves

**Comment by mtkennerly** [comment]
> Or could I do something like prismlauncher/instances/*/.minecraft/saves

Yes, that will work! You can use [glob wildcards](https://en.wikipedia.org/wiki/Glob_(programming)) in the custom game entry.
