### ISSUE TITLE
The time of the archive header is different from the local time

### ISSUE THREAD

**Issue by Delta-R** [mtkennerly/ludusavi#327]
### Ludusavi version

v0.22.0

### Operating system

Windows

### Installation method

Standalone

### Description

Ludusavi's time in the filename of the game archive doesn't match the local time when it autosaves the game and is 8 hours different, hopefully this will be fixed!
<img width="526" alt="PixPin_2024-03-27_10-02-42" src="https://github.com/mtkennerly/ludusavi/assets/138836439/b8f45849-7779-4d88-a6a4-581321c98083">

**Comment by mtkennerly** [comment]
Hi! The zip filenames use UTC (indicated by the "Z" suffix). That's intentional to ensure consistent ordering of the files, even when you change time zones or experience daylight saving shifts. You can use the "date modified" column for the local time :)
