### ISSUE TITLE
FTL missing path

### ISSUE THREAD

**Issue by HugKitten** [mtkennerly/ludusavi#330]
### Ludusavi version

v0.22.0

### Operating system

Arch Linux

### Installation method

Flatpak

### Description

Not sure if its an issue on my end (might be), but it doesn't back up any files for (This is where FTL saves are stored when running in linux):
/home/user/var/app/com.valvesoftware.Steam/.local/share/FasterThanLight/

**Comment by mtkennerly** [comment]
Hi! Thanks for reporting this.

On PCGamingWiki, the Linux save path is listed as `$XDG_DATA_HOME/FasterThanLight`. Ludusavi will check your normal `$XDG_DATA_HOME`, but it doesn't currently know to check the Steam Flatpak equivalent of `$XDG_DATA_HOME`. I can look into adding support for that.

For now, you can make a custom game entry and add the missing path that way. As long as the custom game title matches the wiki page (`FTL: Faster Than Light`), it'll override the default entry.
