### ISSUE TITLE
Add `strip` to release binaries

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#338]
### What's your idea?

Not a big deal, but it reduces resulting file size of a release build on my Linux machine from 37M down to 25M by adding this to `Cargo.toml`:

```Cargo.toml
[profile.release]
strip = true # strip binaries to reduce their size
```

**Comment by mtkennerly** [comment]
Makes sense :+1: Rust recently [enabling stripping in release mode by default](https://github.com/rust-lang/cargo/issues/4122), but it's probably still good to specify it since the Flatpak builds can use a slightly older version.
