### ISSUE TITLE
Add a way to backup ludusavi settings

### ISSUE THREAD

**Issue by Alfredoes234** [mtkennerly/ludusavi#339]
### What's your idea?

Add some way to backup ludusavi settings because I feel this would help in a case where I setup on a new system.

Such as the custom games, it would be cool to have a way to back these up and restore. The configs for the paths and etc.

**Comment by mtkennerly** [comment]
Hi! You can back up Ludusavi's config folder. The paths for each OS are listed here: https://github.com/mtkennerly/ludusavi?tab=readme-ov-file#configuration

There's a separate ticket for specifically importing/exporting custom games: https://github.com/mtkennerly/ludusavi/issues/217

**Comment by Alfredoes234** [comment]
Ill vlose this then if it is a duplicate
