### ISSUE TITLE
GUI is not working

### ISSUE THREAD

**Issue by JuniorSum1** [mtkennerly/ludusavi#340]
### Ludusavi version

v0.23.0

### Operating system

Linux

### Installation method

Standalone

### Description

The tool does not work for the GUI. The CLI works just fine but the GUI doesn't. I have no idea whats causing this.

### Logs

wl_drm@50: error 0: wl_drm.create_prime_buffer is not implemented
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error warning: queue 0x5eaf99976be0 destroyed while proxies still attached:
0  wl_registry@53 still attached
 on object wl_drm@50: 
Protocol error thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:7240: on object 18wl_drm:
@Error in Surface::configure: Validation Error

Caused by:
    Surface does not support the adapter's queue family
50
: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50: 
Protocol error 0 on object wl_drm@50:

**Comment by mtkennerly** [comment]
Hi! This is probably a GPU/driver issue. Please try setting the `ICED_BACKEND` environment variable to `tiny-skia` to use the software renderer instead.

**Comment by JuniorSum1** [comment]
Thank for the quick reply. That worked I ran `ICED_BACKEND=tiny-skia ./ludusavi`. This problem is solved but do you know of a more permanent solution. Other than that thanks.

**Comment by mtkennerly** [comment]
I'm glad that helped :) Unfortunately, I don't know a solution to the underlying problem, especially since it may be hardware/driver-specific. In some cases, updating your graphics drivers may help.

**Comment by JuniorSum1** [comment]
Hi, I was thinking about this issue and tried starting a session on Xorg rather than Wayland which was what I used when the error occurred. Running Ludusavi on Xorg works fine but when I run Ludusavi on Wayland it will throw out that error. I believe that there is nothing wrong with my graphics or drivers. Does Ludusavi not have full support for Wayland?
