### ISSUE TITLE
Suggestion: Command to reformat backups to updated config

### ISSUE THREAD

**Issue by RuiNtD** [mtkennerly/ludusavi#342]
### What's your idea?

A CLI command (and possibly GUI option?) to update your backups to match your updated config with your selected format (simple / zip), compression method + level, and number of full + differential backups. In the CLI, there could also be flags to specify these settings (like you can do with the `backup` command), and the user could specify a specific game(s) instead of applying to all backups.

**Comment by RuiNtD** [comment]
If this was added to the GUI, it would probably make sense to put it into an "Advanced" tab.

**Comment by mtkennerly** [comment]
Hi! This is covered by #126, but I agree it would be a great feature :)
