### ISSUE TITLE
Emudeck Emulator Manifest

### ISSUE THREAD

**Issue by hblamo** [mtkennerly/ludusavi#344]
### What's your idea?

Could we add something like the following to find/track saves for emulators added by emudeck? 
I tested on my end and it seems to work (assuming I duplicate my SD card directory and set it as "home folder" ) 

[manifest.txt](https://github.com/mtkennerly/ludusavi/files/15380748/manifest.txt)

**Comment by mtkennerly** [comment]
Hi! You can absolutely put that into a GitHub repository if you'd like to make it available for others (they can add the GitHub file link in Ludusavi). I saw a repo for secondary manifests pop up recently if you want to try submitting it there: https://github.com/BloodShed-Oni/ludusavi-extra-manifests , or you could make your own repo if you like.

**Comment by hblamo** [comment]
Hello, done and done! 
Including the repo in case anyone needs it. 
https://github.com/hblamo/ludusavi-emudeck-manifest
