### ISSUE TITLE
Unrecognized game: `Return to the Obra Dinn`

### ISSUE THREAD

**Issue by mainrs** [mtkennerly/ludusavi#345]
### Ludusavi version

v0.23.0

### Operating system

Linux

### Installation method

Flatpak

### Description

I installed the game via Lutris. I used the `GOG (Auto) version`. The game natively only runs on Windows. The wiki has the entry correctly listed for Windows. However, the game is not picked up by ludusavi.

Roots:
```
/home/me/.local/share/Steam (Steam)
/home/me/.var/app/net.lutris.Lutris/data/lutris (Lutris)
```

The log file does not mention contain the words `obra dinn` at all. The game manifest of the game inside the Lutris config directory has a `slug`, `name` and `game_slug` property. The `prefix` property inside of `game` is missing. Is that the same problem as I had before in #309?

**Comment by mtkennerly** [comment]
> The `prefix` property inside of game is missing. Is that the same problem as I had before in https://github.com/mtkennerly/ludusavi/issues/309?

Yeah, this sounds like the same issue, unfortunately. Would you be able to check the Lutris `pga.db` to see which table/column has the prefix path (or email a copy to me and I can check: mtkennerly@gmail.com)? I'll see if I can work on #209 for the next release.

> The log file does not mention contain the words `obra dinn` at all.

You should see some if you turn on debug of trace logging: `RUST_LOG=ludusavi=trace ludusavi backup --preview "Return to the Obra Dinn"`

**Comment by mainrs** [comment]
The game is found, I get this output:

```console
$ flatpak run --env=RUST_LOG="ludusavi=trace" com.github.mtkennerly.ludusavi backup --preview "Return of the Obra Dinn"

Overall:
  Games: 0
  Size 0 B
  Location: /home/john/ludusavi-backup
```

The Lutris database does not contain any column with the name `prefix` or similar. Notable information I have found: 

- Table `games` contains columns `id` (autoincrement), `name`, `slug`, `installer_slug`, `platform`, `runner`, `executabe`, `directory`, `configpath`. non exhaustive.  `platform`=`Windows`, `runner`=`wine`, `directory`=`/home/john/Games/gog/return-of-the-obra-dinn` (the directory that contains the `.reg` files and the `c_drive` folder), `configpath`=`<path to the lutris game config file>`.
- Table `service_games` contains a row for the game as well. This holds the service's metadata I think. In this case, data fetched from GOG directly. It also has a `details` column that contains JSON (that's why I concluded that) and a `lutris_slug` column that references the `slug` under which the game is available in the `games` table.

The save files are under the same path inside the wine prefix as they are mentioned in the Windows section on pcgamingwiki: /drive_c/Users/john/AppData/LocalNow/3909/ObraDinn.

Do you need more information?

**Comment by mtkennerly** [comment]
Thanks! That's exactly what I needed :) Give me a few days, and I'll try to get a build for you to try out that will read the data from `pga.db`.

**Comment by mtkennerly** [comment]
I have a build ready for testing. Any feedback would be great:

* Build: [ludusavi-v0.23.0-post.18+f0a6767-linux.zip](https://github.com/user-attachments/files/15527849/ludusavi-v0.23.0-post.18%2Bf0a6767-linux.zip)
* [Changelog](https://github.com/mtkennerly/ludusavi/blob/f0a67673dc64a5a9976c656352a196db222ade9f/CHANGELOG.md#unreleased)

If you usually use Flatpak, just remember to pass the `--config` argument so it knows where to find your normal settings:

```
./ludusavi --config ~/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi
```

**Comment by mainrs** [comment]
Yup, both `Return of the Obra Dinn` and `Cult of the Lamb` are found.

**Comment by mtkennerly** [comment]
Nice, thanks for confirming! I'm hoping to make a new release within a week or so, which would include this.
