### ISSUE TITLE
Setup questions 

### ISSUE THREAD

**Issue by Dkassovic** [mtkennerly/ludusavi#346]
### What's your question?

Hello may be a dumb question but dose this program run automatically in the background always saving backups or do I need to run it every now and then would there be a way to always having it back up? Data 
And what’s the best way to save it to the cloud

**Comment by mtkennerly** [comment]
Hi! Ludusavi doesn't run automatically in the background on its own, but you can absolutely set up a recurring task that runs the Ludusavi command line interface. On Windows, you could use the built-in Task Scheduler app, and on Linux, you could use something like `cron` or `systemd`. You just need it to run `ludusavi backup --force` to do a full backup.

For cloud integration, there are a few options, and I'd recommend [reading this section of the docs](https://github.com/mtkennerly/ludusavi?tab=readme-ov-file#cloud-backup) if you haven't already. One option is to set Ludusavi's backup folder to somewhere that's already being synced to the cloud (e.g., if you have Google Drive or OneDrive set up on your computer). Another option is to use Ludusavi's integration with [Rclone](https://rclone.org/).

**Comment by mtkennerly** [comment]
I've added a short guide to setting up automatic backups: https://github.com/mtkennerly/ludusavi/blob/master/docs/help/backup-automation.md
