### ISSUE TITLE
Windows Defender detected a virus (Trojan:Win32/Bearfoos.B!ml) in the 64 bits package

### ISSUE THREAD

**Issue by herve-brun** [mtkennerly/ludusavi#350]
### Ludusavi version

v0.24.0

### Operating system

Windows

### Installation method

Standalone

### Description

Windows 11 Defender with the latest definitions detected Trojan:Win32/Bearfoos.B!ml in the executable file in the 64 bits windows zip file.

![windows defender - ludusavi](https://github.com/mtkennerly/ludusavi/assets/7703249/a3b3b58a-dec9-47fb-a23c-428f7df195a8)

**Comment by mtkennerly** [comment]
Thanks for reporting this. Unfortunately, I don't have any control over false positives like this :(

VirusTotal gives it a clean report:

https://www.virustotal.com/gui/url/977b8f1eddb2e30fe676b0fcd72041694e13c91d09cd376149758e9a96f3a416?nocache=1
