### ISSUE TITLE
Add `ignore game` feature to GUI

### ISSUE THREAD

**Issue by TeamLinux01** [mtkennerly/ludusavi#352]
### What's your idea?

It would be nice to manually add games to an ignore list, like how I can set it to ignore cloud save games.

The games I want to ignore are ones that don't actually keep a save, but just setting files, like Overwatch 2.

I don't mind if it it is part of the drop-down list of the game or part of the options page.

Do you think this would be useful to include or just a nice to have on a rare occasion?

**Comment by mtkennerly** [comment]
You can get close right now by making a custom entry for Overwatch 2 and just deleting all the save paths 😄 It'll still find Steam screenshots, though, if you have that option enabled. Is that enough for your case?

**Comment by TeamLinux01** [comment]
That would work, thanks
