### ISSUE TITLE
Use environment variables instead of hard coded paths

### ISSUE THREAD

**Issue by ZzzZeta** [mtkennerly/ludusavi#357]
### What's your idea?

The current backup saves hard coded paths in `mapping.yaml`, for example

`C:/Users/ZzzZeta/AppData/Roaming/Bioshock/User.ini`

Can it be changed to:

`%APPDATA%/Bioshock/User.ini`

so it can be restored to different user profiles?

**Comment by mtkennerly** [comment]
Hi! It's possible to do this using redirects.

* If you want all new backups to use a unified user folder (but still restore to your current system's username):
  > ![image](https://github.com/mtkennerly/ludusavi/assets/4934192/05778834-9bbe-463e-b57d-7e39941fee53)
* If you already have some backups using `ZzzZeta` and you want to restore them to a different user:
  > ![image](https://github.com/mtkennerly/ludusavi/assets/4934192/da169bda-a595-441f-ada1-9692c32d4713)

However, I don't plan to make this a default behavior of Ludusavi. There was some prior discussion in #156, but essentially:

* Ludusavi wants to guarantee (by default) that any given backup will restore to exactly its original location on the same system.
* What if you set Ludusavi to back up data from multiple user accounts? We could pick a main username that gets a path variable and use the absolute path for other usernames, but then the content of the backup changes based on the active user account.
* What if you set up automated backups using a service account? The main username would be the service account, so the backup content would always be different than when you run Ludusavi manually in your regular account.
* On Linux, Flatpak overrides the `XDG` environment variables (`$XDG_CONFIG_HOME` is like `%APPDATA%`), so a standalone copy of Ludusavi would start producing different backups than the Flatpak version, even when you run it using the same user account.

**Comment by ZzzZeta** [comment]
Thanks!
