### ISSUE TITLE
macOS: Program crashes on clicking "select directory" button

### ISSUE THREAD

**Issue by benorei** [mtkennerly/ludusavi#363]
### Ludusavi version

v0.24.2

### Operating system

Mac

### Installation method

Standalone

### Description

Whenever the folder button / "select directory" button is clicked, the application crashes.

### Logs

https://github.com/mtkennerly/ludusavi/assets/43426819/15a0d1ce-e58c-4c24-83a4-33581ed862d0

**Comment by mtkennerly** [comment]
Thanks for reporting this! Here's a version you can use with a fix, until I publish a new release:

> [ludusavi-v0.24.2-post.2+30f6308-mac.zip](https://github.com/user-attachments/files/16043015/ludusavi-v0.24.2-post.2%2B30f6308-mac.zip)

**Comment by mtkennerly** [comment]
I've just released the fix for this in v0.24.3 :)
