### ISSUE TITLE
Suggestion: Steam Cloud downloads

### ISSUE THREAD

**Issue by FenixR** [mtkennerly/ludusavi#366]
### What's your idea?

I'm sure it might not be possible or complicated to implement depending on permissions, but think you can do something to log in into a steam account and download to backup the cloud saves?

Recently i lost some saves from a game because it was stored in the install folder, so when i reinstalled the game (after completely deleting the game folder) i had a "Cloud Save Sync error" but instead of giving me a choice it went ahead and overwrote the steam cloud effectively making me lose all the saves.

Downloading stuff from the cloud into local storage would give you a chance to restore any mistakes made by the cloud sync in the worst scenarios.

**Comment by mtkennerly** [comment]
Hi! There's another ticket about this idea: https://github.com/mtkennerly/ludusavi/issues/99 (I can't promise when/if I'll work on it, but I'm still open to looking into it)

In the meantime, there are some other tools out there that may help, although I haven't tried them:

* https://github.com/pyscsd/steamCloudSaveDownloader - looks to still be maintained
* https://github.com/GMMan/SteamCloudFileManagerLite - last updated 9 years ago

There's also an official Steam page where you can download saves manually in a pinch:

* https://store.steampowered.com/account/remotestorage
