### ISSUE TITLE
Immediate crash when starting ludusavi

### ISSUE THREAD

**Issue by mainrs** [mtkennerly/ludusavi#369]
### Ludusavi version

v0.24.3

### Operating system

OS: CachyOS Linux x86_64
Kernel: Linux, 6.9.9-2-cachyos
DE: LXQt 2.0.0
WM: Openbox (X11)

### Installation method

Other

### Description

I install via AUR:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ludusavi

### Logs

```console
$ ludusavi

thread 'main' panicked at /home/me/.cache/yay/ludusavi/src/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:1208:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/me/.cache/yay/ludusavi/src/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/window.rs:601:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5c23a3ac3d19 - <unknown>
   1:     0x5c23a3af3dbb - <unknown>
   2:     0x5c23a3abf8ff - <unknown>
   3:     0x5c23a3ac3aee - <unknown>
   4:     0x5c23a3ac4f89 - <unknown>
   5:     0x5c23a3ac4ccd - <unknown>
   6:     0x5c23a3ac5413 - <unknown>
   7:     0x5c23a3ac52f4 - <unknown>
   8:     0x5c23a3ac4209 - <unknown>
   9:     0x5c23a3ac5027 - <unknown>
  10:     0x5c23a294cde3 - <unknown>
  11:     0x5c23a294d276 - <unknown>
  12:     0x5c23a347082a - <unknown>
  13:     0x5c23a3430bdc - <unknown>
  14:     0x5c23a2cf2794 - <unknown>
  15:     0x5c23a2cd7984 - <unknown>
  16:     0x5c23a2d462cb - <unknown>
  17:     0x5c23a2cd0cf4 - <unknown>
  18:     0x5c23a2c73b12 - <unknown>
  19:     0x5c23a2d12eb6 - <unknown>
  20:     0x5c23a2accf33 - <unknown>
  21:     0x5c23a2b775b9 - <unknown>
  22:     0x5c23a3ab5246 - <unknown>
  23:     0x5c23a2d16825 - <unknown>
  24:     0x7226369b1f8e - <unknown>
  25:     0x7226369b204a - __libc_start_main
  26:     0x5c23a294d735 - <unknown>
  27:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:228:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
```

**Comment by mtkennerly** [comment]
Hi! Could you try running with `ICED_BACKEND=tiny-skia` set in your environment variables? That will activate the software renderer, which may help.

Also, I don't maintain the AUR version. Just to test, could you try a standalone copy from the [releases page](https://github.com/mtkennerly/ludusavi/releases) and confirm if it has the same issue?

**Comment by mainrs** [comment]
> Hi! Could you try running with `ICED_BACKEND=tiny-skia` set in your environment variables? That will activate the software renderer, which may help.
> 
> Also, I don't maintain the AUR version. Just to test, could you try a standalone copy from the [releases page](https://github.com/mtkennerly/ludusavi/releases) and confirm if it has the same issue?

The flag did the trick. Not sure why this happens, as I have Vulkan installed and working, too. The release binary exhibits the same issue. The AUR package is compiled from source.

**Comment by mtkennerly** [comment]
The graphics layer can definitely be finicky on some systems - could be some combination of driver issues or bugs in the underlying Rust libraries. Unfortunately, I don't have any better advice than to use the software renderer for now if you're on an affected system 😞

**Comment by mainrs** [comment]
Good enough for me right now. I'm just surprised, since I ca run games via Vulkan :D
I tried digging into the issue in the underlying `winit` crate. I only found this comment that showed the same error message.

Does this apply to ludusavi? https://github.com/rust-windowing/winit/issues/1210#issuecomment-552163730

**Comment by mtkennerly** [comment]
Ludusavi doesn't have a full screen mode, so I'm not sure if that would apply, but if it can happen just by some other application being in full screen like the title says, then that might be related.

If you have Rust, you could try running some of the Winit examples to see if they work on your system:

```
git clone git@github.com:rust-windowing/winit.git
cd winit
cargo run --example window

git checkout v0.29.15
cargo run --example window
```

**Comment by mainrs** [comment]
Just some last information for people stumbling upon this. I did not run anything in full screen mode when this crash happened. 

Maybe it's related to LXQt (DE).
