### ISSUE TITLE
Redirect Back Up for Steam Deck to Match PC

### ISSUE THREAD

**Issue by HatSquid** [mtkennerly/ludusavi#371]
### What's your question?

I got this program to help with syncing Steam between my PC and Steam Deck with games that don't have Cloud, but I want it so when I back up my save on my steam deck, it will make the same directory as my PC, so I don't have to deal with two different folders leading to different directories. Dose anybody know how to achieve this?

**Comment by mtkennerly** [comment]
Hi! That's not possible right now (unless you manually configure a ton of redirects), but I'd like to support it in the future. You can track this ticket for updates: https://github.com/mtkennerly/ludusavi/issues/194
