### ISSUE TITLE
Cross platform restore functionality

### ISSUE THREAD

**Issue by MRDGH2821** [mtkennerly/ludusavi#373]
### What's your idea?

I have a linux tablet and a windows desktop.
That tablet has a game called [Symmetry](https://www.gog.com/en/game/symmetry) installed via Lutris.
I backed up the game save via Ludusavi, since the tablet was low spec.

Now I want to play on my high windows desktop.
Ludusavi saves were brought via cloud, and I tried restoring but ludusavi fails to do so.
This is primarily because of paths differing between linux & windows ofcourse. 
But there is no way to edit those paths OR provide windows path along with linux (lutris) path

Can we have something like having multiple path data, so that ludusavi can also restore game saves in cross platform manner?

**Comment by mtkennerly** [comment]
Hi! This isn't possible right now, unfortunately, but there's another ticket that you can follow for futures updates: https://github.com/mtkennerly/ludusavi/issues/194
