### ISSUE TITLE
Flatpak does not find all games in second steam library

### ISSUE THREAD

**Issue by processor286** [mtkennerly/ludusavi#374]
### Ludusavi version

v0.24.3

### Operating system

Linux

### Installation method

Flatpak

### Description

I have a steam lib in my home directory, and one on a drive mounted to /steamLibrary

ludusavi flatpack detected all the games in my home library and only one in the additional library. I could understand if it was all of them, or none of them. But one is strange.

I used the standalone version instead and this detected all games (I added the second library as a steam path in 'other' in both cases).

I'm happy to use the standalone one, but I thought I'd raise the issue for the flatpack one as I did spend a bit of time attempting to make it work before trying standalone.

**Comment by mtkennerly** [comment]
Hi! Have you added `/steamLibrary` to Ludusavi's Flatpak permissions? The permissions are limited by default, so you may just need to use Flatseal to allow some more paths. These are the defaults:

https://github.com/flathub/com.github.mtkennerly.ludusavi/blob/f290827796733a3c0a5a38ea56d045e804157ef9/com.github.mtkennerly.ludusavi.yaml#L16-L26

For the one game that Ludusavi found from the secondary library, which files did it find for that game? I'm wondering if the save files themselves are somewhere like your user home folder, where Ludusavi has permission, even though the game itself is in `/steamLibrary`.
