### ISSUE TITLE
RESTORE fails when username is changed.

### ISSUE THREAD

**Issue by spacefractaldk** [mtkennerly/ludusavi#376]
### Ludusavi version

v0.24.3

### Operating system

Windows

### Installation method

Standalone

### Description

You cant restore any games if username has been changed between a install. On Windows 11 example, you cant select the path required, so if username is changed from previous install. Most save games will fails to restore.

**Comment by mtkennerly** [comment]
Hi! You can use the [redirect feature](https://github.com/mtkennerly/ludusavi/blob/master/docs/help/redirects.md) for this. For example:

> ![image](https://github.com/user-attachments/assets/381ea125-4882-461a-9af7-5d76e4432f5e)
