### ISSUE TITLE
Hide/Ignore game list

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#38]
Since Ludusavi checks for all matching directories in the manifest for all games, there can be issues in certain game entries that have general locations for save files. For example: [The Next Penelope](https://www.pcgamingwiki.com/wiki/The_Next_Penelope)

This is a game I've never played but since I have the directory listed in PCGW, it detects the save files.

![imagen](https://user-images.githubusercontent.com/1389286/90110940-90b32c80-dd13-11ea-959b-35d65d14c222.png)

Although it wouldn't be much of an issue, since the location is not specific, it tries to backup a lot of files.
![imagen](https://user-images.githubusercontent.com/1389286/90110805-68c3c900-dd13-11ea-8726-36a436e93258.png)

The problem could be solved for this specific game by correcting the entry, but that's only possible if you own the game and can check. Another option is deselecting, but you'd have to do this each time you press select all and it's possible that you can forget to do it. I think adding an ignore list for games could solve this and other games that can have this issue in the future.

**Comment by mtkennerly** [comment]
This is actually possible by creating a custom game with the same name and just not specifying any paths. That will override the normal entry so that it can't find anything. I can add a note to the documentation about using custom games for that specific purpose.

**Comment by darklinkpower** [comment]
How about adding an override button that promts for this in the game list? I think it can be useful for this and other cases:

1.  In case the user setup for the specific games has more files than the ones normally found. For example, if the user uses a mod for the game that uses other config/save files.
2. Maybe the user wants to backup anything else with the game
3. In case the game has wrong/innacurate information and the user updates the information in PCGW, the user wouldn't have to wait for the manifest to update.

**Comment by mtkennerly** [comment]
Yeah, that's a good idea. It could pre-fill the existing info, rather than making you fill out the entry from scratch.

**Comment by mtkennerly** [comment]
Demo:

![quick-customize](https://user-images.githubusercontent.com/4934192/90322096-10144c00-df1e-11ea-9385-67c5332b3730.gif)
