### ISSUE TITLE
Scan retroarch save states and saves by default

### ISSUE THREAD

**Issue by davidfrickert** [mtkennerly/ludusavi#380]
### What's your idea?

Would it be possible to also scan retroarch for save states and saves and backup these?

**Comment by davidfrickert** [comment]
These can be found in the retroarch folder:
`.config/retroarch` if installed on the system or
`.var/app/org.libretro.RetroArch/config/retroarch` if installated via flatpak

then, `saves` and `states` folders could be scanned and backed up

**Comment by mtkennerly** [comment]
Closing for now since this would be a wiki change. Let me know if you can confirm the paths above.
