### ISSUE TITLE
Input/output error when trying to backup

### ISSUE THREAD

**Issue by that404nerd** [mtkennerly/ludusavi#383]
### Ludusavi version

v0.25.0

### Operating system

Linux

### Installation method

Standalone

### Description

As the title mentions when i tried to backup my game saves using ludusavi, it simply gave me that error message.I ran `ludusavi backup` from the terminal after it failed to backup from the GUI. I actually had the save files for the games before but in different paths, i created custom game saves from the same games again in ludusavi. I removed both the local and cloud folders and created different folders and set those in ludusavi. Here is the error message i get when i click backup:
![image](https://github.com/user-attachments/assets/572764e9-dba2-4e48-86f9-57b1f7f1a5d0)

And i doubled checked the paths and permissions, since the files are on my external drive. Any help is greatly appreciated! Thanks!

### Logs

[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/16828753/ludusavi_rCURRENT.log)

**Comment by mtkennerly** [comment]
Hi! I'm not sure what's causing that error specifically. Some questions for you:

* I see the error only happens with three games: GTA IV, ULTRAKILL, and Turbo Overkill. Are you able to back up any other games successfully?
* How much space is available on your main internal drive?
* What file system format do your internal and external drives use?

**Comment by that404nerd** [comment]
> Hi! I'm not sure what's causing that error specifically. Some questions for you:
> 
> * I see the error only happens with three games: GTA IV, ULTRAKILL, and Turbo Overkill. Are you able to back up any other games successfully?
> * How much space is available on your main internal drive?
> * What file system format do your internal and external drives use?
> 

Hi! Thanks for responding. And no, I haven't been able to backup the other game (GTA5). My internal drive has another 290GB of free space. Both my internal and external drives use ext4.

**Comment by that404nerd** [comment]
@mtkennerly Anything that you can recommend? Is there a way to reset all the backups and start from scratch again?

**Comment by that404nerd** [comment]
Hi there! I'm closing this issue since I figured out what the problem was. It was the r/w permissions and for some reason the drive was read only. I fixed it and now I am able to backup the save files. Sorry for mistake, I should've been careful. Have a nice day!

**Comment by mtkennerly** [comment]
No worries! I'm glad you got it working :D
