### ISSUE TITLE
Backup single save file?

### ISSUE THREAD

**Issue by annomatik** [mtkennerly/ludusavi#384]
### What's your question?

Hi! I have a PopCap game called Big Money Deluxe. It does not have a dedicated save game directory. Instead, there's a "savegame.dat" and a "hiscores.dat", next to the executeable (BigMoney.exe). And below, there are a bunch of directories.

I have added Big Money Deluxe as a custom game. Is it possible to not save the whole game all the time but instead, only savegame.dat and hiscores.dat? I have only seen the option to specify a path, which of course means backing up the whole game.

Thanks!

**Comment by mtkennerly** [comment]
Hi! Although the path selector dialog only lets you choose a folder, you can type in a file name (or glob pattern) afterwards :) There's some documentation about this here: https://github.com/mtkennerly/ludusavi/blob/master/docs/help/custom-games.md

**Comment by annomatik** [comment]
Works perfect, thanks!
