### ISSUE TITLE
So many logfiles...

### ISSUE THREAD

**Issue by annomatik** [mtkennerly/ludusavi#386]
### What's your question?

I started using Ludusavi today and like it a lot -- thanks! One thing I noticed... Today alone, ludusavi generated 55 logfiles (I use it as a Playnite tool -- it probably generates a log file for each time I start a game). Is there some sort of log file rotation so the directory doesn't run over? Thanks!

**Comment by mtkennerly** [comment]
Hmm, it's only supposed to keep 5 log files. Is it putting the logs in `%APPDATA%/ludusavi`, or are you using the [`ludusavi.portable` flag file](https://github.com/mtkennerly/ludusavi/blob/master/docs/help/application-folder.md)?

Also, by default, it only creates a log file if there's a warning or an error. Would you mind uploading the latest log file here?

**Comment by annomatik** [comment]
I'm using the portable one. Yes, there seems to be errors in all of them. Here's one:

[2024-09-01T16:44:35.801Z] WARN [ludusavi::scan::steam] Unable to locate Steam directory: FailedLocate(Backend(BackendError { inner: BackendErrorInner(Os { code: 2, kind: NotFound, message: "Das System kann die angegebene Datei nicht finden." }) }))

**Comment by mtkennerly** [comment]
> I'm using the portable one.

Is your `ludusavi.exe` on a network drive? If so, could you try with the build from https://github.com/mtkennerly/ludusavi/issues/385#issuecomment-2323523455 ?

> Yes, there seems to be errors in all of them. Here's one:

Thanks. I'm guessing you don't have Steam installed or it's installed in a custom location? I'll demote that log from `warning` to `info`.

**Comment by mtkennerly** [comment]
@annomatik Hey, just wanted to follow up here. Have you had a chance to try the new build?

**Comment by annomatik** [comment]
Hi! New Build works great with Age of Empires 2, thank you! Still have all the log files in the Ludsavi directory, I have it on a network drive too, in portable mode (with ludsavi.portable file).

**Comment by mtkennerly** [comment]
Gotcha, thanks for confirming. I think this is a limitation of the [`flexi_logger`](https://crates.io/crates/flexi_logger) library. I've opened a ticket with them here: https://github.com/emabee/flexi_logger/issues/173

**Comment by annomatik** [comment]
Thank you!

**Comment by mtkennerly** [comment]
This will be fixed in the next release \:D
