### ISSUE TITLE
Ludusavi crashes on start, "Failed to choose present mode"

### ISSUE THREAD

**Issue by Anseryde** [mtkennerly/ludusavi#388]
### Ludusavi version

v0.25.0

### Operating system

Linux

### Installation method

Flatpak

### Description

Ludusavi fails on start, crashing without showing gui.
System information:
Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.7-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × 13th Gen Intel® Core™ i7-13620H
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: Micro-Star International Co., Ltd.
Product Name: Katana 15 B13VFK
System Version: REV:1.0

### Logs

RUST_BACKTRACE=full flatpak run com.github.mtkennerly.ludusavi
wp_linux_drm_syncobj_manager_v1@71: error 0: surface already exists
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error thread '0main on object ' panicked at wp_linux_drm_syncobj_manager_v1/run/build/ludusavi/cargo/vendor/wgpu-core-0.19.3/src/device/global.rs@:711859: :
21:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
Protocol error stack backtrace:
0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: RUST_BACKTRACE=full flatpak run com.github.mtkennerly.ludusavi
wp_linux_drm_syncobj_manager_v1@71: error 0: surface already exists
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error thread '0main on object ' panicked at wp_linux_drm_syncobj_manager_v1/run/build/ludusavi/cargo/vendor/wgpu-core-0.19.3/src/device/global.rs@:711859: :
21:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
Protocol error stack backtrace:
0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1 @ 71 : 0
:   Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563432f463d5@ - 71<unknown>: 

Protocol error  0  on object  wp_linux_drm_syncobj_manager_v11@: 71 :  
  0xProtocol error 563432f75bfb0 -  on object <unknown>wp_linux_drm_syncobj_manager_v1
@71 :  
 Protocol error 20:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
563432f41ddf - <unknown>Protocol error 
0  on object  wp_linux_drm_syncobj_manager_v1 @371: :  
 Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563432f461ae@ - 71<unknown>: 

Protocol error  0  on object  wp_linux_drm_syncobj_manager_v14@: 71 :  
 Protocol error  00x on object 563432f476f9wp_linux_drm_syncobj_manager_v1 - @<unknown>71
:  
  5Protocol error : 0  on object  wp_linux_drm_syncobj_manager_v1 @ 710x: 563432f4749a
 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @ 716: : 
  Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563432f47b93@ - 71<unknown>: 

 Protocol error  0  on object 7wp_linux_drm_syncobj_manager_v1: @ 71 :  
 0x563432f47a74Protocol error 0 on object  - wp_linux_drm_syncobj_manager_v1<unknown>@
71 :  
 Protocol error 80:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
563432f46899 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @ 719: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563432f477a771 - : <unknown>

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@ 71 : 10
: Protocol error  0  on object  wp_linux_drm_syncobj_manager_v1 @0x71563431e5f5f3:  - 
<unknown>
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1 @ 7111: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563432d31f5571 - : <unknown>

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1 @ 7112: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563432c3749271 - : <unknown>

Protocol error  0  on object 13wp_linux_drm_syncobj_manager_v1: @ 71 :  
 Protocol error 0x0563432bf4979 on object  - wp_linux_drm_syncobj_manager_v1<unknown>@
71:  
 14Protocol error : 0  on object  wp_linux_drm_syncobj_manager_v1 @ 710x: 563432c026c3
 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @1571: :  
   Protocol error 0x0563432bc9fe1 on object  - wp_linux_drm_syncobj_manager_v1<unknown>@
71: 
 Protocol error  016 on object : wp_linux_drm_syncobj_manager_v1 @ 71 :  
0x563432a39fd7Protocol error  - 0<unknown> on object 
wp_linux_drm_syncobj_manager_v1@71:  
 Protocol error 170:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
5634322604ce - Protocol error <unknown>0
 on object wp_linux_drm_syncobj_manager_v1@71:  
 Protocol error 180:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
56343218a576 - <unknown>Protocol error 
0  on object  wp_linux_drm_syncobj_manager_v119@: 71 :  
 Protocol error  00x on object 563432176dfdwp_linux_drm_syncobj_manager_v1 - @<unknown>71
:  
 20Protocol error : 0  on object  wp_linux_drm_syncobj_manager_v1 @ 710x: 56343224f12b
 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @2171: :  
  Protocol error  00x on object 56343228882cwp_linux_drm_syncobj_manager_v1 - @<unknown>71
: 
Protocol error  0  on object 22wp_linux_drm_syncobj_manager_v1: @ 71 :  
 0x563431f61666Protocol error  - 0<unknown> on object 
wp_linux_drm_syncobj_manager_v1@71:  
 Protocol error 230:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
5634320f5763 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @2471: :  
 Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v156343225e459@ - 71<unknown>: 

 Protocol error  025 on object : wp_linux_drm_syncobj_manager_v1 @ 71 :  
0xProtocol error 563432f379cd0 -  on object <unknown>wp_linux_drm_syncobj_manager_v1
@ 71 : 26
:   Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563431f620a5@ - 71<unknown>: 

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object  wp_linux_drm_syncobj_manager_v1 @2771: :  
  Protocol error  00x on object 7f07b11bf08awp_linux_drm_syncobj_manager_v1 - @<unknown>71
: 
Protocol error  0  on object 28wp_linux_drm_syncobj_manager_v1: @ 71 :  
 0x7f07b11bf14bProtocol error  - 0__libc_start_main on object 
wp_linux_drm_syncobj_manager_v1 @ 7129: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563431e6016571 - : <unknown>

Protocol error  0  on object 30wp_linux_drm_syncobj_manager_v1: @ 71 :  
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v1 @ 71 :  
  Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v10@ - 71<unknown>: 

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1 @ 71 : 0
:   Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563432f463d5@ - 71<unknown>: 

Protocol error  0  on object  wp_linux_drm_syncobj_manager_v11@: 71 :  
  0xProtocol error 563432f75bfb0 -  on object <unknown>wp_linux_drm_syncobj_manager_v1
@71 :  
 Protocol error 20:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
563432f41ddf - <unknown>Protocol error 
0  on object  wp_linux_drm_syncobj_manager_v1 @371: :  
 Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563432f461ae@ - 71<unknown>: 

Protocol error  0  on object  wp_linux_drm_syncobj_manager_v14@: 71 :  
 Protocol error  00x on object 563432f476f9wp_linux_drm_syncobj_manager_v1 - @<unknown>71
:  
  5Protocol error : 0  on object  wp_linux_drm_syncobj_manager_v1 @ 710x: 563432f4749a
 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @ 716: : 
  Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563432f47b93@ - 71<unknown>: 

 Protocol error  0  on object 7wp_linux_drm_syncobj_manager_v1: @ 71 :  
 0x563432f47a74Protocol error 0 on object  - wp_linux_drm_syncobj_manager_v1<unknown>@
71 :  
 Protocol error 80:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
563432f46899 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @ 719: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563432f477a771 - : <unknown>

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@ 71 : 10
: Protocol error  0  on object  wp_linux_drm_syncobj_manager_v1 @0x71563431e5f5f3:  - 
<unknown>
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1 @ 7111: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563432d31f5571 - : <unknown>

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1 @ 7112: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563432c3749271 - : <unknown>

Protocol error  0  on object 13wp_linux_drm_syncobj_manager_v1: @ 71 :  
 Protocol error 0x0563432bf4979 on object  - wp_linux_drm_syncobj_manager_v1<unknown>@
71:  
 14Protocol error : 0  on object  wp_linux_drm_syncobj_manager_v1 @ 710x: 563432c026c3
 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @1571: :  
   Protocol error 0x0563432bc9fe1 on object  - wp_linux_drm_syncobj_manager_v1<unknown>@
71: 
 Protocol error  016 on object : wp_linux_drm_syncobj_manager_v1 @ 71 :  
0x563432a39fd7Protocol error  - 0<unknown> on object 
wp_linux_drm_syncobj_manager_v1@71:  
 Protocol error 170:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
5634322604ce - Protocol error <unknown>0
 on object wp_linux_drm_syncobj_manager_v1@71:  
 Protocol error 180:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
56343218a576 - <unknown>Protocol error 
0  on object  wp_linux_drm_syncobj_manager_v119@: 71 :  
 Protocol error  00x on object 563432176dfdwp_linux_drm_syncobj_manager_v1 - @<unknown>71
:  
 20Protocol error : 0  on object  wp_linux_drm_syncobj_manager_v1 @ 710x: 56343224f12b
 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @2171: :  
  Protocol error  00x on object 56343228882cwp_linux_drm_syncobj_manager_v1 - @<unknown>71
: 
Protocol error  0  on object 22wp_linux_drm_syncobj_manager_v1: @ 71 :  
 0x563431f61666Protocol error  - 0<unknown> on object 
wp_linux_drm_syncobj_manager_v1@71:  
 Protocol error 230:  on object  wp_linux_drm_syncobj_manager_v1 @ 71 : 0x
5634320f5763 - Protocol error <unknown>0
 on object  wp_linux_drm_syncobj_manager_v1 @2471: :  
 Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v156343225e459@ - 71<unknown>: 

 Protocol error  025 on object : wp_linux_drm_syncobj_manager_v1 @ 71 :  
0xProtocol error 563432f379cd0 -  on object <unknown>wp_linux_drm_syncobj_manager_v1
@ 71 : 26
:   Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v1563431f620a5@ - 71<unknown>: 

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object  wp_linux_drm_syncobj_manager_v1 @2771: :  
  Protocol error  00x on object 7f07b11bf08awp_linux_drm_syncobj_manager_v1 - @<unknown>71
: 
Protocol error  0  on object 28wp_linux_drm_syncobj_manager_v1: @ 71 :  
 0x7f07b11bf14bProtocol error  - 0__libc_start_main on object 
wp_linux_drm_syncobj_manager_v1 @ 7129: : 
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v10x@563431e6016571 - : <unknown>

Protocol error  0  on object 30wp_linux_drm_syncobj_manager_v1: @ 71 :  
 Protocol error  0  on object  wp_linux_drm_syncobj_manager_v1 @ 71 :  
  Protocol error  0  on object 0xwp_linux_drm_syncobj_manager_v10@ - 71<unknown>: 

Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@71:

**Comment by mtkennerly** [comment]
Hi! Unfortunately, graphics issues can be pretty hard to diagnose :( There could be an issue in your graphics drivers or a bug in one of the libraries that Ludusavi uses. There are a couple of workarounds you could try:

* Enable the software renderer by setting `ICED_BACKEND=tiny-skia` in your environment variables.
* Force X11 by running Flatpak with `flatpak run --nosocket=fallback-x11 --socket=x11 ...`

**Comment by Anseryde** [comment]
Thanks! Forcing it to run using x11 didn't work but the software renderer variable did.

**Comment by mtkennerly** [comment]
Ah, might have also needed `--nosocket=wayland`, but I'm glad the software renderer helps :)
