### ISSUE TITLE
Several errors, app does not open

### ISSUE THREAD

**Issue by shishimaru90** [mtkennerly/ludusavi#390]
### Ludusavi version

v0.25.0

### Operating system

Linux

### Installation method

Flatpak

### Description

`$ flatpak run com.github.mtkennerly.ludusavi 
wp_linux_drm_syncobj_manager_v1@65: error 0: surface already exists
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@65: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@65: 
thread 'main' panicked at /run/build/ludusavi/cargo/vendor/wgpu-core-0.19.3/src/device/global.rs:1859:21:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@65: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@65: 
`

**Comment by mtkennerly** [comment]
Hi! Unfortunately, graphics issues can be pretty hard to diagnose :( There could be an issue in your graphics drivers or a bug in one of the libraries that Ludusavi uses. There are a couple of workarounds you could try:

* Enable the software renderer by setting `ICED_BACKEND=tiny-skia` in your environment variables.
* Force X11 by running Flatpak with `flatpak run --nosocket=fallback-x11 --socket=x11 ...`

**Comment by mtkennerly** [comment]
I've just updated to the latest version of the Iced graphics library. Would you mind checking this build to see if it does any better for you?

> [ludusavi-v0.25.0-post.7+687cf50-linux.zip](https://github.com/user-attachments/files/17080444/ludusavi-v0.25.0-post.7%2B687cf50-linux.zip)

**Comment by iodream** [comment]
Hi i'm still getting this bug, even with the latest -git version. Installed as a systems package without flatpak. Issue is on Plasma Wayland but works on x11.

tiny-skia workaround works as well.

**Comment by mtkennerly** [comment]
@iodream Thanks for the extra info :+1: I've added some details to the [troubleshooting steps](https://github.com/mtkennerly/ludusavi/blob/master/docs/help/troubleshooting.md) for anyone else who runs into this.

**Comment by iodream** [comment]
after some more testing my own issue turns out to be caused by nvidia drivers, my DE(and the terminal as well for that matter) were selecting the discrete GPU as the main one for rendering. launching on the integrated gpu works without the software rendering workaround.

**Comment by mtkennerly** [comment]
@iodream Are there some particular environment variables or tools you used to reconfigure that? I can add it to the troubleshooting guide as an option.

**Comment by iodream** [comment]
Well i'm just using [this](https://gitlab.com/AndrewShark/amd-vulkan-prefixes/-/tree/main?ref_type=heads) tool which is just a bash script which sets VK_DRIVER_FILES to force a particular vulkan implementation. But looking at it i think it's a bit too specific and would help only AMD users.
