### ISSUE TITLE
Big fish games

### ISSUE THREAD

**Issue by JackobStuard** [mtkennerly/ludusavi#391]
### What's your idea?

Hi, it will be great to automatically detect and back up "Big fish games".

**Comment by mtkennerly** [comment]
Hi! Ludusavi gets most of its save locations from PCGamingWiki. It sounds like PCGamingWiki doesn't let you add save locations specific to Big Fish Games releases, so there are a couple of ways to proceed here:

* For games that have a PCGamingWiki article (https://www.pcgamingwiki.com/wiki/List_of_games_available_on_Big_Fish_Games), if the Big Fish Games release uses the same save locations as another release (Steam, GOG, etc), then you could add the save paths for the other store instead.
* If there's no article or the Big Fish Games release has a different save location, then you could create a secondary manifest.

The specification for secondary manifests can be found here: https://github.com/mtkennerly/ludusavi-manifest , and there are some existing secondary manifests you can use as an example: https://github.com/mtkennerly/ludusavi?tab=readme-ov-file#community

**Comment by JackobStuard** [comment]
Ok, thanks
