### ISSUE TITLE
Non Steam Games recognition

### ISSUE THREAD

**Issue by hvmzx** [mtkennerly/ludusavi#393]
### What's your question?

Hi,

I wanted to know how Ludusavi is supposed to be used for non steam games, as it doesn't seem to recognise many of my games as their app id may not match databases. Basically all the prefixes are in compatadata folder (steamdeck), and in each prefix there will be in some folder (differs often) the save of my game.

What would be the solution to this ?

Thanks

**Comment by hvmzx** [comment]
I think it's probably because they are quacked games so the app id was random I believe and also the save locaton, but here here is an example :
- Devil May Cry 5 : 3451084768

After manually adding it, the files were correctly found. But it's weird that it didn't get detected in the first place as its title corresponds to the title on PCGamingWiki.

I think for this non steam games case, it would be nice to have the option to select a list of folders like "/home/deck/.steam/steam/steamapps/compdata/APP_ID/pfx/drive_c/users/Public/Documents" and if Ludusavi finds a game in Steam that has a certain name in this case "Devil May Cry 5" and has its APP_ID also, then add that folder the list of files to sync (if the option is enabled)

Because from the looks of it, a few games might not be recognised, but most games will actually have the wrong folder to check so I have to do them manually.

**Comment by mtkennerly** [comment]
Ah, [on PCGamingWiki](https://www.pcgamingwiki.com/wiki/Devil_May_Cry_5#Save_game_data_location), the save path explicitly contains the app ID (`601150`) and references the Steam `userdata` folder, so that's why the save path wouldn't match as a non-Steam game. Defining a custom game is one solution (as you found), or you could create a secondary manifest if you want to share it with other people.

I can't provide support for cracked games specifically (I'd rather not risk any legal liability), so I'll go ahead and close this.

**Comment by hvmzx** [comment]
> Ah, [on PCGamingWiki](https://www.pcgamingwiki.com/wiki/Devil_May_Cry_5#Save_game_data_location), the save path explicitly contains the app ID (`601150`) and references the Steam `userdata` folder, so that's why the save path wouldn't match as a non-Steam game. Defining a custom game is one solution (as you found), or you could create a secondary manifest if you want to share it with other people.
> 
> 
> 
> I can't provide support for cracked games specifically (I'd rather not risk any legal liability), so I'll go ahead and close this.

I'll look up the manifest part and how to customise it for non steam games. Thanks!
