### ISSUE TITLE
Ludusavi unable to detect rclone when Ludusavi is installed via Flatpak

### ISSUE THREAD

**Issue by MRDGH2821** [mtkennerly/ludusavi#394]
### Ludusavi version

v0.25.0

### Operating system

Linux

### Installation method

Flatpak

### Description

I have rclone installed in my system, but ludusavi is unable to detect it. I'm using Fedora 40 & installed ludusavi from flathub.

**Comment by mtkennerly** [comment]
Hi! Could you share how you've configured  Rclone in Ludusavi (path and arguments)?

**Comment by MRDGH2821** [comment]
> Hi! Could you share how you've configured  Rclone in Ludusavi (path and arguments)?

At first I typed `/usr/bin/rclone` with the default preset parameters.
Didn't work.

But if I pick rclone from the picker icon, it was able to use rclone but the path in app was different.
I realised that this is a limitation of flatpak. 

So I tinkered with flatseal to allow access to access to system binaries, still no luck.

In the end, I downloaded binary release, but I'm open to installing flatpak for more testing.

**Comment by mtkennerly** [comment]
Gotcha. I'm not sure offhand how to get the Flatpak version to cooperate, but I know the permissions can be finicky 😅 

I think using the standalone release is a good idea for now. I'll try to set up a test system sometime so I can look into this further.

**Comment by MRDGH2821** [comment]
I discovered 2 apps which use rclone via flatpak.

Both apps use a different approach.


Rclone shuttle

https://github.com/pieterdd/RcloneShuttle

It uses system installed rclone. After installing the app it tells me to configure rclone via CLI then use the app to see the remotes.


Celeste

https://github.com/hwittenborn/celeste

This doesn't use system rclone, nor does it use system rclone generated config. 

It possibly comes bundled with its own rclone binary. 

I can say this because Fedora 40 has an older version of rclone (which doesn't support proton drive) and Celeste was able to connect to Proton drive.


So ludusavi flatpak can either bundle rclone like Celeste OR use similar configuration as of Rclone Shuttle.

**Comment by mtkennerly** [comment]
I found a solution that worked for me on Ubuntu. If you give Ludusavi the host filesystem permission (`flatpak override com.github.mtkennerly.ludusavi --filesystem=host`), then you can reference the system Rclone as `/var/run/host/usr/bin/rclone`. Could you give it a try?

**Comment by MRDGH2821** [comment]
> I found a solution that worked for me on Ubuntu. If you give Ludusavi the host filesystem permission (`flatpak override com.github.mtkennerly.ludusavi --filesystem=host`), then you can reference the system Rclone as `/var/run/host/usr/bin/rclone`. Could you give it a try?

This indeed works!

**Comment by mtkennerly** [comment]
Great :D I've updated the documentation with a note about that.
