### ISSUE TITLE
Allow processing bidirectional redirects in reverse order in restore mode

### ISSUE THREAD

**Issue by DJXJD** [mtkennerly/ludusavi#395]
### What's your idea?

Hey there,

First up, I'm loving ludusavi! Thank you very much for your great work on the project.

I'm in the process of setting up save syncing for gog games, between my steam deck running the heroic flatpak, and my main Arch Linux PC, running the heroic AUR package.

While doing the above, I'm making use of the following bidirectional redirects, to handle linux native saves:
![20240927_07h58m24s_grim](https://github.com/user-attachments/assets/7f8a25b8-16b4-44cb-a059-c8f084ea6e0c)

Those rules work perfectly for backing up, but when restoring, they would need to be applied in reverse order in order to restore properly.

Correct backup:
![Screenshot_20240927_080743](https://github.com/user-attachments/assets/b5628b89-6a96-4820-a769-7b6b53537653)

Incorrect restore:
![Screenshot_20240927_080936](https://github.com/user-attachments/assets/8226d9a6-8630-4a2f-a4c8-9b70641bf654)

Correct restore with bidirectional redirects in reverse order:
![Screenshot_20240927_081043](https://github.com/user-attachments/assets/80aaa5f2-ec11-4712-868d-12843fb78429)
![Screenshot_20240927_081205](https://github.com/user-attachments/assets/ed2f2731-f28c-4dda-b83e-d828cb3373ae)

I believe that having a toggle (so as not to break current setups) for my suggestion would work great with the nature of bidirectional redirects, and could really simplify some complex setups. Of course, the same end result can be achieved using separate backup and restore redirects, but I feel like its really in the spirit of bidirectional redirects to be able to combine them in this way.

Thanks again for your great work and hope to hear back soon!

**Comment by mtkennerly** [comment]
Hi! Thanks for this suggestion. It will be available in the next release :)

**Comment by DJXJD** [comment]
Thank you very much!!! Really looking forward to making use of this when that release comes 😁
