### ISSUE TITLE
Show warning when multiple game entries point to same file(s)

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#40]
There are cases where certain PCGW articles have incomplete or wrong information, which can lead to issues like this:
![imagen](https://user-images.githubusercontent.com/1389286/90116182-be4fa400-dd1a-11ea-93ae-6a99f928b6c5.png)

This can later lead to issues when trying to restore the save file of any of the games that coincide in files, since it will overwrite the other one. It would be useful if Ludusavi warned if there are cases like this detected, maybe showing them on top of the list to see them easier and/or a warning with the conflicting games. Identifying them this way could also help to more easily see errors like this and fix them in the respective pages.

**Comment by mtkennerly** [comment]
How about a `[DUPLICATES]` tag next to each game/file, like how the `[FAILED]` tag works?

I could add a modal warning as well, but it would need to be configurable, since there are some cases where duplicate files are expected - namely Sega Genesis Classics, where PCGW has 50 articles (one per game), but each game has the same save file.

**Comment by darklinkpower** [comment]
Yeah I think showing `[DUPLICATES]` would certainly help.

I think if possible, this would help too:

1. Group games with conflicting files together in the list to check more easily the duplicates
2. Perhaps even show a label in the specific conflicting files on the right side
3. When there are duplicates, show a warning in either a tiny window or in the Ludusavi UI since the duplicates can be missed by the user if the list is not checked

**Comment by mtkennerly** [comment]
I'm not sure about 1 (it could get complex depending on how the duplicates are distributed), but 2 and 3 are doable for sure. I'll play around with how to display a warning without a full-blown modal (maybe in the main status: `10 games | 100 MiB | 2 duplicated entries`).

**Comment by mtkennerly** [comment]
## GUI
I added a badge in the main status as well as next to each game. I also converted the game-level `[FAILED]` label and the `selecting ...` text into badges. I'd like to convert the individual file-level `[FAILED]` and `[DUPLICATED]` labels into badges as well, but I'm going to wait and do it as part of #45.

![image](https://user-images.githubusercontent.com/4934192/90351932-bee48500-e00f-11ea-9115-f7f7eee4606e.png)

## CLI (standard format)
```
$ ludusavi backup --preview 'A Custom Game' 'A Custom Game 2'
A Custom Game [3 B] [DUPLICATES]:
  - [DUPLICATED] C:/tmp/ludusavi/file1.txt
  - C:/tmp/ludusavi/file2.txt
  - [DUPLICATED] HKEY_CURRENT_USER/Software/Ludusavi
A Custom Game 2 [1 B] [DUPLICATES]:
  - [DUPLICATED] C:/tmp/ludusavi/file1.txt
  - [DUPLICATED] HKEY_CURRENT_USER/Software/Ludusavi

Overall:
  Games: 2
  Size: 4 B
  Location: C:/Users/mtken/ludusavi-backup
```

## CLI (JSON format)
There is a new `duplicatedBy` field:

```
$ ludusavi backup --preview --api 'A Custom Game' 'A Custom Game 2'
{
  "overall": {
    "totalGames": 2,
    "totalBytes": 4,
    "processedGames": 2,
    "processedBytes": 4
  },
  "games": {
    "A Custom Game": {
      "decision": "Processed",
      "files": {
        "C:/tmp/ludusavi/file1.txt": {
          "bytes": 1,
          "duplicatedBy": [
            "A Custom Game 2"
          ]
        },
        "C:/tmp/ludusavi/file2.txt": {
          "bytes": 2
        }
      },
      "registry": {
        "HKEY_CURRENT_USER/Software/Ludusavi": {
          "duplicatedBy": [
            "A Custom Game 2"
          ]
        }
      }
    },
    "A Custom Game 2": {
      "decision": "Processed",
      "files": {
        "C:/tmp/ludusavi/file1.txt": {
          "bytes": 1,
          "duplicatedBy": [
            "A Custom Game"
          ]
        }
      },
      "registry": {
        "HKEY_CURRENT_USER/Software/Ludusavi": {
          "duplicatedBy": [
            "A Custom Game"
          ]
        }
      }
    }
  }
}
```
