### ISSUE TITLE
Custom games: minimize entries

### ISSUE THREAD

**Issue by maicol07** [mtkennerly/ludusavi#401]
### What's your idea?

When you have a lot of custom entries it becomes hard to see all of them without scrolling a lot. A new button to minimize the entry (on a single row, like in the backup mode) would help

**Comment by mtkennerly** [comment]
Thanks for the suggestion :) This will be available in the next release:

> ![image](https://github.com/user-attachments/assets/4c068ead-7364-425e-b0f0-18c501f107b7)
