### ISSUE TITLE
Custom games: entry mode (replace or append)

### ISSUE THREAD

**Issue by maicol07** [mtkennerly/ludusavi#402]
### What's your idea?

Add a new selector for each entry to be able to select the behaviour of a custom game when is also found on a manifest:
- **Replace**: The current behaviour, replaces the manifest entry with the custom one
- **Append**: It appends the custom paths to the manifest entry. So scanned paths would be manifest + custom

**Comment by mtkennerly** [comment]
Demo:

> https://github.com/user-attachments/assets/0e355b8f-1703-480e-a5d2-47f656d9d3fa
