### ISSUE TITLE
I'm having problems with several glitter graphics, how can I solve this?

### ISSUE THREAD

**Issue by Wesleyjor6** [mtkennerly/ludusavi#403]
### Ludusavi version

v0.25.0

### Operating system

Windows

### Installation method

Standalone

### Description

I'm having several problems with the interface of the problem every time blitz is appearing and every time the program gets totally bugged it just gets to a level where it's not possible to move the program my My RX 550 video card has any solution to solve this problem. Vitaliza Vulcan would be able to change the volcano to another pi or something like that. I'm kind of new to these things, I don't understand. I'm pretty much there to tell these things, amazing sensational problems, but if I didn't need graphics, I would be messing with it. I'm having a lot of headaches with the problem.

**Comment by Wesleyjor6** [comment]
![Uploading 17288532936067096757801242526261.jpg…]()

**Comment by mtkennerly** [comment]
Hi! It looks like the screenshot didn't upload. Could you please try again?

You can try some steps from the [troubleshooting document](https://github.com/mtkennerly/ludusavi/blob/master/docs/help/troubleshooting.md). In particular, try setting the environment variable `ICED_BACKEND` to the value `tiny-skia`. That will use the software renderer, which may help if it's an issue with your graphics drivers.

**Comment by Wesleyjor6** [comment]
![Captura de Tela (39)](https://github.com/user-attachments/assets/38b9b450-fca1-4f07-bccf-2cd25086c871)

**Comment by Wesleyjor6** [comment]
[Uploading ludusavi_rCURRENT.log…]()

**Comment by Wesleyjor6** [comment]
[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/17386849/ludusavi_rCURRENT.log)

**Comment by Wesleyjor6** [comment]
[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/17387116/ludusavi_rCURRENT.log)

**Comment by mtkennerly** [comment]
Did either of the first two commands make the text display correctly?

For the last command (`RUST_LOG="trace"`), please just open and close Ludusavi without performing a scan, and then upload the log file. I need to see a minimal log file with only the startup info.

**Comment by Wesleyjor6** [comment]
Hi The first command worked perfectly, could it be set permanently? I don't know how to use it to do much with these environment things.

**Comment by mtkennerly** [comment]
Great! Yes, you can set it permanently :)

I noticed your system is in Portuguese, so I found a video that you can follow: https://youtu.be/ing2pLCrvxo?t=124

Here are the steps:

* Open the Start menu and search for `editar as variáveis de ambiente para sua conta`. Click on the matching result.
* In the new window, click the first `novo` button (in the top section `variáveis de usuário para...`)
* Set `nome da variável` = `ICED_BACKEND`
* Set `valor da variável` = `tiny-skia`
* Click `OK`

**Comment by Wesleyjor6** [comment]
Now it's much better, thank you very much for your help and all the patience you had with me, I appreciate it.
