### ISSUE TITLE
Saves are read only instead of read/write

### ISSUE THREAD

**Issue by KibSquib48** [mtkennerly/ludusavi#404]
### Ludusavi version

v0.25.0

### Operating system

Linux (Steam Deck)

### Installation method

Flatpak

### Description

I tried playing Sonic Adventure 2 with a save file restored from a Ludusavi backup, but it kept saying something like "File not saved!", so I checked the file's permissions and it turns out they've been set to read only instead of read/write.

**Comment by mtkennerly** [comment]
Hi! I can look into this. I have some questions for you, just to narrow down where things went wrong:

* Are you using zip backups?
* Are the original backup files also read-only, or just the restored copies?
* Is this the same system where you made the backup, or did you copy the backup from another system?
* Had you played the game before restoring the backup?

**Comment by KibSquib48** [comment]
> Hi! I can look into this. I have some questions for you, just to narrow down where things went wrong:
> 
> * Are you using zip backups?
> * Are the original backup files also read-only, or just the restored copies?
> * Is this the same system where you made the backup, or did you copy the backup from another system?
> * Had you played the game before restoring the backup?

I'm backing up to a folder.
The backups are read-only too.
I backed up from the Deck, wiped and reinstalled SteamOS, and then restored the backup.
I restored the backup before launching the game.

**Comment by mtkennerly** [comment]
I just tested a Flatpak install on Ubuntu and confirmed that the backups are created with read/write permissions. I don't have a Steam Deck to test on, but I suspect that the permissions got changed when you transferred the files with LocalSend, so I think this is out of the scope of what Ludusavi should try to recover from automatically. I'd recommend manually fixing the existing backups with `chmod`. However, if you find that new backups are being created with the wrong permissions, please let me know.
