### ISSUE TITLE
Show number of selected games

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#41]
Probably in the info area, in order to prevent mistakes when selecting games to backup or restore.

![imagen](https://user-images.githubusercontent.com/1389286/90300989-bc90f800-de62-11ea-9d5d-c89dc7b94c41.png)

**Comment by mtkennerly** [comment]
## Changing selection after operation is complete
![count-selection-resize-2](https://user-images.githubusercontent.com/4934192/90320334-6083ad80-df0e-11ea-81db-e3fe67a80a9b.gif)

## Changing selection during operation
![count-selection-resize-2b](https://user-images.githubusercontent.com/4934192/90320335-62e60780-df0e-11ea-828b-61c96049c06a.gif)
