### ISSUE TITLE
Option to add mutliple wine prefixes at the same time

### ISSUE THREAD

**Issue by mrdm211** [mtkennerly/ludusavi#410]
### What's your idea?

As the title mentions, a way to add multiple wine prefixes from a single folder would be great. Say I have like 3 wine prefixes in a folder. I would like to have an option to add all those wine prefixes at the same time instead of adding them one at a time. I hope you will look into this. Thanks!

**Comment by mtkennerly** [comment]
Hi! When defining roots, you can use [globs](https://en.wikipedia.org/wiki/Glob_(programming)) to match multiple folders, as in `~/wine-prefixes/*` :)
