### ISSUE TITLE
Support for Save Data Collection via Symbolic Links

### ISSUE THREAD

**Issue by Schroedingers-Cat** [mtkennerly/ludusavi#411]
### What's your idea?

Instead of copying save game data, ludusavi could have an alternative mode that replaces a game's save data directory with a symbolic link, moving the actual data to a central "collected saves" directory.

This approach offers several benefits:
- Enables real-time syncing of game saves using tools like SyncThing (including on Steam Deck).
- Avoids duplication of save data on the file system.
- Has no overhead.
- Avoids the need for regular execution of ludusavi.

I've been using a custom script to achieve this on Linux and Windows for years, and it has worked reliably. Integrating such a feature into Ludusavi would be incredibly useful due to its huge database already having everything that's needed for this.

**Comment by mtkennerly** [comment]
Hi! I had considered something like this before, but ended up deciding against it: https://github.com/mtkennerly/ludusavi/issues/11#issuecomment-1452618152

That said, you could use Ludusavi's CLI (`ludusavi backup --preview --api`) to get the save locations and optionally filter by size/etc to decide what to symlink.

**Comment by Schroedingers-Cat** [comment]
I understand your reasons.  

Thanks a lot for mentioning the CLI, that looks quite useful for my use case.
