### ISSUE TITLE
Support for Backing Up Save Files from Non-Standard Game Installations

### ISSUE THREAD

**Issue by z1n8tjshh** [mtkennerly/ludusavi#412]
### What's your idea?

Hello Ludusavi team,

I have a feature suggestion that I hope you’ll consider. Some games, particularly those installed from non-standard sources (such as those distributed by groups like Razor 1911 or Reloaded), store their save files in unique locations. For example, save files for these versions can often be found in directories like:

```
%appdata%\.1911
C:\ProgramData\Socialclub\RLD!
```

Currently, Ludusavi doesn’t seem to automatically detect or back up save files from these non-standard game paths. It would be incredibly useful if Ludusavi could be updated to recognize these directories and back up save files from these installations as well.

Is there a possibility that support for these types of game installations could be added, or automatically detected? I believe this feature would help make Ludusavi even more comprehensive for users who might be managing both official and non-standard game versions.

Thank you so much for considering this request, and thank you for all the work you’ve done to make Ludusavi such a great tool!

**Comment by mtkennerly** [comment]
Hi! For legal reasons, I'm not comfortable providing specific support for cracked versions of games in Ludusavi directly.

Of course, others are free to write a secondary manifest that adds more save locations to existing game entries:

* https://github.com/mtkennerly/ludusavi?tab=readme-ov-file#community
* https://github.com/mtkennerly/ludusavi-manifest
