### ISSUE TITLE
How to Run Automated Backups via Task Scheduler Without Showing the CLI Window?

### ISSUE THREAD

**Issue by z1n8tjshh** [mtkennerly/ludusavi#413]
### What's your question?

Hello Ludusavi team,

I’ve been trying to set up an automated backup using Windows Task Scheduler to run Ludusavi on a regular basis, following this page: https://github.com/mtkennerly/ludusavi/blob/master/docs/help/backup-automation.md

However, I’ve encountered an issue: when the task runs, the command-line interface (CLI) window pops up, which is a bit distracting.

Is there a way to configure the Task Scheduler or Ludusavi so that the backup process runs completely in the background, without showing the black CLI window? I’d like to automate my backups without any visual interruptions.

Any guidance or suggestions would be greatly appreciated!

**Comment by mtkennerly** [comment]
Hi! From a brief test, it looks like enabling the `run whether user is logged in or not` option will hide the console window.

In my case, it didn't like my password for some reason (no idea why - I use a local Windows account, if that matters), so I also had to enable the `do not store password - the task will only have access to local computer resources` option. From what I can tell, the backup still contains all of the correct files, but I'm not 100% sure what "local computer resources" means. It sounds like that means it can only access local drives, but not network drives, which is fine in my case. I'd recommend doing some extra testing just to be safe 😅
