### ISSUE TITLE
Backup is processing non selected games

### ISSUE THREAD

**Issue by nicolasnobelis** [mtkennerly/ludusavi#415]
### Ludusavi version

v0.26.0

### Operating system

Linux

### Installation method

Flatpak

### Description

![Capture d’écran du 2024-11-15 10-56-07](https://github.com/user-attachments/assets/d7a40156-6ae2-4320-b0cc-a07a7ffef376)

I am in the "backup" tab with a filter set to "leg". I see all the games matching this filter.
Please note that one game "LEGO DC Super Vilains" is from a primary manifest while all the others are from a secondary manifest.

If I trigger the backup, Ludusavi creates 5 archives. Since only one is selected, I would expect only this one would be created.
I think that the problem lies with the presence of a secondary manifest.

**Comment by mtkennerly** [comment]
Thanks for reporting this! There's some logic so that, if you explicitly use a game's context menu to back it up, then the checkbox is ignored. The new filtered scan feature from 0.26.0 is mistakenly using the same logic. I'll get this fixed and make a release within the next few days :)

**Comment by nicolasnobelis** [comment]
A strange behavior caused I guess by the way you fixed the bug:

- Select one game in the list
- Use the filter to reduce the list, hiding the game you selected
- Select another game
![Capture d’écran du 2024-12-04 22-28-34](https://github.com/user-attachments/assets/219e2b62-ce3c-4f9d-8e10-ff8a0177d6f4)

You are now in this state. Ludusavi says "2 of XX games" but there is only one visible on the screen.

I you press "backup", Ludusavi will only create one save, for the visible selected game.

I am not sure if this is really a bug: you could argue that, since only one game is visible, Ludusavi should only create one save. However, you could also argue that, if Ludusa says "2 of XX", you should expect 2 saves.

What do you think ?

**Comment by mtkennerly** [comment]
Yeah, that's a bit awkward. I think the summary line should reflect the games that are currently displayed. This will be adjusted in the next release:

> https://github.com/user-attachments/assets/6556db94-e973-47e5-b736-486052c82231
