### ISSUE TITLE
Files are not ignored in Backup Exclusions

### ISSUE THREAD

**Issue by ItsRogueRen** [mtkennerly/ludusavi#416]
### Ludusavi version

v0.26.0

### Operating system

Linux

### Installation method

Flatpak

### Description

I have added some folders within my .config directory to be excluded from backups. However, they are still included every time I make a backup without exception. 

### Logs

![image](https://github.com/user-attachments/assets/e92c8003-e10c-4b65-9b8b-0f21da8e54be)

**Comment by mtkennerly** [comment]
Hi! I'm not able to reproduce this using Flatpak on Ubuntu. Could you show me an example of a game where Ludusavi is finding files in those folders?

For one such game, please run this command:

```
flatpak run --env=RUST_LOG=ludusavi=trace com.github.mtkennerly.ludusavi backup --preview "<GAME NAME HERE>"
```

...and then send me a copy of `~/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi/ludusavi_rCURRENT.log`.
