### ISSUE TITLE
 zip is not working with stalker 2 and run as admin required for wrap..

### ISSUE THREAD

**Issue by J65043** [mtkennerly/ludusavi#422]
### Ludusavi version

v0.27.0

### Operating system

Windows

### Installation method

Standalone

### Description

I get an error zipping backups for stalker 2
I get this error with the zip. It seems like I am also required to run the shortcut I have for wrapping as admin, is that normal?

### Logs

zip logs
[2024-11-24T19:35:41.758Z] ERROR [ludusavi::scan::layout] [S.T.A.L.K.E.R2 ] unable to create zip file: StrictPath { raw: "C:/Users/j/ludusavi-backup/S.T.A.L.K.E.R2 /backup-20241124T193541Z.zip", basis: None } | The system cannot find the path specified. (os error 3)

[2024-11-24T19:38:32.950Z] ERROR [ludusavi::cli] WRAP::execute: Game command execution failed with: Os {
    code: 740,
    kind: Uncategorized,
    message: "The requested operation requires elevation.",
}

**Comment by mtkennerly** [comment]
Hi!

I'm not sure about the admin part. It's possible that S.T.A.L.K.E.R. 2 itself requires elevated permissions, but is set up in such a way that you're not normally prompted for it, whereas Ludusavi doesn't expect to need elevation. I would say that's probably normal depending on the game.

As far as the backup not working, based on this part of the log:

```
C:/Users/j/ludusavi-backup/S.T.A.L.K.E.R2 /backup-20241124T193541Z.zip
```

It looks like `S.T.A.L.K.E.R2 ` ends with a space. Is that a custom entry? If so, please try removing the space from the title. I was able to reproduce some backup issues by making a custom entry that ends with a space, so I'll need to fix up the handling for that in Ludusavi.
