### ISSUE TITLE
Unable to download cloud backup to steam deck using Rclone

### ISSUE THREAD

**Issue by antymonty** [mtkennerly/ludusavi#428]
### Ludusavi version

v0.27.0

### Operating system

Linux (Steam Deck)

### Installation method

Flatpak

### Description

I've been working on getting this functional for my steam deck over the past day and it was I had it working until I somehow broke it. Now, when I try and download my ludusavi files from the cloud I receive an error.
The only things I've done in my setup so far that may be somewhat non-traditional are:
1. Setting up the cloud saving through Google Drive using RClone
2. Set up redirects for my game that saves in Windows-specific locations.
I've included the error in the logs. Please let me know if you need any more info.

### Logs

Error: Unable to synchronize with cloud.

Command failed with code 3: /home/deck/Downloads/rclone-v1.68.2-linux-amd64/rclone --fast-list --ignore-checksum sync -v --use-json.log --stats=100ms ludusave-1733785975:ludusavi-bac /home/deck/ludusavi

**Comment by mtkennerly** [comment]
Hi! If you run this manually, is there any additional output?

```
/home/deck/Downloads/rclone-v1.68.2-linux-amd64/rclone --fast-list --ignore-checksum sync -vvv ludusave-1733785975:ludusavi-bac /home/deck/ludusavi
```

**Comment by antymonty** [comment]
Sorry I didn't see the notification until just now. I think I solved it; it seems I had 2 characters that looked the same but were actually different, so it created two ludusavi folders in my drive. After correcting the issue, it worked again.
