### ISSUE TITLE
Detect saves in xdg dirs for flatpaked lutris

### ISSUE THREAD

**Issue by moeenio** [mtkennerly/ludusavi#429]
### What's your idea?

Linux native games that use XDG standard directories, launched within flatpaked Lutris, will hsve their save directory inside the Lutris flatpak's own directory.

```
/home/deck/.var/app/net.lutris.Lutris/
├── cache
├── config
└── data
    ├── applications
    ├── Celeste              <--------
    ├── desktop-directories
    ├── icons
    ├── lutris
    ├── mime
    ├── recently-used.xbel
    ├── umu
    ├── wget
    └── yuzu
```
Would be neat if ludusavi detected them here :3

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the `scan` function to detect Linux native games using XDG standard directories within the Flatpak Lutris directory. Added a new function `scan_flatpak_xdg` to handle the detection of these games.

You can review changes in this commit: https://github.com/kkpo4553/mtkennerly-ludusavi-429/commit/1e0e6fcb7af0000801f4b9749c582fef9cb66fc5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by mtkennerly** [comment]
Thanks for this suggestion! We already do this for Heroic, so I agree it makes sense to add for Lutris \:D

**Comment by moeenio** [comment]
yoo thanks for implementing it!
