### ISSUE TITLE
Use filter input box to just show searched games

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#43]
This would help the user when the game list is large and wants to find a specific single game or just a few of them
![imagen](https://user-images.githubusercontent.com/1389286/90301102-6b353880-de63-11ea-8c42-fe58782c7ba0.png)

**Comment by mtkennerly** [comment]
It uses fuzzy matching so that you can type arbitrary parts of the name:

![search](https://user-images.githubusercontent.com/4934192/90331503-e5a8aa00-df82-11ea-9fd3-621d202fb465.gif)
