### ISSUE TITLE
Excluded directories are still scanned on every run

### ISSUE THREAD

**Issue by Terrance** [mtkennerly/ludusavi#432]
### Ludusavi version

v0.27.0

### Operating system

Windows

### Installation method

Other

### Description

Not sure if this is intentional, but despite toggling off certain large directories on a couple of games, they still get scanned in their entirety during both previews and actual backups.

This makes all-game scans rather slow (about 12 minutes to preview) because of these huge excluded directories.  For exaple, _Tabletop Simulator_ stores cached mod files in `~/Documents/My Games/Tabletop Simulator/Mods` (currently ~14GB, ~9000 files), alongside saves and other files I do want to keep.  I have the `Mods` directory excluded, but almost the entire scan duration was in part digging through that directory.

### Logs

📎 [ludusavi_rCURRENT.log](https://github.com/user-attachments/files/18203612/ludusavi_rCURRENT.log)

Some progress snippets (the first ~45k proceeded at a regular pace, about 1k/sec, presumably those not installed):

```
Scan (00:00:45) █████████████████████████████████████████████████████░ Games: 47648 / 48363
Scan (00:01:16) █████████████████████████████████████████████████████░ Games: 48304 / 48363
Scan (00:03:05) █████████████████████████████████████████████████████░ Games: 48304 / 48363
Scan (00:05:36) █████████████████████████████████████████████████████░ Games: 48362 / 48363
Scan (00:11:20) █████████████████████████████████████████████████████░ Games: 48362 / 48363
```

**Comment by mtkennerly** [comment]
Hi! This is the intended behavior when you uncheck a file/folder in the list under a game. However, if you go to the "other" screen and add `~/Documents/My Games/Tabletop Simulator/Mods` to the "backup exclusions" list, then it won't be scanned at all :)

**Comment by Terrance** [comment]
Noted, thanks -- scan time now down to 2 minutes from cold with a few well-placed excludes.  🙂  (Mainly one game with a lot of small files that I do want to keep backed-up, and it seems a lot faster on subsequent scans.)
