### ISSUE TITLE
How to detect manually-installed games?

### ISSUE THREAD

**Issue by Terrance** [mtkennerly/ludusavi#434]
### What's your question?

I have a handful of games installed outside of a game store client and in their own base directory, `D:\Windows\Games\Standalone`.  This path is defined as an "Other" root in Ludusavi, and I can see the immediate child directories being detected as games.  However, some of these installations use names that don't match the full game name.

For example, _Dr. Robotnik's Ring Racers_ is currently installed at `D:\Windows\Games\Standalone\Ring Racers`.  My understanding of the alias system is that I can alias _Ring Racers_ to _Dr. Robotnik's Ring Racers_ in order to get this picked up:

![Alias for Ring Racers](https://github.com/user-attachments/assets/64790f65-3ea9-45a1-aec9-9ea6c7b1cf24)

I assume this is the expected way around, based on the "overrides a manifest entry" hint appearing on the inverse suggesting I'm replacing the real entry, but I've tried it individually both ways around without any success.  Am I using this right?

<details>
<summary>Log snippet</summary>

```
[2024-12-21T18:41:25.013Z] DEBUG [ludusavi::scan::launchers] Scanning launcher info: Other(Other { path: StrictPath { raw: "D:/Windows\\Games\\Standalone", basis: None } })
[2024-12-21T18:41:25.013Z] DEBUG [ludusavi::scan::launchers::generic] ranking installations for root: Other(Other { path: StrictPath { raw: "D:/Windows\\Games\\Standalone", basis: None } })
[2024-12-21T18:41:25.014Z] DEBUG [ludusavi::scan::launchers::generic] actual install folders: ... | Ring Racers | ...
[2024-12-21T18:41:25.088Z] DEBUG [ludusavi::scan::launchers::generic] [...] selecting subdir with score ...
... (not listed here)
[2024-12-21T18:41:25.744Z] DEBUG [ludusavi::scan::launchers] launcher games found (Other(Other { path: StrictPath { raw: "D:/Windows\\Games\\Standalone", basis: None } })): {
    ... (or here)
}
```
</details>

**Comment by mtkennerly** [comment]
The alias feature is pretty limited by design. It's really just for interoperation with other tools and for translations. The presence of an alias won't cause any extra paths to be scanned.

With the options that exist today, you could either:

* Make a custom entry titled `Dr. Robotnik's Ring Racers`, mark it as "extend" rather than "override", and add the relevant paths.
* Make a secondary manifest YAML file with this content and then add it on the "other" screen:

  ```yaml
  "Dr. Robotnik's Ring Racers":
    installDir:
      Ring Racers: {}
  ```

It might make sense for custom games to directly support adding extra `installDir` entries.

**Comment by Terrance** [comment]
> Make a custom entry titled `Dr. Robotnik's Ring Racers`, mark it as "extend" rather than "override", and add the relevant paths.

This is what I have currently, but it requires redefining all the specific paths to save files (which in this case is [three individual files](https://www.pcgamingwiki.com/wiki/Dr._Robotnik%27s_Ring_Racers#Save_game_data_location), but I've seen worse) and keeping them up-to-date, so you unfortunately don't benefit from extending the manifest entry.

> It might make sense for custom games to directly support adding extra installDir entries.

:+1:  I think this would be pretty useful to have, as standalone paths are somewhat unpredictable, and some Itch-installed games use paths based on the URL slug which don't always line up with the PCGW title.  This would presumably also mean being able to use `<base>` rather than having to write the full path for each target file/directory of fully custom games (i.e. those not extending from the manifest).

> Make a secondary manifest YAML file with this content and then add it on the "other" screen

Looks like that does the trick.  Would still be nice to have a way of managing custom install paths in the UI though, be it saved here or as part of a custom game entry.

**Comment by mtkennerly** [comment]
This will be available in the next release:

> https://github.com/user-attachments/assets/56a656ac-0f92-4ea5-b30d-fe4e97751d1a
