### ISSUE TITLE
Exclude games with cloud save

### ISSUE THREAD

**Issue by RobertoHigor** [mtkennerly/ludusavi#44]
There could be a way to use the "Save Cloud Syncing" settings and give the user the option to ignore titles that have cloud saving.
I't will also help for some online games, like MMORPG that trigger backup data.

For Example:
![image](https://user-images.githubusercontent.com/14026017/90314772-be070280-deec-11ea-8513-493322f827f1.png)

**Comment by mtkennerly** [comment]
Yeah, that should be feasible. Good idea! There might be cases where not everything is backed up to the cloud (e.g., maybe it backs up saves, but not configuration), but it certainly wouldn't hurt to have the option.

**Comment by Dave247** [comment]
I was thinking just this. There are some games that dont use cloud sync on Steam for whatever reason, and they are the ones I want to make sure I don't lose.

Rather then look at the PCGW field, another option is that you probably would be able to query the Steam API directly to get if a game supports cloud saves or not, like what SteamDB does.

**Comment by nioncode** [comment]
In any case this should be a customizable option, since some games support cloud save, but only if installed through steam (obviously) and even if installed through steam, sometimes cloud save did not work for me, so I prefer having my local savegame copies and sync those around.

**Comment by mtkennerly** [comment]
This  is finally coming in the next release :)

> ![image](https://github.com/mtkennerly/ludusavi/assets/4934192/f3ed7947-a606-4131-a738-f4b90ac5a930)

This setting doesn't apply to customized games or to games that already have a local backup. That way, you can have this setting enabled for most cases but still make some exceptions.
