### ISSUE TITLE
Exclude Drive Root Saves [Windows]

### ISSUE THREAD

**Issue by MattWThomas** [mtkennerly/ludusavi#48]
[Lords of Doom](https://www.pcgamingwiki.com/wiki/Lords_of_Doom) has its gamesave location reported as A:\, B:\ on PCGW because it stored saves on floppy. If you use these drives for internal HDDs, then the entire drives will be copied to your backups folder.

I think that a check for drive root save paths could be conducted to remove cases like these. In this case, I feel PCGW shouldn't be edited because it is not incorrect. But, it doesn't make sense to backup entire drive roots in general.

This would be a Windows-specific fix.

**Comment by mtkennerly** [comment]
Thanks for pointing this out. This would be a fix in the [Ludusavi Manifest](https://github.com/mtkennerly/ludusavi-manifest) importer script to rule out the paths as being too broad. I'll add a check for it.

PCGW probably could be edited with the exact folder or file name on the floppy disk, but we'll just have to work around it for now.

**Comment by mtkennerly** [comment]
I've just updated the manifest so that those entries are removed and marked appropriately. I didn't see any other entries that were just a drive letter, so it should be good now.

**Comment by MattWThomas** [comment]
Awesome! Thank you.
