### ISSUE TITLE
Support backing up and restoring across OSes

### ISSUE THREAD

**Issue by mystal** [mtkennerly/ludusavi#49]
For example, backing up the save data for a game on Linux and restoring it on Windows. This would be a killer feature for me, as I tend to hop between machines and OSes pretty often and some games just don't have cloud sync.

I might start looking into how to do this myself, but I would love to hear your thoughts. Any guidance is appreciated :)

**Comment by mtkennerly** [comment]
This is actually possible already, by configuring redirects in restore mode. It would be nice if Ludusavi already knew about how to redirect things by default, but that level of detail isn't available in the data set (i.e., it has a list of paths, but doesn't know which ones are equivalent between OSes).
