### ISSUE TITLE
[Readme/Comparison with other tools] Game Backup Monitor

### ISSUE THREAD

**Issue by Darthagnon** [mtkennerly/ludusavi#52]
[GBM GitHub](https://github.com/MikeMaximus/gbm)

[GBM Homepage](http://mikemaximus.github.io/gbm-web/)

Was wondering how Ludusavi compared with GBM. I personally use GBM, but can already see some interesting comparison points:

Ludusavi has (GBM hasn't):
- Mac support
- Playnite integration
- CLI
- Standardised save location listing from PCGamingWiki (GBM has a similar system, but afaik it's a manually updated list)

GBM has (Ludusavi lacks??):
- 7z compression of saves (#47 )
- Save history (multiple historical save files can be saved in 7z format) (#47)

At least to me, looks like Ludusavi is best for people who use Playnite, while GBM is completely standalone and better for people who don't use a launcher.

**Comment by mtkennerly** [comment]
Thanks for mentioning GBM - I can add it to the README :+1:

From trying it out on my system, I think another significant difference is the size of the data set:

* When opening GBM for the first time, the "official list import" has 479 game configurations. Ludusavi's data set currently has save locations for 7,985 games.
* When I run a full backup, GBM finds data for 17 games on my system, whereas Ludusavi finds 179.

Are there any premade expansions for the GBM data set? I'm not familiar with it, so I don't want to make an unfair comparison if there are expansions available.

**Comment by Darthagnon** [comment]
I think the [official config list](http://mikemaximus.github.io/gbm-web/GBM_Official.xml), which is indeed 479 games, is all there is. GBM is accepting contributions to the list (not sure how; website says to email him if you want to contribute). I don't contribute, as I recall seeing a post somewhere (GitHub issues?) saying that the official config list only accepts configs with default parameters, e.g. game installed on the C drive, etc. 

Since my PC has multiple partitions, with all games installed to ```E:\Program Files\Games``` or ```E:\Program Files\Games_portable```, plus I usually stick to cracked releases (no online dependencies that way, no saves in standard Steam folders though) and use multiple tools that change save paths (e.g. [Goldberg Emulator](https://gitlab.com/Mr_Goldberg/goldberg_emulator) for LAN multiplayer), as well as obscure games, I don't use any config lists and set up the save backup in GBM on a per-game basis. PCGamingWiki is a godsend for finding where some games save their data, or initial pointers to it.
