### ISSUE TITLE
Crash Windows

### ISSUE THREAD

**Issue by Skyline404** [mtkennerly/ludusavi#53]
App instantly crashes after start on windows 10.
OpenGL version works just fine

**Comment by mtkennerly** [comment]
Hi! This sounds normal. It just means that your system doesn't support any of the regular version's required graphics backends (DirectX 11, DirectX 12, Vulkan, Metal). Please continue to use the OpenGL version for now - in the future, the OpenGL version may become the default, but I'm not able to do that just yet because of some logistical issues.

**Comment by Skyline404** [comment]
Please can you explain how my system (Windows 10 with latest updates) and vega 56 don't support dx11,dx12,vulcan ?

**Comment by Skyline404** [comment]
> Hi! This sounds normal. It just means that your system doesn't support any of the regular version's required graphics backends (DirectX 11, DirectX 12, Vulkan, Metal). Please continue to use the OpenGL version for now - in the future, the OpenGL version may become the default, but I'm not able to do that just yet because of some logistical issues.


Please can you explain how my system (Windows 10 with latest updates) and vega 56 don't support dx11,dx12,vulcan ?

**Comment by mtkennerly** [comment]
Hmm, that card should be fine, so I suppose it could be an issue with the GUI library that Ludusavi uses instead. Could you try running it from the command line with the `RUST_BACKTRACE` environment variable set to `1` and then copy/paste the output here? That would confirm if it's graphics-related.

**Comment by Skyline404** [comment]
> Hmm, that card should be fine, so I suppose it could be an issue with the GUI library that Ludusavi uses instead. Could you try running it from the command line with the `RUST_BACKTRACE` environment variable set to `1` and then copy/paste the output here? That would confirm if it's graphics-related.

Build with  `cargo install ludusavi --debug`
Heres output. Am i doing it right ?
![WindowsTerminal-19-02-50-lRcsA](https://user-images.githubusercontent.com/32412867/96389091-0c1ed780-11b6-11eb-852e-e90505bf196c.jpg)

**Comment by mtkennerly** [comment]
`cargo run --bin ludusavi` won't show the backtrace because Cargo catches any errors and reports them on its own. Try just running `ludusavi`. (By the way, the backtrace thing seems to work even with the release version, although I'm not sure if the output is 100% identical between release and debug.)

**Comment by Skyline404** [comment]
> `cargo run --bin ludusavi` won't show the backtrace because Cargo catches any errors and reports them on its own. Try just running `ludusavi`. (By the way, the backtrace thing should work even with the release version, although I'm not sure if the output is 100% identical between release and debug.)

its shown nothinh to me

![WindowsTerminal-19-16-44-aOMZK](https://user-images.githubusercontent.com/32412867/96459154-73766f00-122a-11eb-9859-32c1e8c89677.jpg)

**Comment by mtkennerly** [comment]
Hmm, I wonder if the Scoop shim interferes with the backtrace functionality too. Sorry that this is a bit of a hassle, but could you download the standalone EXE from the [releases page](https://github.com/mtkennerly/ludusavi/releases/tag/v0.9.0) (either ludusavi-v0.9.0-win64.zip or ludusavi-v0.9.0-win32.zip) and try that from the console?

**Comment by Skyline404** [comment]
> Hmm, I wonder if the Scoop shim interferes with the backtrace functionality too. Sorry that this is a bit of a hassle, but could you download the standalone EXE from the [releases page](https://github.com/mtkennerly/ludusavi/releases/tag/v0.9.0) (either ludusavi-v0.9.0-win64.zip or ludusavi-v0.9.0-win32.zip) and try that from the console?

![WindowsTerminal-19-17-10-ZWpL2](https://user-images.githubusercontent.com/32412867/96462300-17154e80-122e-11eb-88ab-43a9a417ccb8.jpg)

**Comment by mtkennerly** [comment]
Oh, I just realized why (related to a step in the console-to-GUI transition) - I'll need to add something to make this easier for people to troubleshoot. In the meantime, please try this custom build instead:

[ludusavi-test-issue-53.zip](https://github.com/mtkennerly/ludusavi/files/5402562/ludusavi-test-issue-53.zip)

**Comment by Skyline404** [comment]
> Oh, I just realized why (related to a step in the console-to-GUI transition) - I'll need to add something to make this easier for people to troubleshoot. In the meantime, please try this custom build instead:
> 
> [ludusavi-test-issue-53.zip](https://github.com/mtkennerly/ludusavi/files/5402562/ludusavi-test-issue-53.zip)

Opens and closes immediately

**Comment by mtkennerly** [comment]
Still no backtrace or anything when you run it from the console? That's really weird. I don't think there's anything else I can do for now to make it show the backtrace in the console if even that didn't work. Just to confirm, you ran it from the console, not by double clicking the EXE, right?

**Comment by Skyline404** [comment]
> Still no backtrace or anything when you run it from the console? That's really weird. I don't think there's anything else I can do for now to make it show the backtrace in the console if even that didn't work. Just to confirm, you ran it from the console, not by double clicking the EXE, right?

Yes
