### ISSUE TITLE
Installing via winget

### ISSUE THREAD

**Issue by starsep** [mtkennerly/ludusavi#56]
It would be great if one could install ludusavi on Windows using [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/).

It is blocked by lack of installing software from zip: https://github.com/microsoft/winget-cli/issues/140
Possible solutions are:
- waiting for zip support
- implementing installer

Then one have to add a manifest to this repo: https://github.com/microsoft/winget-pkgs

**Comment by mtkennerly** [comment]
I'd be happy to submit a manifest to winget-pkgs once they support zips :+1: I'm not sure if I want to maintain an MSI, but I'll think about that option since some people may prefer it anyway.

**Comment by soredake** [comment]
https://github.com/microsoft/winget-pkgs/issues/35471

**Comment by redactedscribe** [comment]
winget version 1.3 (currently unreleased) will support portable/standalone apps, so there won't be a need to maintain an MSI. See https://github.com/microsoft/winget-cli/issues/182

**Comment by mtkennerly** [comment]
That's great news! I'll watch out for the release so that we can get Ludusavi listed :+1:

**Comment by redactedscribe** [comment]
Support for installing via Zip files will be supported in winget 1.4 it seems: https://github.com/microsoft/winget-cli/releases/tag/v1.4.2011-preview

**Comment by redactedscribe** [comment]
Nice work. Thanks!
