### ISSUE TITLE
Automatically search in all clients directories for games on scan/backup actions

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#58]
Currently Ludusavi uses expects the default locations of where games are installed to detect the saves automatically. This can be an issue where games are not installed in the default location and use `<path-to-game>` as the save directory. The current solution is to add the location of all extra non-default library directories as a root.

The proposal is to automatically scan for all the library locations of all clients automatically.

## Steam

1. Scan the `SteamPath` registry key in `HKEY_CURRENT_USER\SOFTWARE\Valve\Steam` to find steam installation directory.
![imagen](https://user-images.githubusercontent.com/1389286/101532748-997edc80-395a-11eb-98cf-01f3bf13add0.png)

2. Read the `<SteamPath>\steamapps\libraryfolders.vdf` in to get all the extra steam library directories.
![imagen](https://user-images.githubusercontent.com/1389286/101533799-e8794180-395b-11eb-8da5-c39e8350bdce.png)

## Epic
1. Scan the `ModSdkMetadataDir` registry key in `HKEY_CURRENT_USER\SOFTWARE\Epic Games\EOS` to find steam installation directory.
![imagen](https://user-images.githubusercontent.com/1389286/101534273-879e3900-395c-11eb-9c80-c834c9349119.png)

2. Read the `*.item` manifests that are in that directory to get the games install locations
![imagen](https://user-images.githubusercontent.com/1389286/101534569-f8ddec00-395c-11eb-9c20-3faa5ed30c62.png)
![imagen](https://user-images.githubusercontent.com/1389286/101534690-232fa980-395d-11eb-8947-de78e25c20b6.png)

Still need to look what can be done in other clients like Uplay, Origin, GOG Galaxy or itch.io. A possible solution to this, but that could only be used in Ludusavi-Playnite would be to use the [InstallDirectory](https://playnite.link/docs/api/Playnite.SDK.Models.Game.html#Playnite_SDK_Models_Game_InstallDirectory) property of the game.

**Comment by mtkennerly** [comment]
I've implemented this with a "find roots" button:

> https://user-images.githubusercontent.com/4934192/179449870-32461c89-faf8-4001-95bc-7d1f21e0d024.mp4
