### ISSUE TITLE
Use dropdown instead of radio buttons for root type

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#6]
This is dependent on https://github.com/hecrj/iced/issues/209. At the same time, we can add options for more stores in addition to "other", since right now there isn't enough room for that many options in the window.

**Comment by Songtronix** [comment]
Master has a dropdown widget now so it depends on a release and not really on https://github.com/hecrj/iced/issues/209 anymore :ok_hand:

**Comment by mtkennerly** [comment]
I may end up tweaking the dropdown style/colors, but here it is using the default:

> ![image](https://user-images.githubusercontent.com/4934192/108025388-65780580-6ff4-11eb-817c-b87033c12d21.png)
