### ISSUE TITLE
How to handle saves stored in %userprofile%/Local Settings/Application Data

### ISSUE THREAD

**Issue by micke1m** [mtkennerly/ludusavi#62]
I'm on Linux and I noticed [Darksiders Genesis](https://www.pcgamingwiki.com/wiki/Darksiders_Genesis) saves are not detected by ludusavi. 

The game seems to stores saves in `%userprofile%/Local Settings/Application Data`, but Windows redirects that to `%localappdata%` (`%userprofile%/AppData/Local`).

However wine does not redirect it in that way so they are not found by ludusavi when `%localappdata%` is specified as the path on PCGW.

So, should the path on PCGW be changed to `%userprofile%/Local Settings/Application Data` which would seem wrong to Windows users, or should ludusavi check that location when `%localappdata%` is being used.

**Comment by mtkennerly** [comment]
That's a good find :+1: I think Ludusavi should be responsible for checking it automatically. It doesn't strike me as something that would go on PCGW since it's more a quirk of Wine that of the game itself.

I found this interesting:

* If you put `%userprofile%/Local Settings/Application Data` in Windows Explorer, you get an error that it doesn't exist.
* If you `cd` to it in Command Prompt, that works. `dir` says "file not found". but if you `echo` to a file, it will show up in `%userprofile%/AppData/Local` successfully.

**Comment by micke1m** [comment]
I read it was used on Windows XP but Windows 7 and later redirects it to %appdata%. A bit strange some modern games still seem to store saves there.

**Comment by micke1m** [comment]
I also noticed this does not work `<home>/Documents/My Games/Borderlands 3`, because in the wineprefix it is `My Documents` for some reason, I wonder if proton has wineprefix set to windows XP or something.
Chaning it to `<winDocuments>/My  Games/Borderlands 3` makes it work.

Maybe in this chase it should just be changed to `{{p|userprofile\Documents}}` on PCGW.

**Comment by mtkennerly** [comment]
Yeah, that one's a mistake on the wiki, since `{{p|userprofile\Documents}}` is meant to be used for it: https://www.pcgamingwiki.com/wiki/Template:Path

> ![image](https://user-images.githubusercontent.com/4934192/107985867-f02b1700-6f98-11eb-828f-b3461fa0cc10.png)

**Comment by micke1m** [comment]
It seems wine simply redirects to XP paths.
%appdata% -> Application Data\
%localappdata% -> Local Settings\Application Data\
I don't know if there is a environment variable for the documents folder but newer windows uses Documents and wine/xp uses My Documents.

My guess is that any game that I have used in wine that has stored files in the AppData folder simply has the path hardcoded as %userprofile%/AppData/ and is not using the %appdata% or %localappdata% variables.
