### ISSUE TITLE
Symlinks taking twice the space if pointing to an already backed up path

### ISSUE THREAD

**Issue by Lucki** [mtkennerly/ludusavi#67]
Example:
[Deus Ex: Mankind Divided](https://www.pcgamingwiki.com/wiki/Deus_Ex:_Mankind_Divided) has 100 save slots and has roughly 1,5 GB of save data.
The linux version has a symlink to the remote steam save folder.
~~~
$ ll $XDG_DATA_HOME/feral-interactive/Deus\ Ex\ Mankind\ Divided/SaveData/
lrwxrwxrwx 1 lucki lucki 62 17. Nov 21:33 'Steam Saves (42528769)' -> /home/lucki/.local/share/Steam/userdata/42528769/337000/remote
~~~

~~~
$ du -h $XDG_DATA_HOME/Steam/userdata/42528769/337000/remote
1,6G	/home/lucki/.local/share/Steam/userdata/42528769/337000/remote
~~~

The UI shows only the remote folder which seems correct but it's taking twice the space into account (~ 3 GB) in the preview and in the resulting backup.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/1408843/114543915-29f76180-9c5a-11eb-8852-08504674e9cb.png)
</details>

-----
Side question: I'm not sure why it's trying to backup the binary `…/bin/DeusExMD`

**Comment by mtkennerly** [comment]
Thanks for pointing this out 👍 I'll look into this.

I'm not sure why the `DeusExMD` binary is being included either, unless it's under a folder pointed to by a symlink that's being backed up. Did you make a custom entry for the game?
