### ISSUE TITLE
Ignore cache folders in backup paths (and sort game list by file size)

### ISSUE THREAD

**Issue by Lucki** [mtkennerly/ludusavi#68]
Example: [Natural Selection 2](https://www.pcgamingwiki.com/wiki/Natural_Selection_2) dumps _everything_ in the config path including cache and workshop files bumping the backup size to 1,5 GB with unnecessary stuff:

~~~
$ du -h $XDG_CONFIG_HOME/Natural\ Selection\ 2/
758M	/home/lucki/.config/Natural Selection 2/cache
4,0K	/home/lucki/.config/Natural Selection 2/dumps
885M	/home/lucki/.config/Natural Selection 2/Workshop
~~~

I know this is difficult to decide but I think clearly marked `cache` or `dumps` folders can be safely ignored in a general way.
I'm not so sure about the workshop, there might be something in there that was removed from the servers or it has leaderboards in it like Distance does.

Other observations while going through some big backups (sorting by size would be handy…):
Xonotic dumps `dlcache` in the save path.
Rise of the Tomb Raider (feral-interactive) has `crashes` in the save path.
Shadow of the Tomb Raider (feral-interactive) dumps `crashes` and `cache` in the save path.
Mad Max (feral-interactive) also has `crashes`.
Rocket League has `Cache` and `Logs` in the save path.
Red Orchestra: Ostfronz 41-45 has `Cache` in the path.
Painkiller: Hell and Damnation has `Logs` in the path.
OpenTTD has `content_download` in the path - this might be to specific.
Killing Floor has `Cache` in the path.
Distance (Uinity) has `Analytics` and `WorkshopLevels` in the save path. It saves leaderboards in the workshop path.
Crusader Kings has `logs` in the path.
7 Days to Die (Unity) has `Analytics` in the path.

Maybe a simple checkbox would already be enough so it's possible to exclude a path at will.

**Comment by mtkennerly** [comment]
This is something that I think is best addressed by refining the data on PCGamingWiki (by listing specific subfolders instead of the whole parent folder). Ludusavi just trusts whatever data ends up in the manifest. Otherwise, you eventually end up with special cases to counteract special cases, when someone makes a Crash Simulator 2021 that saves replays in `crashes` 🙃 

Checkboxes for paths could be nice, though. You can accomplish the same goal with a custom entry, but the checkbox option would be easier for simple cases.

**Comment by Lucki** [comment]
I'm not sure if it even can be improved (with the current layout) in the wiki. Taking NS2 again as an example, the config files are in that specific folder - together with everything else. The wiki has to support exclude filter for that to take into account or specifically list every config file.

Same goes for the custom entry, I haven't found an exclude filter (yet) so I would have to set every config file separately.

Either way you're going with:
Please also allow sorting by size so it's easier to spot which games are probably the false positives with the biggest impact.

**Comment by davidhesselbom** [comment]
> Please also allow sorting by size so it's easier to spot which games are probably the false positives with the biggest impact.

I would also like to see this, but it should be made a separate issue to keep it from being lost in the discussion about the cache folders.

**Comment by mtkennerly** [comment]
I've split the info from this out into a couple of other tickets, so I'm going to close this one.
