### ISSUE TITLE
Recursively detect wine prefix root folders

### ISSUE THREAD

**Issue by Lucki** [mtkennerly/ludusavi#69]
It's common on Linux to have different wine bottles for different games because that allows some flexibility in configuration. An example for this is the steamcompat folder where every games has a subfolder with its appid and a wine prefix in it.

Of course there are also other programs to handle these like GameHub, Lutris or PlayOnLinux, ….
It would be nice if it would be possible to specify a root directory where wine prefixes get recursively detected.
E.g. GameHub currently (changes with the next version) saves prefixes in `$game_folder/_gamehub/compat/$wine_ver`. It's a bit cumbersome to specify each wine prefix root separately for each game.
I'm not sure how the other tools handle these prefixes - it's some years since I've used them the last time.

**Comment by mtkennerly** [comment]
This sounds like a good idea. I had briefly thought about it, but wasn't sure how common it was, so it's good to know that there's interest for it.

**Comment by mtkennerly** [comment]
The next release will allow globs in root paths.

The scan could become a bit slow, though, since it has to scan each root for each game. Ideally, it would pick the correct prefix folder for each game, but there may not be a good way to do that generically since it depends on how other tools/launchers name their prefix folders. I would be open to adding launcher-specific prefix detection if there's a stable way to find them from the game names.

**Comment by Lucki** [comment]
Thanks a lot!
I've transitioned to Bottles from GameHub and while Bottles encourages putting multiple programs into one prefix IMHO it's still necessary to split them across different prefixes. All prefixes from Bottles end up in one path either directly or as a symlink to the actual location.

> I would be open to adding launcher-specific prefix detection if there's a stable way to find them from the game names.

I'm not sure if there's a single solution to this. Most if not all launcher are presenting a simple text input on prefix creation which will then gets sanitized of special symbols and ends up as the folder name. So this will only work if the user correctly entered the whole game name and doesn't reuse the prefix. This could be a good first guess but seems unreliable.
At the end I'll link to some example sanitizer functions.

There could be another way to achieve this for a subset of games. Some launchers, e.g. Lutris and PoL, are hosting installation scripts which will end up in defined prefix names. For Lutris this is the "slug" if I recall correctly - I'm not using these installers so I'm not that familiar with them.
But honestly this doesn't seem worth the effort to get this working.

---
https://github.com/tkashkin/GameHub/blob/master/src/utils/Utils.vala#L477-L507
https://github.com/lutris/lutris/blob/master/lutris/util/strings.py#L15-L35
https://github.com/bottlesdevs/Bottles/blob/master/src/backend/managers/manager.py#L1083-L1085
