### ISSUE TITLE
Select if save folder should be recursive or not

### ISSUE THREAD

**Issue by ferrazpedro** [mtkennerly/ludusavi#70]
Hey! I noticed that [Sleeping Dogs: Definitive Edition](https://www.pcgamingwiki.com/wiki/Sleeping_Dogs:_Definitive_Edition) keeps it's save in the top of a folder that contains other things in it. Would it be possible to have a option to just get games for the top folder?

This is the situation: 
![image](https://user-images.githubusercontent.com/37643357/115425074-a7305280-a1d5-11eb-8d17-bdba1ba7414b.png)

Only the highlighted files are the saves. On the other folders the game keeps more than 3gb of files.

**Comment by mtkennerly** [comment]
Hi! There are a couple of ways to handle this:

* Ideally, it's best to narrow down the data on the wiki. That could be something like `{{p|game}}\Data\HK Autosave*|{{p|game}}\Data\HK GameSlot*` for the save section and `{{p|game}}\Data\HK Options|{{p|game}}\Data\DisplaySettings.xml` for the config section. `*` is a glob wildcard that will match the rest of the filename after that point.
* If the data on the wiki can't be updated (it should be fine in this case, but maybe there are cases where it's not feasible or accepted), then in Ludusavi you can click the edit icon next to the game to create a custom entry and narrow it down. For example, you could configure these two paths: `<base>/HK*` and `<base>/*.xml`, which should find just the files you want.

I've gone ahead and [updated the wiki](https://www.pcgamingwiki.com/w/index.php?title=Sleeping_Dogs:_Definitive_Edition&diff=1044110&oldid=995397), so Ludusavi's manifest will be updated automatically at midnight UTC.

There was also a suggestion in #68 to let you deselect specific folders/files without making a whole custom entry, but that's not available yet.

**Comment by ferrazpedro** [comment]
Thanks a lot! I didn't knew it was possible to be this specific in pcgamingwiki. From now on, I'll edit there directly.
