### ISSUE TITLE
Back up redirects

### ISSUE THREAD

**Issue by aabeba** [mtkennerly/ludusavi#72]
Use case: I have two (or more) computers running copies of the same game.

The computers back up the game's save files to the same cloud drive. The directory is slightly different on each computer (because the computers' usernames are different), but the structure of the drives is the same on either computer. The save paths are as follows (names changed):

Computer A: C:\Users\John\Save Games\Game Saves (Local Path 1)
Computer B: D:\Users\Stan\Save Games\Game Saves  (Local Path 2)

By default, then, each computer backs up to \\cloud folder\<game_name>\<drive_letter>\Users\<username>\<save_data>. Clearly, then, there were will be separate structures:

Computer A: \\cloud folder\<game_name>\drive-C\Users\John\<save_data> (Cloud Path 1)
Computer B: \\cloud folder\<game_name>\drive-D\Users\Stan\<save_data> (Cloud Path 2)

Fortunately, I can – using redirects – restore to either computer from the same location on the cloud drive. Let's say I pick the first path – Cloud Path 1.

Now I can back up and restore these save files fine on Computer A – everything will go from Local Path 1 to Cloud Path 1 and back. But what about Computer B? Sure, it can restore from Cloud Path 1, just like Computer A can, but it has no way I know of of backing up to Cloud Path 1 – it can only back up from its save folder of Local Path 1 to its default target: Cloud Path 2.

It would be cool to be able to both back up files to and restore files from the same directory on a cloud drive. Is there already a way to do this I'm unaware of?

**Comment by mtkennerly** [comment]
Hi! It's not possible right now, as you surmised, but I would be open to adding this.

**Comment by aabeba** [comment]
Thank you for the response, sir! For now I think I can make do with a simple copy script.

**Comment by andyktaylor** [comment]
I found a way to automate this (sort of), just make both files a Symbolic link of each other.
I used this guide to do it
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/
Seems to work fine for me
