### ISSUE TITLE
(nicety feature) lutris backup support

### ISSUE THREAD

**Issue by MissLav** [mtkennerly/ludusavi#73]
Support for backing up lutris's .config and .local folder

**Comment by mtkennerly** [comment]
Hi! You can do this currently by making a "custom game" entry for Lutris and adding the files/folders to back up. It's just not defined by default since Ludusavi is oriented for game saves specifically and not other game-related programs.

**Comment by MissLav** [comment]
oh tysm maybe a quick tips menu would be a good idea for explaining stuff like that
