### ISSUE TITLE
Support for emulators?

### ISSUE THREAD

**Issue by turtleship69** [mtkennerly/ludusavi#75]
This would likely require manual (hard coded/specific) support per emulator, but a way to backup saves from emulators would be nice.  
Some emulators have one folder and multiple files within it e.g. ppsspp has one folder with psp state and screenshot files, so you'd need to get a games id and match that to a game.  
I think some form of profile system would be good, like how playnite has, where you have a list of profiles for different emulators, and all of the settings etc are stored within it ([example](https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/Emulators/PPSSPP.yaml), although the contents would be very different).

**Comment by Faalagorn** [comment]
Alternatively, you could ask PCGW to include paths for emulators, they already cover them briefly here: https://www.pcgamingwiki.com/wiki/Emulation but that to cover might require more work on the wiki's side sadly. :(

**Comment by mtkennerly** [comment]
This is possible with custom entries, but I don't think it's feasible to add default entries for it. There are several variables that make it difficult to support automatically:

* Emulators can be installed in a custom location
* Emulators can be configured to store saves in a custom location
* Some systems store multiple games' saves in a single file (memory card)
* Some emulators base the save file name on the ROM name, so if you wanted to match a game to its save file, you may have to know the game's file name

Now, if people started having some particularly popular custom entries and wanted an easier way to share/reuse them, then I could see adding support for extra manifests. But depending on your configuration, this could be as simple as just making a custom entry to back up a common `C:/Emulators/Saves`.

**Comment by sharkusmanch** [comment]
I think supporting external/shared manifests might be a good feature. Not exactly sure what that would look like though.

`Yuzu` (and `RPCS3` I think) for instance has predictable save data paths based on a title ID. Personally, I've been automating this on my machine using a script that adds custom entries.

But I can see the benefit of a user defining their "Yuzu Root", referencing an external Yuzu Ludusavi manifest repo, and not having to worry about it again.

**Comment by mtkennerly** [comment]
That sounds good. I've opened #95 to track that enhancement.

**Comment by JVT038** [comment]
I have vibe coded a Python script that generated a manifest for all released PS3 games. 
The resulting Ludusavi manifest can be found here: https://github.com/JVT038/Ludusavi-RPCS3-manifest/tree/main
