### ISSUE TITLE
Working with cmd

### ISSUE THREAD

**Issue by DHYTFG** [mtkennerly/ludusavi#77]
Hello. I want to perform a backup using cmd and at the same time that the GUI settings are used. I have seen such an option somewhere, but now I can't find it. Tell me, what is this option?

**Comment by mtkennerly** [comment]
Hello! The GUI and command line automatically share the same settings. When you reconfigure the GUI, that updates the config file, and then the command line checks the same config file when it runs.

Are you seeing any issues where that doesn't seem to be the case?

**Comment by DHYTFG** [comment]
I've already figured it out. Thank you for the useful program. The best of everything I've tried.
