### ISSUE TITLE
Game not found despite being in the manifest

### ISSUE THREAD

**Issue by mkoza0922** [mtkennerly/ludusavi#79]
One of my games, _Ys VIII: Lacrimosa of DANA_, was not caught by the backup preview despite the game being on my disk. I added it as a custom game, but I am worried if other games might be missed as well:

![image](https://user-images.githubusercontent.com/81341325/136705904-31bd2bbe-7ac9-41ef-9901-011bdfcf9a68.png)
![image](https://user-images.githubusercontent.com/81341325/136705984-d4c55708-7055-4d74-9d56-dd335f50df70.png)

I did notice something, though I am not sure if is pertinent. The install dir listed in `manifest.yaml` is `Ys VIII Lacrimosa of Dana`, but my game is installed in `C:\Program Files (x86)\GOG Galaxy\Games\Ys VIII - Lacrimosa of DANA`.

I am not going to presume too much, but I wonder if it is trying to find an exact match for `Ys VIII Lacrimosa of Dana`, and not finding it?

**Comment by russelltennant** [comment]
Same issue with the GOG version of Prince of Persia The Sands of Time. It seems that where Steam removes colons from game names GOG replaces them with hyphens. So if the name of the game is Prince of Persia: The Sands of Time, the steam folder name is Prince of Persia The Sands of Time and the GOG folder name is Prince of Persia - The Sands of Time.

**Comment by mtkennerly** [comment]
This should be fixed by the same change that I made for #89, which will be included in the upcoming v0.11.0 release.
