### ISSUE TITLE
Sleeping Dogs backup includes game data files

### ISSUE THREAD

**Issue by davidhesselbom** [mtkennerly/ludusavi#83]
From the [PCGamingWiki entry](https://www.pcgamingwiki.com/wiki/Sleeping_Dogs#Save_game_data_location):

![sleepingdogs_saves](https://user-images.githubusercontent.com/4319680/145790441-103aec4f-0217-496a-8563-394c8e5ce468.PNG)

Understandably, Ludusavi does not read the "note", but simply includes the entire `Data` folder.

The save game files have no extension, so a wildcard pattern like `*.sav` won't work, but the files do have a leading `HK` and the word `Slot` in them. Thus,

```<path-to-game>\Data\HK*Slot*```

does the job when given as the path for a "custom game" in Ludusavi. I can make the change in PCGamingWiki, but would the double wildcards still work when Ludusavi pulls the data from there, or is there any other reason not to have double wildcards in a path string in a on PCGamingWiki entry?

Otherwise, would it be inadvisable to modify PCGamingWiki to list each savegame filename used by this game individually? There are 8 possible filenames, according to the note in the screenshot.

**Comment by mtkennerly** [comment]
Hi! Sorry for the delay in responding. Putting the double wildcards on PCGamingWiki would work fine, and I think that's probably the best solution here.
