### ISSUE TITLE
Unicode Characters & only custom items backup

### ISSUE THREAD

**Issue by JunglePredator** [mtkennerly/ludusavi#88]
Hi,

Is there a way to make ludusavi backup/scan only for custom entries?
I don't really need it scanning my documents folder or steam folders; I do however have some saved games in irregular locations I'd like an automated process for & which ludusavi would do fine on if other items can be skipped.

Also your program appears to have an issue with non-english unicode characters.
For instance I added a Japanese based path & while it seemed to accept it... it can't display it instead showing a series of empty squares.

**Comment by mtkennerly** [comment]
Hi!

* There's not a single specific option, but you could remove any configured roots, deselect any games that still show up (hit "deselect all"), and then just select the ones you're interested in. That selection will be remembered the next time you run Ludusavi as well.
* The Unicode characters are a current limitation of the graphics library that Ludusavi uses, unfortunately. There's another ticket for that: https://github.com/mtkennerly/ludusavi/issues/9

**Comment by JunglePredator** [comment]
Thanks
