### ISSUE TITLE
schedule backup feature

### ISSUE THREAD

**Issue by Bush-cat** [mtkennerly/ludusavi#90]
a handy feature for lazy people

**Comment by EmeraldSnorlax** [comment]
scheduled backups with versioning would be very nice!

**Comment by Auncaughbove17** [comment]
In case you are interested, I will share my personal solution for automatic backups.
I use [nssm](https://nssm.cc/download) (available via [choco](https://chocolatey.org/))
This is a dump of the nssm service:

You will want to replace `alima` with your username. If you use a local account replace "****" with your local password, if it's a microsoft account, use your Microsoft password, not your pin.
```ps1
nssm.exe install ludusavi C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
nssm.exe set ludusavi AppParameters C:\Users\alima\AppData\Roaming\ludusavi\service.ps1
nssm.exe set ludusavi AppDirectory C:\Users\alima\AppData\Roaming\ludusavi
nssm.exe set ludusavi AppExit Default Restart
nssm.exe set ludusavi DisplayName ludusavi
nssm.exe set ludusavi ObjectName .\alima "****"
nssm.exe set ludusavi Start SERVICE_DELAYED_AUTO_START
nssm.exe set ludusavi Type SERVICE_WIN32_OWN_PROCESS
```

The service.ps1 is this:
```ps1
$ludusaviPath = "C:\ProgramData\chocolatey\bin\ludusavi.exe"
$workingDir = "C:\Users\alima\AppData\Roaming\ludusavi"
$arguments = " backup --try-update --force"

Set-Location "$workingDir"
Write-Output "We're good to go. starting loop..."
Start-Transcript -path "$workingDir\ludusavi_service_log.txt" -append
while ($true) {
    Write-Output "=================================="
    Write-Output "running backup at $(get-date)..."
    Write-Output "=================================="
    Invoke-Expression "$ludusaviPath $arguments"
    
    Write-Output "sleeping for 12 hours"
    start-sleep -s "$(60*60*12)"
}
Stop-Transcript 
```

I have put the file simply in `%appdata%\ludusavi` that way it gets backed up like ludusavi itself, which I set up by adding it as a custom game (from `%appdata%\ludusavi\config.yaml`):

```yml
customGames:
  - name: ludusavi
    files:
      - "<winAppData>\\ludusavi\\cache.yaml"
      - "<winAppData>\\ludusavi\\config.yaml"
      - "<winAppData>\\ludusavi\\manifest.yaml"      
      - "<winAppData>\\ludusavi\\service.ps1"      
    registry: []
```

You want to create the service file, install nssm and change the nssm commands to use your paths/user. Then just run them and afterwards you should see a service called ludusavi. The service should start with windows and create a backup when it starts and then every 12 hours. The execution log will be saved to `%appdata%\ludusavi\ludusavi_service_log.txt`.

![image](https://user-images.githubusercontent.com/26165288/222840306-3efb4be5-5e69-48c6-a5c4-cefb8030ff81.png)

**Comment by seniorm0ment** [comment]
It would be really nice to have this integrated directly please.

**Comment by Nekotje** [comment]
this would be great. but also for the other OSen. i use linux my self and powershell is possible in linux but not standard installed.

**Comment by Alistair1231** [comment]
> this would be great. but also for the other OSen. i use linux my self and powershell is possible in linux but not standard installed.

@Nekotje The simplest solution would be a cron job (https://wiki.archlinux.org/title/cron#Basic_commands)
just run  `/path/to/ludusavi --try-manifest-update backup --force` for backup and `/path/to/ludusavi cloud upload --force` for cloud upload

**Comment by mtkennerly** [comment]
I've added a short guide for setting this up on Windows and Linux using standard system tools:

https://github.com/mtkennerly/ludusavi/blob/master/docs/help/backup-automation.md

Since there are already standard tools for this, I think I'll refrain from building it into Ludusavi directly for now. If anyone has trouble following the guide, let me know!
