### ISSUE TITLE
Steam deck support?

### ISSUE THREAD

**Issue by ANJ-Projects** [mtkennerly/ludusavi#91]
Have anyone tried this on the steamdeck yet?

**Comment by mtkennerly** [comment]
I don't have one to test with, but since the Steam Deck is using an x86 processor, the Linux version of Ludusavi *should* work on it. If anyone is able to test it, that would be great.

**Comment by magne4000** [comment]
Just tested it. It launches correctly in game mode (once controller mapped as keyboard+mouse). In desktop mode le interface is way too big though.
Also, in game mode, picking a folder does not work as the folder selection window hides itself immediatly.

**Comment by LeSnake04** [comment]
I can help getting it on flathub.

**Comment by marcusziade** [comment]
What is the status of this?

I'm looking to use this in Dark Souls II

**Comment by psymin** [comment]
> Just tested it. It launches correctly in game mode (once controller mapped as keyboard+mouse). In desktop mode the interface is way too big though. Also, in game mode, picking a folder does not work as the folder selection window hides itself immediatly.

In Desktop mode the UI is certainly way too big to be usable.

**Comment by mtkennerly** [comment]
Can you resize it smaller after it opens, or is it stuck being too big? Ludusavi's minimum window size is supposed to be 640x480, but I'm not sure how the initial size is determined. Might be related to https://github.com/iced-rs/iced/issues/1028.

**Comment by mtkennerly** [comment]
Also, if anyone's willing to try a preview of the upcoming Ludusavi release, I'm curious if it happens to fix either of the Steam Deck issues. The preview includes some updates to the graphics libraries: [ludusavi-v0.10.0-post.29+9d2547a-linux.zip](https://github.com/mtkennerly/ludusavi/files/9151849/ludusavi-v0.10.0-post.29%2B9d2547a-linux.zip) (also: [list of changes](https://github.com/mtkennerly/ludusavi/blob/9d2547a638d6236a1cebe1fbed1b3646e9e48f58/CHANGELOG.md#Unreleased))

**Comment by psymin** [comment]
The file in ludusavi-v0.10.0-post.29+9d2547a-linux.zip appears to have the same GUI issue on the Steam Deck as the other release.

> 
![Screenshot_20220726_093924](https://user-images.githubusercontent.com/326578/181049878-f6a80cab-db4f-4e2a-aeeb-0be1c194abbe.png)

**Comment by psymin** [comment]
> 

Picking a folder in Game Mode doesn't appear to work, since by default the mouse cannot move to the bottom of the screen for "Cancel" or "OK"

**Comment by mtkennerly** [comment]
Thanks for testing it! This is very helpful. I think I'll need to report this to one of the libraries I'm using, but there are a couple that it could be. Could you please try the below two tests to help narrow it down?

Also, on your Steam Deck, under "System Settings" -> "Display and Monitor" -> "Display Configuration", what is the global scale? I found a [Reddit thread](https://www.reddit.com/r/SteamDeck/comments/ukqcei/my_desktop_mode_is_too_big/) where it came up for troubleshooting a similar issue, although it was for the entire desktop mode, not just one program.

### Iced stopwatch
[iced-stopwatch.zip](https://github.com/mtkennerly/ludusavi/files/9192316/iced-stopwatch.zip)

This creates a window with a stopwatch. The default size is 1024x768, but it may be larger when adjusted for DPI.

<img width="1280" alt="ludusavi-deck-iced" src="https://user-images.githubusercontent.com/4934192/181081898-e3332ab3-992b-4701-b1af-1e8c5bd15c57.png">

### Winit window
[winit-window.zip](https://github.com/mtkennerly/ludusavi/files/9192317/winit-window.zip)

This creates a basic window with nothing inside. The default size is 128x128, but it may be larger when adjusted for DPI.

<img width="1280" alt="ludusavi-deck-winit" src="https://user-images.githubusercontent.com/4934192/181081915-d48b8664-5712-4b58-92f1-44da0b1bc46c.png">

**Comment by psymin** [comment]
global scale is 100%

![Screenshot_20220727_164244](https://user-images.githubusercontent.com/326578/181385343-5b6ace0d-875d-4003-b067-56b5ecef560d.png)
![Screenshot_20220727_164314](https://user-images.githubusercontent.com/326578/181385346-c0ecfa6a-225e-42e6-ba6a-70093b6b6195.png)
![Screenshot_20220727_164408](https://user-images.githubusercontent.com/326578/181385352-793d6acd-554a-464f-bec0-aa5ca78a4557.png)
[window-output.log](https://github.com/mtkennerly/ludusavi/files/9204057/window-output.log)

**Comment by mtkennerly** [comment]
@psymin Thanks again! It looks like an issue with Winit. I've reported the issue to them here: https://github.com/rust-windowing/winit/issues/2401.

**Comment by mtkennerly** [comment]
From the [Winit documentation](https://docs.rs/winit/latest/winit/dpi/index.html#how-is-the-scale-factor-calculated), it sounds like a workaround would be to set this environment variable: `export WINIT_X11_SCALE_FACTOR=1` . That would force a scale factor of 1 instead of the 4.5 that it's coming up with.

**Comment by psymin** [comment]
> From the [Winit documentation](https://docs.rs/winit/0.27.0/winit/dpi/index.html#how-is-the-scale-factor-calculated), it sounds like a workaround would be to set this environment variable: `export WINIT_X11_SCALE_FACTOR=1` . That would force a scale factor of 1 instead of the 4.5 that it's coming up with.

That works.

Using `WINIT_X11_SCALE_FACTOR=1 ./ludusavi` in desktop mode makes Ludusavi work as expected.

**Comment by mtkennerly** [comment]
Nice :+1: I've added a note about it to the README.

For now, I'm assuming that the folder picker issue in game mode is a limitation of game mode itself, since it's not something a game would ordinarily do. If that's not the case, then it would need to be addressed first in this library that Ludusavi uses: https://github.com/balthild/native-dialog-rs

**Comment by NgJason** [comment]
The above solution worked for me. The Discover Store (assuming Flatpak) doesn't detect rclone, so I'm trying this out via the executable from release
