### ISSUE TITLE
Ludusavi thinks my entire Documents folder is "The Lord of the Rings: The Return of the King"

### ISSUE THREAD

**Issue by ajddavid452** [mtkennerly/ludusavi#92]
![ludusavi_UB7uZCkB4j](https://user-images.githubusercontent.com/9932984/158456508-2dfb330a-7e72-4a8f-9453-57d912c12949.png)

**Comment by mtkennerly** [comment]
Thanks for reporting this! I've fixed this up in the manifest (https://github.com/mtkennerly/ludusavi-manifest/commit/9ace2cea0d6110c8b8d125851cad984ae9f47ee4), so this will be fixed locally the next time you launch Ludusavi.
