### ISSUE TITLE
Incremental backup?

### ISSUE THREAD

**Issue by safijari** [mtkennerly/ludusavi#93]
Is this something you've considered doing? I've implemented one for myself on linux using rsync but would be nice to have it in ludusavi itself. I can also help with implementing something like this if you're interested but I'm not particularly fluent in rust and would need some guidance.

**Comment by safijari** [comment]
Ok, I ended up implementing this a different way. For anyone that may get here looking for this feature and is unwilling to use a syncing solution (e.g. using dropbox, syncthing, google drive, whatever), I recommend using borg backup. On linux, I now run the following command to create an incremental and fully version controlled backup of all my saves.

```
cd ~
ludusavi backup --path ludusavi-backup-old --merge
borg create --stats ludusavi-backup::"`date`" ludusavi-backup-old```

Where my borg repo and ludusavi backup folder are both in the home directory, and I'm running the commands from the home directory and using relative paths.

**Comment by mtkennerly** [comment]
The `merge` option is an incremental backup, but for the version control aspect, I think you've found a good solution :+1:
